import type { MetadataRoute } from 'next'

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Registra Brasil',
    short_name: 'Registra',
    description: 'Arquivo público de declarações de políticos brasileiros',
    start_url: '/',
    display: 'standalone',
    background_color: '#f9fafb',
    theme_color: '#1d4ed8',
    lang: 'pt-BR',
    categories: ['news', 'politics'],
    orientation: 'any',
    icons: [
      {
        src: '/favicon.ico',
        sizes: '48x48',
        type: 'image/x-icon',
      },
      // /icon is auto-generated by app/icon.tsx (512×512 PNG).
      {
        src: '/icon',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
    shortcuts: [
      {
        name: 'Buscar declarações',
        url: '/buscar',
        description: 'Pesquisar declarações de políticos',
      },
      {
        name: 'Políticos',
        url: '/politicos',
        description: 'Ver lista de políticos',
      },
      {
        name: 'Estatísticas',
        url: '/estatisticas',
        description: 'Ver estatísticas do acervo',
      },
    ],
  }
}
