-- Politicians batch 6: Governors + Mayors (2023-2026 terms)
INSERT INTO politicians (slug, full_name, common_name, party, state, role, is_active) VALUES
  -- Governors
  ('claudio-castro',       'Cláudio Bomfim de Castro e Silva',           'Cláudio Castro',       'PL',     'RJ', 'Governador do Rio de Janeiro',            true),
  ('wilson-lima',          'Wilson Miranda Lima',                        'Wilson Lima',          'UNIAO',  'AM', 'Governador do Amazonas',                  true),
  ('ibaneis-rocha',        'Ibaneis Rocha Barros Junior',                'Ibaneis Rocha',        'MDB',    'DF', 'Governador do Distrito Federal',          true),
  ('eduardo-riedel',       'Eduardo Corrêa Riedel',                      'Eduardo Riedel',       'PSDB',   'MS', 'Governador de Mato Grosso do Sul',        true),
  ('mauro-mendes',         'Mauro Mendes Ferreira',                      'Mauro Mendes',         'UNIAO',  'MT', 'Governador de Mato Grosso',               true),
  ('elmano-de-freitas',    'Elmano de Freitas da Costa',                 'Elmano de Freitas',    'PT',     'CE', 'Governador do Ceará',                     true),
  ('rafael-fonteles',      'Rafael Fonteles',                            'Rafael Fonteles',      'PT',     'PI', 'Governador do Piauí',                     true),
  ('jeronimo-rodrigues',   'Jerônimo Rodrigues Souza',                   'Jerônimo Rodrigues',   'PT',     'BA', 'Governador da Bahia',                     true),
  ('paulo-dantas',         'Paulo Dantas',                               'Paulo Dantas',         'MDB',    'AL', 'Governador de Alagoas',                   true),
  ('raquel-lyra',          'Raquel Teixeira Lyra',                       'Raquel Lyra',          'PSDB',   'PE', 'Governadora de Pernambuco',               true),
  ('joao-azevedo',         'João Azevêdo Lins Filho',                    'João Azevêdo',         'PSB',    'PB', 'Governador da Paraíba',                   true),
  ('fatima-bezerra',       'Maria de Fátima Bezerra',                    'Fátima Bezerra',       'PT',     'RN', 'Governadora do Rio Grande do Norte',      true),
  ('carlos-brandao',       'Carlos Orleans Brandão Júnior',              'Carlos Brandão',       'PSB',    'MA', 'Governador do Maranhão',                  true),
  ('fabio-mitidieri',      'Fábio Henrique Mitidieri Leite Silva',       'Fábio Mitidieri',      'PSD',    'SE', 'Governador de Sergipe',                   true),
  ('renato-casagrande',    'José Renato Casagrande',                     'Renato Casagrande',    'PSB',    'ES', 'Governador do Espírito Santo',            true),
  ('helder-barbalho',      'Helder Zahluth Barbalho',                    'Helder Barbalho',      'MDB',    'PA', 'Governador do Pará',                      true),
  ('gladson-cameli',       'Gladson de Lima Cameli',                     'Gladson Cameli',       'PP',     'AC', 'Governador do Acre',                      true),
  ('antonio-denarium',     'Antônio Oliverio Garcia de Almeida Denarium','Antônio Denarium',     'PP',     'RR', 'Governador de Roraima',                   true),
  ('clecio-luis',          'Clécio Vieira de Oliveira Luís',             'Clécio Luís',          'SOLID.', 'AP', 'Governador do Amapá',                     true),
  ('eduardo-leite',        'Eduardo Figueiredo Cavalheiro Leite',        'Eduardo Leite',        'PSDB',   'RS', 'Ex-Governador do Rio Grande do Sul',      true),
  ('eduardo-mauro',        'Mauro Carlesse',                             'Mauro Carlesse',       'Indep.', 'TO', 'Ex-Governador do Tocantins',              true),
  ('wanderlei-barbosa',    'Wanderlei Barbosa Castro',                   'Wanderlei Barbosa',    'REP',    'TO', 'Governador de Tocantins',                 true),
  ('jorginho-mello',       'Jorge Luiz de Mello',                        'Jorginho Mello',       'PL',     'SC', 'Governador de Santa Catarina',            true),
  -- Mayors of capitals
  ('ricardo-nunes',        'Ricardo Luis Reis Nunes',                    'Ricardo Nunes',        'MDB',    'SP', 'Prefeito de São Paulo',                   true),
  ('eduardo-paes',         'Eduardo da Costa Paes',                      'Eduardo Paes',         'PSD',    'RJ', 'Prefeito do Rio de Janeiro',              true),
  ('fuad-noman',           'Fuad Jorge Noman Filho',                     'Fuad Noman',           'PSD',    'MG', 'Prefeito de Belo Horizonte',              true),
  ('joao-campos',          'João Henrique de Andrade Lima Campos',       'João Campos',          'PSB',    'PE', 'Prefeito do Recife',                      true),
  ('topazio-silveira',     'Topázio Silveira Neto',                      'Topázio Silveira',     'MDB',    'SC', 'Prefeito de Florianópolis',               true),
  ('jose-sarto',           'José Sarto Nogueira Moreira',                'José Sarto',           'PDT',    'CE', 'Ex-Prefeito de Fortaleza',                true),
  ('sebastiao-melo',       'Sebastião Afonso Viana Macedo Neves',        'Sebastião Melo',       'MDB',    'RS', 'Prefeito de Porto Alegre',                true),
  ('rafael-greca',         'Rafael Valdomiro Greca de Macedo',           'Rafael Greca',         'PSD',    'PR', 'Ex-Prefeito de Curitiba',                 true),
  ('bruno-reis',           'Bruno Soares Reis',                          'Bruno Reis',           'UNIAO',  'BA', 'Prefeito de Salvador',                    true),
  ('david-almeida',        'David Antônio Abisai Pereira de Almeida',    'David Almeida',        'AVANTE', 'AM', 'Prefeito de Manaus',                      true),
  ('boulos-prefeito',      'Guilherme Castro Boulos',                    'Boulos (pref)',        'PSOL',   'SP', 'Ex-Candidato a Prefeito de SP',           false)
ON CONFLICT (slug) DO NOTHING;
