-- Politicians batch 7: Senators, deputies, historical figures (broad spectrum)
INSERT INTO politicians (slug, full_name, common_name, party, state, role, is_active) VALUES
  -- Senators (2023-2031 term)
  ('jaques-wagner',        'Jaques Wagner',                              'Jaques Wagner',        'PT',     'BA', 'Senador',                                 true),
  ('humberto-costa',       'Humberto Sérgio Costa Lima',                 'Humberto Costa',       'PT',     'PE', 'Senador',                                 true),
  ('randolfe-rodrigues',   'Randolfe Rodrigues Alves',                   'Randolfe Rodrigues',   'PT',     'AP', 'Senador',                                 true),
  ('alessandro-vieira',    'Alessandro Ferreira Vieira',                 'Alessandro Vieira',    'MDB',    'SE', 'Senador',                                 true),
  ('efraim-filho',         'Efraim de Araújo Morais Filho',              'Efraim Filho',         'UNIAO',  'PB', 'Senador',                                 true),
  ('rogerio-marinho',      'Rogério Simonetti Marinho',                  'Rogério Marinho',      'PL',     'RN', 'Senador',                                 true),
  ('omar-aziz',            'Omar Aziz',                                  'Omar Aziz',            'PSD',    'AM', 'Senador',                                 true),
  ('otto-alencar',         'Otto Roberto Mendonça de Alencar',           'Otto Alencar',         'PSD',    'BA', 'Senador',                                 true),
  ('soraya-thronicke',     'Soraya Thronicke',                           'Soraya Thronicke',     'PODE',   'MS', 'Senadora',                                true),
  ('marcos-pontes',        'Marcos Cesar Pontes',                        'Marcos Pontes',        'PL',     'SP', 'Senador',                                 true),
  ('eliziane-gama',        'Eliziane Pedrosa Gama Santos',               'Eliziane Gama',        'PSD',    'MA', 'Senadora',                                true),
  ('wellington-fagundes',  'Wellington Fagundes',                        'Wellington Fagundes',  'PL',     'MT', 'Senador',                                 true),
  ('angelo-coronel',       'Ângelo Marcos Noronha Coronel',              'Ângelo Coronel',       'PSD',    'BA', 'Senador',                                 true),
  ('cid-gomes',            'Cid Ferreira Gomes',                         'Cid Gomes',            'PSB',    'CE', 'Ex-Senador',                              true),
  ('contarato',            'Fabiano Contarato',                          'Fabiano Contarato',    'PT',     'ES', 'Senador',                                 true),
  ('plinio-valerio',       'Plínio Valério',                             'Plínio Valério',       'PSDB',   'AM', 'Senador',                                 true),
  ('mecias-de-jesus',      'Mecias de Jesus Pereira da Silva',           'Mecias de Jesus',      'REP',    'RR', 'Senador',                                 true),
  ('izalci-lucas',         'Izalci Lucas Ferreira',                      'Izalci Lucas',         'PL',     'DF', 'Senador',                                 true),
  ('esperidiao-amin',      'Esperidião Amin Helou Filho',                'Esperidião Amin',      'PP',     'SC', 'Senador',                                 true),
  -- Federal Deputies (broad spectrum)
  ('tabata-amaral',        'Tabata Claudia Amaral de Pontes',            'Tabata Amaral',        'PSB',    'SP', 'Deputada Federal',                        true),
  ('erika-hilton',         'Erika Hilton',                               'Erika Hilton',         'PSOL',   'SP', 'Deputada Federal',                        true),
  ('samia-bomfim',         'Sâmia de Souza Bomfim',                      'Sâmia Bomfim',         'PSOL',   'SP', 'Deputada Federal',                        true),
  ('fernanda-melchionna',  'Fernanda Marchesan Melchionna',              'Fernanda Melchionna',  'PSOL',   'RS', 'Deputada Federal',                        true),
  ('marcel-van-hattem',    'Marcel van Hattem',                          'Marcel van Hattem',    'NOVO',   'RS', 'Deputado Federal',                        true),
  ('kim-kataguiri',        'Kim Kataguiri',                              'Kim Kataguiri',        'UNIAO',  'SP', 'Ex-Deputado Federal',                     true),
  ('felipe-carreras',      'Felipe Luiz Sampaio Martins Carreras',       'Felipe Carreras',      'PSB',    'PE', 'Deputado Federal',                        true),
  ('aguinaldo-ribeiro',    'Aguinaldo Velloso Borges Ribeiro',           'Aguinaldo Ribeiro',    'PP',     'PB', 'Deputado Federal',                        true),
  ('elmar-nascimento',     'Elmar Nascimento',                           'Elmar Nascimento',     'UNIAO',  'BA', 'Deputado Federal',                        true),
  ('lindbergh-farias',     'Lindbergh Farias Filho',                     'Lindbergh Farias',     'PT',     'RJ', 'Deputado Federal',                        true),
  ('taliria-petrone',      'Talíria Petrone Soares',                     'Talíria Petrone',      'PSOL',   'RJ', 'Deputada Federal',                        true),
  ('adriana-ventura',      'Adriana Ventura',                            'Adriana Ventura',      'NOVO',   'SP', 'Deputada Federal',                        true),
  ('duarte-jr',            'Duarte Júnior',                              'Duarte Jr',            'REP',    'MA', 'Deputado Federal',                        true),
  ('orlando-silva',        'Orlando Silva de Jesus Júnior',              'Orlando Silva',        'PCdoB',  'SP', 'Deputado Federal',                        true),
  ('chico-alencar',        'Francisco Rodrigues de Alencar Filho',       'Chico Alencar',        'PSOL',   'RJ', 'Deputado Federal',                        true),
  ('jandira-feghali',      'Jandira Feghali',                            'Jandira Feghali',      'PCdoB',  'RJ', 'Deputada Federal',                        true),
  ('jose-guimaraes',       'José Guimarães',                             'José Guimarães',       'PT',     'CE', 'Deputado Federal',                        true),
  ('zeca-dirceu',          'José Eduardo de Oliveira Dirceu',            'Zeca Dirceu',          'PT',     'PR', 'Deputado Federal',                        true),
  ('afonso-florence',      'Afonso Bandeira Florence',                   'Afonso Florence',      'PT',     'BA', 'Deputado Federal',                        true),
  ('marcelo-freixo',       'Marcelo Ribeiro Freixo',                     'Marcelo Freixo',       'PSB',    'RJ', 'Ex-Deputado Federal',                     true),
  ('general-girao',        'Bernardo José de Queiroga Girão',            'General Girão',        'PL',     'RN', 'Deputado Federal',                        true),
  ('julia-zanatta',        'Julia Nayara Zanatta',                       'Julia Zanatta',        'PL',     'SC', 'Deputada Federal',                        true),
  ('sanderson',            'Sanderson Avelino dos Santos',               'Sanderson',            'PL',     'RS', 'Deputado Federal',                        true),
  ('filipe-barros',        'Filipe Nakada Barros',                       'Filipe Barros',        'PL',     'PR', 'Deputado Federal',                        true),
  ('cabo-gilberto',        'Gilberto Silva',                             'Cabo Gilberto Silva',  'PL',     'PB', 'Deputado Federal',                        true),
  ('guiga-peixoto',        'Guilherme Derrite',                          'Guilherme Derrite',    'PP',     'SP', 'Ex-Deputado Federal',                     true),
  ('andre-fufuca',         'André Gustavo Fufuca de Farias',             'André Fufuca',         'PP',     'MA', 'Ministro do Esporte',                     true),
  -- Historical / recurring figures
  ('fernando-henrique',    'Fernando Henrique Cardoso',                  'FHC',                  'PSDB',   'SP', 'Ex-Presidente (1995-2002)',               true),
  ('luis-inacio-passado',  'Luiz Inácio da Silva',                       'Lula (hist.)',         'PT',     'SP', 'Ex-Presidente (2003-2010) / Presidente',  true),
  ('marta-suplicy',        'Marta Teresa Smith de Vasconcellos Suplicy', 'Marta Suplicy',        'MDB',    'SP', 'Ex-Prefeita / Senadora',                  true),
  ('jose-serra',           'José Serra',                                 'José Serra',           'PSDB',   'SP', 'Ex-Governador / Senador',                 true),
  ('geraldo-alckmin',      'Geraldo José Rodrigues Alckmin Filho',       'Geraldo Alckmin',      'PSB',    'SP', 'Vice-Presidente',                         true),
  ('aecio-neves',          'Aécio Neves da Cunha',                       'Aécio Neves',          'PSDB',   'MG', 'Deputado Federal',                        true),
  ('doria',                'João Doria Júnior',                          'João Doria',           'PSDB',   'SP', 'Ex-Governador de SP',                     true),
  ('collor',               'Fernando Affonso Collor de Mello',           'Collor',               'PTB',    'AL', 'Ex-Presidente (1990-1992) / Ex-Senador',  false),
  ('cunha',                'Eduardo Cosentino da Cunha',                 'Eduardo Cunha',        'MDB',    'RJ', 'Ex-Presidente da Câmara',                 false),
  ('lulinha',              'Fábio Luís Lula da Silva',                   'Lulinha',              'Indep.', 'SP', 'Empresário / Filho de Lula',              true),
  ('flavio-dino-antigo',   'Flávio Dino (Maranhão)',                     'Dino (ex-gov)',        'PSB',    'MA', 'Ex-Governador do Maranhão',               false),
  ('jean-paul-prates',     'Jean Paul Terra Prates',                     'Jean Paul Prates',     'PT',     'RN', 'Ex-Presidente da Petrobras',              true),
  ('magda-chambriard',     'Magda Maria de Regina Chambriard',           'Magda Chambriard',     'Indep.', 'RJ', 'Presidente da Petrobras',                 true),
  ('aloizio-mercadante',   'Aloizio Mercadante Oliva',                   'Aloizio Mercadante',   'PT',     'SP', 'Presidente do BNDES',                     true),
  ('roberto-campos-neto',  'Roberto de Oliveira Campos Neto',            'Campos Neto',          'Indep.', 'DF', 'Ex-Presidente do Banco Central',          true),
  ('gabriel-galipolo',     'Gabriel Muricca Galípolo',                   'Gabriel Galípolo',     'Indep.', 'SP', 'Presidente do Banco Central',             true)
ON CONFLICT (slug) DO NOTHING;
