-- Politicians batch 5: STF justices + Lula III cabinet (2023-2026)
INSERT INTO politicians (slug, full_name, common_name, party, state, role, is_active) VALUES
  ('gilmar-mendes',        'Gilmar Ferreira Mendes',                     'Gilmar Mendes',        'Indep.', 'DF', 'Ministro do STF',                         true),
  ('luis-roberto-barroso', 'Luís Roberto Barroso',                       'Luís Roberto Barroso', 'Indep.', 'RJ', 'Ex-Presidente do STF',                    true),
  ('dias-toffoli',         'José Antonio Dias Toffoli',                  'Dias Toffoli',         'Indep.', 'SP', 'Ministro do STF',                         true),
  ('carmen-lucia',         'Cármen Lúcia Antunes Rocha',                 'Cármen Lúcia',         'Indep.', 'MG', 'Ministra do STF',                         true),
  ('luiz-fux',             'Luiz Fux',                                   'Luiz Fux',             'Indep.', 'RJ', 'Ministro do STF',                         true),
  ('edson-fachin',         'Luiz Edson Fachin',                          'Edson Fachin',         'Indep.', 'PR', 'Ministro do STF',                         true),
  ('nunes-marques',        'Kassio Nunes Marques',                       'Nunes Marques',        'Indep.', 'PI', 'Ministro do STF',                         true),
  ('andre-mendonca',       'André Luiz de Almeida Mendonça',             'André Mendonça',       'Indep.', 'DF', 'Ministro do STF',                         true),
  ('cristiano-zanin',      'Cristiano Zanin Martins',                    'Cristiano Zanin',      'Indep.', 'SP', 'Ministro do STF',                         true),
  ('alexandre-padilha',    'Alexandre Rocha Santos Padilha',             'Alexandre Padilha',    'PT',     'SP', 'Ministro das Relações Institucionais',    true),
  ('rui-costa',            'Rui Costa dos Santos',                       'Rui Costa',            'PT',     'BA', 'Ministro da Casa Civil',                  true),
  ('silvio-almeida',       'Silvio Luiz de Almeida',                     'Silvio Almeida',       'Indep.', 'SP', 'Ex-Ministro dos Direitos Humanos',        true),
  ('nisia-trindade',       'Nísia Verônica Trindade Lima',               'Nísia Trindade',       'Indep.', 'RJ', 'Ex-Ministra da Saúde',                    true),
  ('mauro-vieira',         'Mauro Luiz Iecker Vieira',                   'Mauro Vieira',         'Indep.', 'SC', 'Ministro das Relações Exteriores',        true),
  ('jose-mucio',           'José Múcio Monteiro Filho',                  'José Múcio',           'Indep.', 'PE', 'Ministro da Defesa',                      true),
  ('luiz-marinho',         'Luiz Marinho',                               'Luiz Marinho',         'PT',     'SP', 'Ministro do Trabalho',                    true),
  ('alexandre-silveira',   'Alexandre Silveira de Oliveira',             'Alexandre Silveira',   'PSD',    'MG', 'Ministro de Minas e Energia',             true),
  ('esther-dweck',         'Esther Dweck',                               'Esther Dweck',         'Indep.', 'RJ', 'Ministra da Gestão',                      true),
  ('wellington-dias',      'José Wellington Barroso de Araújo Dias',     'Wellington Dias',      'PT',     'PI', 'Ministro do Desenvolvimento Social',      true),
  ('jorge-messias',        'Jorge Rodrigo Araújo Messias',               'Jorge Messias',        'Indep.', 'DF', 'Advogado-Geral da União',                 true),
  ('sonia-guajajara',      'Sônia Bone de Souza Silva Santos',           'Sônia Guajajara',      'PSOL',   'MA', 'Ministra dos Povos Indígenas',            true),
  ('anielle-franco',       'Anielle Silva Franco',                       'Anielle Franco',       'PT',     'RJ', 'Ministra da Igualdade Racial',            true),
  ('carlos-favaro',        'Carlos Henrique Baqueta Fávaro',             'Carlos Fávaro',        'PSD',    'MT', 'Ministro da Agricultura',                 true),
  ('cida-goncalves',       'Aparecida Gonçalves Chagas',                 'Cida Gonçalves',       'PT',     'MS', 'Ex-Ministra das Mulheres',                true),
  ('waldez-goes',          'Waldez Góes',                                'Waldez Góes',          'PDT',    'AP', 'Ministro da Integração Nacional',         true),
  ('paulo-teixeira',       'Paulo César Ribeiro Lima Teixeira',          'Paulo Teixeira',       'PT',     'SP', 'Ministro do Desenvolvimento Agrário',     true),
  ('andre-de-paula',       'André Ferreira de Paula',                    'André de Paula',       'PSD',    'PE', 'Ministro da Pesca',                       true),
  ('margareth-menezes',    'Maria Margareth Menezes da Purificação',     'Margareth Menezes',    'Indep.', 'BA', 'Ministra da Cultura',                     true),
  ('marcio-macedo',        'Márcio Costa Macêdo',                        'Márcio Macêdo',        'PT',     'SE', 'Ministro da Secretaria-Geral',            true),
  ('luciana-santos',       'Luciana Santos',                             'Luciana Santos',       'PCdoB',  'PE', 'Ministra da Ciência e Tecnologia',        true),
  ('marina-silva',         'Maria Osmarina Marina Silva Vaz de Lima',    'Marina Silva',         'REDE',   'AC', 'Ministra do Meio Ambiente',               true),
  ('camilo-santana',       'Camilo Sobreira de Santana',                 'Camilo Santana',       'PT',     'CE', 'Ministro da Educação',                    true),
  ('juscelino-filho',      'Juscelino Resende Filho',                    'Juscelino Filho',      'UNIAO',  'MA', 'Ex-Ministro das Comunicações',            true),
  ('ricardo-lewandowski',  'Enrique Ricardo Lewandowski',                'Lewandowski',          'Indep.', 'SP', 'Ministro da Justiça',                     true)
ON CONFLICT (slug) DO NOTHING;
