-- Batch 129: STF constitutional debates 2024-2025 (Part 2)
DO $$
DECLARE
  v_mor UUID; v_gil UUID; v_bar UUID; v_tof UUID; v_car UUID;
  v_fux UUID; v_fac UUID; v_nun UUID; v_mend UUID; v_zan UUID;
  v_din UUID; v_jai UUID; v_lul UUID; v_nik UUID; v_edu UUID;
  v_fla UUID; v_bia UUID; v_mfe UUID; v_rog UUID; v_hug UUID;
  v_dav UUID; v_pac UUID; v_mvh UUID; v_ran UUID; v_lin UUID;
  v_bou UUID; v_jaw UUID; v_hum UUID; v_jom UUID; v_lew UUID;
  v_orl UUID; v_eri UUID; v_sam UUID; v_tal UUID; v_had UUID;
  c_ant UUID; c_obs UUID; c_ame UUID; c_abu UUID; c_aut UUID;
  c_des UUID; c_con UUID; c_int UUID; c_odi UUID;
BEGIN
  SELECT id INTO v_mor FROM politicians WHERE slug = 'alexandre-de-moraes';
  SELECT id INTO v_gil FROM politicians WHERE slug = 'gilmar-mendes';
  SELECT id INTO v_bar FROM politicians WHERE slug = 'luis-roberto-barroso';
  SELECT id INTO v_tof FROM politicians WHERE slug = 'dias-toffoli';
  SELECT id INTO v_car FROM politicians WHERE slug = 'carmen-lucia';
  SELECT id INTO v_fux FROM politicians WHERE slug = 'luiz-fux';
  SELECT id INTO v_fac FROM politicians WHERE slug = 'edson-fachin';
  SELECT id INTO v_nun FROM politicians WHERE slug = 'nunes-marques';
  SELECT id INTO v_mend FROM politicians WHERE slug = 'andre-mendonca';
  SELECT id INTO v_zan FROM politicians WHERE slug = 'cristiano-zanin';
  SELECT id INTO v_din FROM politicians WHERE slug = 'flavio-dino';
  SELECT id INTO v_jai FROM politicians WHERE slug = 'jair-bolsonaro';
  SELECT id INTO v_lul FROM politicians WHERE slug = 'lula';
  SELECT id INTO v_nik FROM politicians WHERE slug = 'nikolas-ferreira';
  SELECT id INTO v_edu FROM politicians WHERE slug = 'eduardo-bolsonaro';
  SELECT id INTO v_fla FROM politicians WHERE slug = 'flavio-bolsonaro';
  SELECT id INTO v_bia FROM politicians WHERE slug = 'bia-kicis';
  SELECT id INTO v_mfe FROM politicians WHERE slug = 'marco-feliciano';
  SELECT id INTO v_rog FROM politicians WHERE slug = 'rogerio-marinho';
  SELECT id INTO v_hug FROM politicians WHERE slug = 'hugo-motta';
  SELECT id INTO v_dav FROM politicians WHERE slug = 'davi-alcolumbre';
  SELECT id INTO v_pac FROM politicians WHERE slug = 'rodrigo-pacheco';
  SELECT id INTO v_mvh FROM politicians WHERE slug = 'marcel-van-hattem';
  SELECT id INTO v_ran FROM politicians WHERE slug = 'randolfe-rodrigues';
  SELECT id INTO v_lin FROM politicians WHERE slug = 'lindbergh-farias';
  SELECT id INTO v_bou FROM politicians WHERE slug = 'guilherme-boulos';
  SELECT id INTO v_jaw FROM politicians WHERE slug = 'jaques-wagner';
  SELECT id INTO v_hum FROM politicians WHERE slug = 'humberto-costa';
  SELECT id INTO v_jom FROM politicians WHERE slug = 'jorge-messias';
  SELECT id INTO v_lew FROM politicians WHERE slug = 'lewandowski';
  SELECT id INTO v_orl FROM politicians WHERE slug = 'orlando-silva';
  SELECT id INTO v_eri FROM politicians WHERE slug = 'erika-hilton';
  SELECT id INTO v_sam FROM politicians WHERE slug = 'samia-bomfim';
  SELECT id INTO v_tal FROM politicians WHERE slug = 'taliria-petrone';
  SELECT id INTO v_had FROM politicians WHERE slug = 'fernando-haddad';

  SELECT id INTO c_ant FROM categories WHERE slug = 'antidemocratico';
  SELECT id INTO c_obs FROM categories WHERE slug = 'obstrucao-justica';
  SELECT id INTO c_ame FROM categories WHERE slug = 'ameaca-instituicoes';
  SELECT id INTO c_abu FROM categories WHERE slug = 'abuso-de-poder';
  SELECT id INTO c_aut FROM categories WHERE slug = 'autoritarismo';
  SELECT id INTO c_des FROM categories WHERE slug = 'desinformacao';
  SELECT id INTO c_con FROM categories WHERE slug = 'conflito-interesses';
  SELECT id INTO c_int FROM categories WHERE slug = 'intimidacao';
  SELECT id INTO c_odi FROM categories WHERE slug = 'discurso-de-odio';

  -- 1
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_gil, 'Gilmar Mendes defende colegialidade no STF e critica decisões monocráticas excessivas.', 'A colegialidade é o coração do Supremo. Decisões monocráticas são exceção, não regra.', 'Palestra no IDP sobre funcionamento da Corte após críticas à expansão de monocráticas.', 'verified', false, '2024-08-05', 'https://www.conjur.com.br/2024-ago-05/gilmar-mendes-colegialidade-stf-monocraticas/', 'news_article', 1, 'IDP Brasília', 'Seminário de Direito Constitucional', 'gilmar-colegialidade-stf-b129-1') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 2
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nik, 'Nikolas Ferreira afirma que STF virou tribunal de exceção contra conservadores.', 'O STF se transformou em tribunal de exceção. Isso não pode continuar.', 'Discurso na tribuna da Câmara contra decisões do STF em inquéritos.', 'verified', true, '2024-08-12', 'https://www.camara.leg.br/noticias/1088654-nikolas-stf-tribunal-excecao', 'news_article', 4, 'Câmara dos Deputados', 'Sessão plenária', 'nikolas-stf-excecao-b129-2') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 3
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moraes suspende contas do X no Brasil após Musk descumprir decisões judiciais.', 'A plataforma descumpriu reiteradamente ordens judiciais. A suspensão é medida necessária.', 'Decisão monocrática determinando a suspensão do X no Brasil após descumprimento de ordens.', 'verified', true, '2024-08-30', 'https://www1.folha.uol.com.br/poder/2024/08/moraes-suspende-x-brasil.shtml', 'news_article', 3, 'STF', 'Decisão monocrática', 'moraes-suspende-x-b129-3') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;
  -- 4
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro chama suspensão do X de ditadura judicial e pede ação internacional.', 'O Brasil virou uma ditadura digital. Precisamos da pressão internacional para restaurar a liberdade.', 'Postagem no X via VPN após suspensão da rede pelo STF.', 'verified', true, '2024-08-31', 'https://www.cnnbrasil.com.br/politica/eduardo-bolsonaro-suspensao-x-ditadura/', 'social_media_post', 4, 'Brasília', 'Postagem em rede social', 'eduardo-ditadura-x-b129-4') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 5
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_bar, 'Barroso defende decisão sobre X e diz que nenhuma plataforma está acima da lei.', 'Nenhuma empresa, por maior que seja, pode se colocar acima da Constituição brasileira.', 'Entrevista coletiva como presidente do STF defendendo decisão sobre suspensão do X.', 'verified', true, '2024-09-02', 'https://g1.globo.com/politica/noticia/2024/09/02/barroso-x-nenhuma-plataforma-acima-lei.ghtml', 'news_article', 2, 'STF', 'Coletiva de imprensa', 'barroso-x-plataforma-lei-b129-5') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 6
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mvh, 'Marcel van Hattem pede na Câmara derrubada da decisão de Moraes sobre o X.', 'É absurdo que um ministro sozinho decida calar milhões de brasileiros.', 'Pronunciamento na Câmara após suspensão do X no Brasil.', 'verified', false, '2024-09-03', 'https://www.camara.leg.br/noticias/1089221-marcel-hattem-x-moraes', 'news_article', 3, 'Câmara dos Deputados', 'Sessão plenária', 'marcel-x-moraes-b129-6') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 7
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fla, 'Flávio Bolsonaro afirma que STF precisa ser disciplinado pelo Congresso.', 'O Congresso precisa agir. O STF não pode continuar legislando por decisão monocrática.', 'Discurso no plenário do Senado defendendo PEC que limita poderes do STF.', 'verified', true, '2024-09-05', 'https://www12.senado.leg.br/noticias/flavio-bolsonaro-stf-pec', 'news_article', 4, 'Senado Federal', 'Sessão plenária', 'flavio-disciplina-stf-b129-7') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 8
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_pac, 'Pacheco defende equilíbrio entre Poderes e rejeita PEC contra STF.', 'O Senado não vai patrocinar uma guerra de Poderes. Equilíbrio institucional é fundamental.', 'Coletiva no Senado após PEC de limitação a decisões monocráticas ganhar tração.', 'verified', true, '2024-09-06', 'https://www12.senado.leg.br/noticias/materias/2024/09/06/pacheco-equilibrio-poderes', 'news_article', 1, 'Senado Federal', 'Coletiva de imprensa', 'pacheco-equilibrio-poderes-b129-8') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 9
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro convoca apoiadores para ato na Paulista contra STF em 7 de setembro.', 'Dia 7 vamos mostrar que o povo não aceita a tirania do STF.', 'Convocação em live semanal para ato do 7 de setembro na Paulista.', 'verified', true, '2024-09-01', 'https://www1.folha.uol.com.br/poder/2024/09/bolsonaro-convoca-7-setembro-paulista-stf.shtml', 'social_media_post', 4, 'Brasília', 'Live em rede social', 'bolsonaro-convoca-7-set-b129-9') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_aut, true FROM ins;
  -- 10
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula diz que ataques ao STF são tentativa golpista desesperada.', 'Atacar o Supremo é ato antidemocrático. Não há espaço para golpistas no Brasil.', 'Pronunciamento na cerimônia da Independência em Brasília.', 'verified', true, '2024-09-07', 'https://g1.globo.com/politica/noticia/2024/09/07/lula-ataques-stf-golpismo.ghtml', 'news_article', 2, 'Brasília', '7 de Setembro', 'lula-ataques-stf-golpe-b129-10') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 11
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nik, 'Nikolas discursa no ato da Paulista e promete impeachment de Moraes.', 'Moraes vai cair. Esse ato é o começo do fim da tirania.', 'Discurso no ato bolsonarista da Avenida Paulista em 7 de setembro.', 'verified', true, '2024-09-07', 'https://www.metropoles.com/brasil/politica-br/nikolas-paulista-impeachment-moraes', 'news_article', 5, 'Av. Paulista', 'Ato 7 de Setembro', 'nikolas-paulista-impeachment-b129-11') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 12
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro discursa na Paulista e chama Moraes de ditador.', 'Alexandre de Moraes é um ditador. O povo brasileiro não vai se curvar.', 'Discurso no palanque do ato da Avenida Paulista em 7 de setembro.', 'verified', true, '2024-09-07', 'https://www.cnnbrasil.com.br/politica/bolsonaro-paulista-moraes-ditador/', 'news_article', 5, 'Av. Paulista', 'Ato 7 de Setembro', 'bolsonaro-paulista-ditador-b129-12') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 13
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_car, 'Cármen Lúcia repudia chamamentos a desobediência ao STF em ato na Paulista.', 'Democracia exige respeito às instituições. Desobedecer ao STF é desobedecer à Constituição.', 'Entrevista à imprensa como presidente do TSE após ato bolsonarista.', 'verified', true, '2024-09-09', 'https://www.poder360.com.br/justica/carmen-lucia-desobediencia-stf-paulista/', 'news_article', 1, 'TSE', 'Coletiva de imprensa', 'carmen-desobediencia-stf-b129-13') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 14
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_bia, 'Bia Kicis apresenta pedido de impeachment de Moraes na Câmara.', 'Apresento hoje o pedido que representa a voz do povo contra Alexandre de Moraes.', 'Protocolo de pedido de impeachment de Moraes no gabinete do presidente da Câmara.', 'verified', true, '2024-09-10', 'https://www.camara.leg.br/noticias/1089991-bia-kicis-impeachment-moraes', 'news_article', 4, 'Câmara dos Deputados', 'Protocolo de pedido', 'bia-impeachment-moraes-b129-14') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 15
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_hug, 'Hugo Motta sinaliza que pedido de impeachment de Moraes não terá tramitação prioritária.', 'Não vou pautar pedido sem base jurídica sólida. A Câmara não será palco de revanchismo.', 'Entrevista após receber pedido de impeachment de Moraes.', 'verified', false, '2024-09-12', 'https://www.cnnbrasil.com.br/politica/hugo-motta-impeachment-moraes-pauta/', 'news_article', 1, 'Câmara dos Deputados', 'Entrevista à imprensa', 'hugo-motta-impeachment-moraes-b129-15') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 16
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fac, 'Fachin defende inquérito das milícias digitais como instrumento legítimo do STF.', 'O inquérito investiga ataques reais à democracia. É instrumento constitucional legítimo.', 'Voto em questão de ordem sobre competência do inquérito das milícias digitais.', 'verified', false, '2024-09-15', 'https://www.conjur.com.br/2024-set-15/fachin-milicias-digitais-inquerito/', 'news_article', 1, 'STF', 'Sessão do Plenário', 'fachin-milicias-digitais-b129-16') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 17
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fux, 'Fux faz voto divergente em caso de marco temporal e causa tensão institucional.', 'O marco temporal é válido. Não se pode aplicar retroativamente entendimento novo.', 'Voto divergente em julgamento sobre marco temporal das terras indígenas no STF.', 'verified', true, '2024-09-18', 'https://www1.folha.uol.com.br/poder/2024/09/fux-marco-temporal-voto-divergente.shtml', 'news_article', 1, 'STF', 'Julgamento marco temporal', 'fux-marco-temporal-b129-17') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 18
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_din, 'Flávio Dino afirma em sua primeira sessão que STF é baluarte contra autoritarismo.', 'O Supremo é a última trincheira contra o autoritarismo. Vou honrar essa responsabilidade.', 'Discurso de posse como ministro do STF indicado por Lula.', 'verified', true, '2024-02-22', 'https://g1.globo.com/politica/noticia/2024/02/22/dino-posse-stf-autoritarismo.ghtml', 'news_article', 2, 'STF', 'Posse no STF', 'dino-posse-autoritarismo-b129-18') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 19
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_rog, 'Rogério Marinho acusa STF de censura prévia contra parlamentares.', 'Há censura prévia sendo aplicada contra parlamentares. Isso é inconstitucional.', 'Discurso no Senado criticando decisões do STF sobre comunicações de parlamentares.', 'verified', false, '2024-09-20', 'https://www12.senado.leg.br/noticias/rogerio-marinho-censura-stf', 'news_article', 3, 'Senado Federal', 'Sessão plenária', 'rogerio-censura-stf-b129-19') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 20
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_ran, 'Randolfe Rodrigues defende STF e alerta para golpe em andamento.', 'Há uma tentativa golpista em andamento. O STF é essencial para impedir retrocesso.', 'Entrevista a jornalistas no Congresso sobre ataques ao STF.', 'verified', false, '2024-09-22', 'https://www.poder360.com.br/congresso/randolfe-stf-golpe/', 'news_article', 1, 'Congresso Nacional', 'Entrevista à imprensa', 'randolfe-golpe-stf-b129-20') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 21
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro diz na CPAC Brasil que STF sequestrou a democracia.', 'Nossa democracia foi sequestrada por 11 togados. Isso precisa acabar.', 'Discurso no CPAC Brasil em Balneário Camboriú.', 'verified', true, '2024-09-28', 'https://www.cnnbrasil.com.br/politica/eduardo-cpac-balneario-stf/', 'news_article', 5, 'Balneário Camboriú', 'CPAC Brasil 2024', 'eduardo-cpac-stf-sequestro-b129-21') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 22
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moraes mantém prisão de general Braga Netto em ação do 8 de janeiro.', 'A prisão preventiva é necessária para evitar risco à ordem pública e obstrução.', 'Decisão individual mantendo prisão do general Braga Netto após manifestações de PRF.', 'verified', true, '2024-12-14', 'https://www.cnnbrasil.com.br/politica/moraes-mantem-prisao-braga-netto/', 'news_article', 3, 'STF', 'Decisão monocrática', 'moraes-braga-netto-prisao-b129-22') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;
  -- 23
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro diz que Moraes persegue generais para atingi-lo pessoalmente.', 'Moraes quer me atingir através dos generais. É perseguição política escancarada.', 'Coletiva à imprensa após prisão de Braga Netto.', 'verified', true, '2024-12-15', 'https://www1.folha.uol.com.br/poder/2024/12/bolsonaro-moraes-generais-perseguicao.shtml', 'news_article', 4, 'Brasília', 'Coletiva de imprensa', 'bolsonaro-moraes-generais-b129-23') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 24
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_zan, 'Zanin defende que STF tem legitimidade para julgar atos golpistas.', 'A Corte tem competência constitucional para apurar os atos de 8 de janeiro.', 'Voto em sessão do STF sobre competência da Corte para julgar réus do 8 de janeiro.', 'verified', false, '2024-10-03', 'https://www.conjur.com.br/2024-out-03/zanin-competencia-stf-8-janeiro/', 'news_article', 1, 'STF', 'Sessão do Plenário', 'zanin-competencia-8jan-b129-24') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 25
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nun, 'Nunes Marques vota pela redução de penas em ações do 8 de janeiro.', 'As penas aplicadas são desproporcionais ao que se apurou em cada caso concreto.', 'Voto divergente em ação penal sobre réus do 8 de janeiro.', 'verified', false, '2024-10-05', 'https://www.poder360.com.br/justica/nunes-marques-penas-8-janeiro/', 'news_article', 1, 'STF', 'Sessão do Plenário', 'nunes-penas-8jan-b129-25') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 26
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mend, 'André Mendonça se declara impedido em caso de marco temporal.', 'Declaro-me impedido em virtude de minha atuação anterior como advogado-geral.', 'Decisão de impedimento na sessão de julgamento do marco temporal.', 'verified', false, '2024-10-08', 'https://www.jota.info/stf/do-supremo/mendonca-impedimento-marco-temporal', 'news_article', 1, 'STF', 'Sessão do Plenário', 'mendonca-impedimento-marco-b129-26') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 27
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_tof, 'Dias Toffoli anula provas da Odebrecht e gera controvérsia no STF.', 'As provas obtidas no âmbito da Lava Jato foram imprestáveis e devem ser anuladas.', 'Decisão monocrática anulando provas da delação da Odebrecht.', 'verified', true, '2024-10-10', 'https://www1.folha.uol.com.br/poder/2024/10/toffoli-anula-provas-odebrecht.shtml', 'news_article', 2, 'STF', 'Decisão monocrática', 'toffoli-anula-odebrecht-b129-27') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 28
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moraes acusa imprensa estrangeira de desinformar sobre STF.', 'Certos veículos estrangeiros são porta-vozes dos extremistas. Não vamos nos curvar.', 'Discurso em seminário no IDP sobre desinformação e jurisdição.', 'verified', false, '2024-10-12', 'https://www.poder360.com.br/justica/moraes-imprensa-estrangeira-desinformacao/', 'news_article', 2, 'IDP Brasília', 'Seminário', 'moraes-imprensa-desinf-b129-28') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;
  -- 29
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lin, 'Lindbergh Farias defende PL da regulação de redes aprovado pelo STF.', 'A regulação das redes é urgente. Não se pode permitir que plataformas sejam zonas de fake news.', 'Discurso na Câmara defendendo decisão do STF sobre responsabilidade de plataformas.', 'verified', false, '2024-10-15', 'https://www.camara.leg.br/noticias/1091221-lindbergh-regulacao-redes', 'news_article', 1, 'Câmara dos Deputados', 'Sessão plenária', 'lindbergh-regulacao-redes-b129-29') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 30
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_bou, 'Boulos defende o STF e diz que direita quer destruir a Constituição.', 'A direita radical quer destruir a Constituição. O STF é nossa defesa.', 'Discurso em ato pró-democracia na Avenida Paulista.', 'verified', false, '2024-10-20', 'https://www1.folha.uol.com.br/poder/2024/10/boulos-ato-pro-democracia.shtml', 'news_article', 1, 'São Paulo', 'Ato pró-democracia', 'boulos-direita-constituicao-b129-30') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 31
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_bar, 'Barroso reage em entrevista e diz que STF é alvo por proteger a democracia.', 'Somos atacados porque protegemos a democracia. Não vamos recuar.', 'Entrevista ao Roda Viva como presidente do STF.', 'verified', true, '2024-10-22', 'https://www.roda-viva.tv/barroso-stf-ataques/', 'news_article', 2, 'TV Cultura', 'Roda Viva', 'barroso-rodaviva-stf-b129-31') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 32
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mfe, 'Marco Feliciano compara ministros do STF a tiranos do século XX.', 'Ministros do STF agem como tiranos. Isso lembra os piores regimes do século XX.', 'Discurso no plenário da Câmara atacando o STF.', 'verified', true, '2024-10-25', 'https://www.camara.leg.br/noticias/1091998-marco-feliciano-stf-tiranos', 'news_article', 4, 'Câmara dos Deputados', 'Sessão plenária', 'feliciano-stf-tiranos-b129-32') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 33
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jom, 'Jorge Messias defende indicação do governo para vaga no STF.', 'Vamos continuar indicando juristas comprometidos com a Constituição e com o Estado democrático.', 'Entrevista como AGU sobre processo de indicação ao STF.', 'verified', false, '2024-11-02', 'https://g1.globo.com/politica/noticia/2024/11/02/messias-indicacao-stf.ghtml', 'news_article', 1, 'Brasília', 'Coletiva de imprensa', 'messias-indicacao-stf-b129-33') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 34
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lew, 'Lewandowski como ministro da Justiça defende diálogo entre Poderes.', 'O ministério está à disposição para construir pontes entre Executivo, Legislativo e Judiciário.', 'Entrevista como ministro da Justiça sobre tensão entre Poderes.', 'verified', false, '2024-11-05', 'https://www.poder360.com.br/governo/lewandowski-dialogo-poderes/', 'news_article', 1, 'Brasília', 'Entrevista à imprensa', 'lewandowski-dialogo-poderes-b129-34') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 35
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro pede aos EUA impeachment internacional de Moraes.', 'Os EUA precisam agir. Moraes está ferindo direitos de cidadãos com dupla cidadania.', 'Entrevista a rede americana conservadora sobre STF brasileiro.', 'verified', true, '2024-11-08', 'https://www.foxnews.com/world/eduardo-bolsonaro-moraes-impeachment', 'news_article', 5, 'Washington, EUA', 'Entrevista à Fox News', 'eduardo-eua-impeachment-moraes-b129-35') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 36
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_sam, 'Sâmia Bomfim defende STF e critica pauta reacionária na Câmara.', 'A pauta bolsonarista contra o STF visa destruir conquistas democráticas.', 'Discurso na tribuna da Câmara em defesa do STF.', 'verified', false, '2024-11-10', 'https://www.camara.leg.br/noticias/1092789-samia-pauta-reacionaria', 'news_article', 1, 'Câmara dos Deputados', 'Sessão plenária', 'samia-pauta-reacionaria-b129-36') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 37
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_eri, 'Erika Hilton denuncia ataques transfóbicos acobertados por discurso anti-STF.', 'Usam o STF como desculpa para disseminar transfobia e ataques a minorias.', 'Discurso na tribuna da Câmara em sessão sobre violência política.', 'verified', true, '2024-11-12', 'https://www.camara.leg.br/noticias/1092891-erika-hilton-transfobia-stf', 'news_article', 2, 'Câmara dos Deputados', 'Sessão plenária', 'erika-transfobia-anti-stf-b129-37') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 38
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_tal, 'Talíria Petrone denuncia criminalização de movimentos sociais sob pretexto de ordem pública.', 'Movimentos sociais estão sendo criminalizados. O STF precisa proteger o direito de manifestação.', 'Pronunciamento na Câmara sobre operações contra manifestantes.', 'verified', false, '2024-11-15', 'https://www.camara.leg.br/noticias/1092945-taliria-criminalizacao-movimentos', 'news_article', 1, 'Câmara dos Deputados', 'Sessão plenária', 'taliria-criminalizacao-movimentos-b129-38') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 39
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_orl, 'Orlando Silva defende marco civil e regulação de redes.', 'Regulamentar redes não é censura. É civilizar o espaço digital.', 'Entrevista sobre projeto do marco civil das redes.', 'verified', false, '2024-11-18', 'https://www.cnnbrasil.com.br/politica/orlando-silva-marco-civil-redes/', 'news_article', 1, 'Brasília', 'Entrevista à imprensa', 'orlando-marco-civil-b129-39') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 40
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moraes alerta que plataformas digitais não podem ser refúgio para extremismo.', 'As redes não podem ser refúgio de golpistas. Vamos continuar impondo limites legais.', 'Palestra em seminário do Instituto Innovare sobre desinformação.', 'verified', true, '2024-11-20', 'https://www.conjur.com.br/2024-nov-20/moraes-plataformas-extremismo/', 'news_article', 2, 'São Paulo', 'Seminário Innovare', 'moraes-plataformas-extremismo-b129-40') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;
  -- 41
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nik, 'Nikolas Ferreira apresenta projeto para limitar monocráticas de ministros do STF.', 'Vamos limitar o poder absoluto dos ministros. Basta de monocráticas.', 'Coletiva na Câmara sobre apresentação do projeto.', 'verified', true, '2024-11-22', 'https://www.camara.leg.br/noticias/1093221-nikolas-monocraticas-pl', 'news_article', 3, 'Câmara dos Deputados', 'Coletiva de imprensa', 'nikolas-pl-monocraticas-b129-41') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 42
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_had, 'Haddad defende STF em reunião com banqueiros e diz que estabilidade institucional é essencial.', 'A estabilidade das instituições é essencial para os mercados. Não há economia forte sem Estado de Direito.', 'Reunião com executivos da Febraban em São Paulo.', 'verified', false, '2024-11-25', 'https://valor.globo.com/brasil/noticia/2024/11/25/haddad-stf-febraban-estabilidade.ghtml', 'news_article', 1, 'São Paulo', 'Reunião com Febraban', 'haddad-stf-estabilidade-b129-42') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 43
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fla, 'Flávio Bolsonaro anuncia viagem aos EUA para denunciar Moraes.', 'Vou a Washington denunciar o que Moraes faz no Brasil.', 'Anúncio em rede social sobre viagem aos EUA.', 'verified', true, '2024-11-28', 'https://www.metropoles.com/brasil/politica-br/flavio-viagem-eua-denunciar-moraes', 'social_media_post', 5, 'Brasília', 'Postagem em rede social', 'flavio-eua-denunciar-moraes-b129-43') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 44
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moraes determina indiciamento de Bolsonaro em inquérito do golpe.', 'Há elementos suficientes de autoria e materialidade para o indiciamento.', 'Decisão em inquérito da PF sobre tentativa de golpe.', 'verified', true, '2024-11-21', 'https://g1.globo.com/politica/noticia/2024/11/21/moraes-indiciamento-bolsonaro-golpe.ghtml', 'news_article', 3, 'STF', 'Decisão', 'moraes-indicia-bolsonaro-b129-44') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;
  -- 45
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro nega tentativa de golpe e diz que PF mente no relatório.', 'Isso é mentira. Nunca tentei dar golpe algum. A PF mente para me atingir.', 'Coletiva à imprensa após indiciamento pela PF.', 'verified', true, '2024-11-22', 'https://www.cnnbrasil.com.br/politica/bolsonaro-nega-golpe-pf/', 'news_article', 4, 'Brasília', 'Coletiva de imprensa', 'bolsonaro-nega-golpe-pf-b129-45') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 46
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_din, 'Flávio Dino vota por condenação de generais do 8 de janeiro.', 'As provas são robustas. Houve planejamento e execução de atos golpistas.', 'Voto em ação penal sobre oficiais militares do 8 de janeiro.', 'verified', false, '2024-12-05', 'https://www.jota.info/stf/do-supremo/dino-condenacao-generais-8-janeiro', 'news_article', 2, 'STF', 'Sessão do Plenário', 'dino-condena-generais-b129-46') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 47
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_car, 'Cármen Lúcia defende urna eletrônica e rebate desinformação.', 'As urnas eletrônicas são seguras. Não há margem para dúvida baseada em evidências.', 'Discurso como presidente do TSE em cerimônia de diplomação.', 'verified', true, '2024-12-12', 'https://www.tse.jus.br/comunicacao/noticias/2024/12/carmen-urnas-seguranca', 'news_article', 1, 'TSE', 'Cerimônia', 'carmen-urnas-seguranca-b129-47') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 48
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_zan, 'Zanin defende voto secreto em julgamentos de réus do 8 de janeiro por segurança.', 'A proteção dos julgadores é essencial em julgamentos de alto risco.', 'Proposta em sessão administrativa do STF.', 'verified', false, '2024-12-18', 'https://www.conjur.com.br/2024-dez-18/zanin-voto-secreto-juizes/', 'news_article', 1, 'STF', 'Sessão administrativa', 'zanin-voto-secreto-b129-48') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 49
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nik, 'Nikolas ataca Zanin e diz que STF quer esconder o voto dos ministros.', 'Querem esconder o voto. O povo tem direito de saber quem decide.', 'Postagem em redes sociais criticando proposta de Zanin.', 'verified', true, '2024-12-19', 'https://www.metropoles.com/brasil/politica-br/nikolas-zanin-voto-secreto', 'social_media_post', 3, 'Brasília', 'Postagem em rede social', 'nikolas-zanin-voto-secreto-b129-49') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 50
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_bou, 'Guilherme Boulos defende investigações do STF e diz que sem STF já teria havido golpe.', 'Sem o STF firme, o golpe de 8 de janeiro teria prosperado.', 'Entrevista em programa de televisão.', 'verified', false, '2024-12-20', 'https://www.cnnbrasil.com.br/politica/boulos-stf-8-janeiro-golpe/', 'news_article', 1, 'São Paulo', 'Programa de TV', 'boulos-stf-evitou-golpe-b129-50') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 51
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moraes destaca papel do STF no combate à desinformação em 2024.', 'O STF cumpriu seu papel histórico em 2024. A democracia se fortaleceu.', 'Discurso de encerramento do ano judiciário do STF.', 'verified', true, '2024-12-19', 'https://g1.globo.com/politica/noticia/2024/12/19/moraes-balanco-stf-2024.ghtml', 'news_article', 2, 'STF', 'Encerramento judiciário', 'moraes-balanco-2024-b129-51') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 52
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_bar, 'Barroso encerra presidência do STF defendendo legado de firmeza democrática.', 'Deixamos um STF que respondeu à altura à crise democrática.', 'Discurso de encerramento da presidência do STF.', 'verified', true, '2024-09-28', 'https://www.stf.jus.br/portal/cms/verNoticiaDetalhe.asp?barroso-encerramento', 'news_article', 2, 'STF', 'Transmissão de cargo', 'barroso-encerramento-b129-52') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 53
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fac, 'Fachin assume presidência do STF e promete diálogo institucional.', 'A Corte dialogará com os demais Poderes com serenidade e firmeza.', 'Discurso de posse como presidente do STF.', 'verified', true, '2024-09-28', 'https://www.conjur.com.br/2024-set-28/fachin-posse-presidente-stf/', 'news_article', 2, 'STF', 'Posse na presidência', 'fachin-posse-presidencia-b129-53') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 54
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fac, 'Fachin como presidente do STF rejeita pressões externas à Corte.', 'Nenhuma pressão externa, nacional ou internacional, modificará a atuação do Supremo.', 'Primeira coletiva como presidente do STF.', 'verified', true, '2024-10-02', 'https://www1.folha.uol.com.br/poder/2024/10/fachin-presidente-stf-pressoes.shtml', 'news_article', 2, 'STF', 'Coletiva de imprensa', 'fachin-pressoes-externas-b129-54') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 55
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro pede sanções Magnitsky contra Fachin e Moraes.', 'Fachin e Moraes devem ser sancionados pela lei Magnitsky.', 'Entrevista a programa conservador nos EUA.', 'verified', true, '2024-10-04', 'https://www.politico.com/news/2024/10/04/eduardo-bolsonaro-magnitsky-fachin-moraes', 'news_article', 5, 'Washington, EUA', 'Entrevista à imprensa americana', 'eduardo-magnitsky-fachin-b129-55') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 56
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro ataca prisão de militares e diz que STF persegue as Forças Armadas.', 'O STF está perseguindo as Forças Armadas. É inaceitável.', 'Live semanal sobre prisões de militares do 8 de janeiro.', 'verified', true, '2024-12-16', 'https://www.poder360.com.br/congresso/bolsonaro-forcas-armadas-stf/', 'social_media_post', 4, 'Brasília', 'Live em rede social', 'bolsonaro-stf-forcas-armadas-b129-56') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 57
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moraes determina prisão preventiva de Filipe Martins em ação do golpe.', 'A prisão é medida cautelar necessária diante dos fortes indícios.', 'Decisão monocrática em inquérito do golpe de 8 de janeiro.', 'verified', true, '2024-02-08', 'https://g1.globo.com/politica/noticia/2024/02/08/moraes-prisao-filipe-martins.ghtml', 'news_article', 3, 'STF', 'Decisão monocrática', 'moraes-prisao-filipe-martins-b129-57') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;
  -- 58
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro diz que prisão de Filipe Martins é arbitrária e sem provas.', 'É uma prisão arbitrária. Querem atingir o meu entorno para me incriminar.', 'Coletiva à imprensa após prisão de assessor.', 'verified', true, '2024-02-09', 'https://www.cnnbrasil.com.br/politica/bolsonaro-prisao-filipe-martins/', 'news_article', 4, 'Brasília', 'Coletiva de imprensa', 'bolsonaro-prisao-filipe-b129-58') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 59
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_dav, 'Davi Alcolumbre afirma que Senado avaliará indicação ao STF com rigor.', 'Vamos analisar com rigor todas as indicações ao STF.', 'Entrevista como presidente do Senado sobre indicações.', 'verified', false, '2025-01-15', 'https://www12.senado.leg.br/noticias/materias/2025/01/15/alcolumbre-indicacoes-stf', 'news_article', 1, 'Senado Federal', 'Entrevista à imprensa', 'alcolumbre-rigor-indicacoes-b129-59') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 60
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula indica Jorge Messias para o STF em substituição a Barroso.', 'Jorge Messias é jurista de qualidade e comprometido com a democracia.', 'Anúncio oficial da indicação ao STF no Planalto.', 'verified', true, '2025-02-20', 'https://g1.globo.com/politica/noticia/2025/02/20/lula-indica-messias-stf.ghtml', 'news_article', 2, 'Brasília', 'Anúncio oficial', 'lula-indica-messias-b129-60') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 61
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_rog, 'Rogério Marinho diz que Messias será obstruído no Senado.', 'Messias não terá vida fácil no Senado. Há resistência forte.', 'Entrevista no Senado sobre indicação de Messias.', 'verified', false, '2025-02-22', 'https://www12.senado.leg.br/noticias/rogerio-marinho-obstrucao-messias', 'news_article', 2, 'Senado Federal', 'Entrevista', 'rogerio-obstrucao-messias-b129-61') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 62
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moraes determina desbloqueio do X após plataforma cumprir ordens judiciais.', 'A plataforma cumpriu as decisões. Determino o imediato retorno da prestação dos serviços.', 'Decisão monocrática determinando retomada do funcionamento do X no Brasil.', 'verified', true, '2024-10-08', 'https://www1.folha.uol.com.br/poder/2024/10/moraes-desbloqueia-x.shtml', 'news_article', 2, 'STF', 'Decisão monocrática', 'moraes-desbloqueia-x-b129-62') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 63
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro comemora desbloqueio do X e diz que foi vitória internacional.', 'A pressão internacional funcionou. O X está de volta.', 'Postagem celebrando desbloqueio do X no Brasil.', 'verified', false, '2024-10-09', 'https://www.metropoles.com/brasil/politica-br/eduardo-desbloqueio-x-vitoria', 'social_media_post', 3, 'Brasília', 'Postagem em rede social', 'eduardo-desbloqueio-x-b129-63') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 64
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_gil, 'Gilmar Mendes critica PEC contra monocráticas e diz que limitar STF fragiliza democracia.', 'Limitar o STF em nome de vingança política é caminho perigoso.', 'Entrevista em programa jurídico sobre PEC das monocráticas.', 'verified', false, '2025-01-25', 'https://www.conjur.com.br/2025-jan-25/gilmar-pec-monocraticas/', 'news_article', 1, 'Brasília', 'Entrevista à imprensa', 'gilmar-pec-monocraticas-b129-64') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 65
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fux, 'Fux manifesta-se a favor de limitação a decisões monocráticas no STF.', 'Precisamos revisar o uso excessivo de monocráticas. A colegialidade é essencial.', 'Palestra em evento jurídico sobre funcionamento da Corte.', 'verified', false, '2025-02-03', 'https://www.jota.info/stf/do-supremo/fux-monocraticas-colegialidade', 'news_article', 1, 'Rio de Janeiro', 'Seminário jurídico', 'fux-limite-monocraticas-b129-65') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 66
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_tof, 'Toffoli arquiva ação contra banqueiros da Lava Jato e gera críticas.', 'As provas obtidas foram viciadas, determino o arquivamento.', 'Decisão monocrática arquivando ações contra banqueiros.', 'verified', false, '2025-02-10', 'https://www1.folha.uol.com.br/mercado/2025/02/toffoli-arquiva-banqueiros-lavajato.shtml', 'news_article', 2, 'STF', 'Decisão monocrática', 'toffoli-arquiva-banqueiros-b129-66') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 67
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moraes recebe general Heleno para interrogatório em inquérito do golpe.', 'O interrogatório é etapa essencial do devido processo legal.', 'Nota do STF sobre interrogatório de general em inquérito do golpe.', 'verified', true, '2025-02-15', 'https://g1.globo.com/politica/noticia/2025/02/15/moraes-heleno-interrogatorio.ghtml', 'news_article', 2, 'STF', 'Interrogatório', 'moraes-heleno-interrogatorio-b129-67') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 68
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro chama interrogatórios de humilhação política dos militares.', 'Humilham nossos generais. Isso é vingança, não justiça.', 'Live comentando interrogatórios de generais no STF.', 'verified', true, '2025-02-16', 'https://www.cnnbrasil.com.br/politica/bolsonaro-humilhacao-militares-stf/', 'social_media_post', 4, 'Brasília', 'Live em rede social', 'bolsonaro-humilhacao-militares-b129-68') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 69
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_car, 'Cármen Lúcia rebate politização do STF e defende atuação da Corte.', 'O STF não é político. Cumpre a Constituição.', 'Palestra na OAB Nacional sobre autonomia do Judiciário.', 'verified', false, '2025-02-20', 'https://www.conjur.com.br/2025-fev-20/carmen-politizacao-stf/', 'news_article', 1, 'Brasília', 'Evento OAB', 'carmen-politizacao-stf-b129-69') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 70
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nik, 'Nikolas Ferreira pede boicote às sessões do STF e enfrentamento direto.', 'É hora de enfrentar o STF. Chega de covardia na Câmara.', 'Discurso no plenário da Câmara convocando enfrentamento.', 'verified', true, '2025-02-25', 'https://www.camara.leg.br/noticias/1095998-nikolas-boicote-stf', 'news_article', 5, 'Câmara dos Deputados', 'Sessão plenária', 'nikolas-boicote-stf-b129-70') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 71
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_hug, 'Hugo Motta nega que Câmara esteja em rota de colisão com STF.', 'Não há rota de colisão. Há divergência institucional saudável.', 'Entrevista como presidente da Câmara sobre relações com STF.', 'verified', false, '2025-03-01', 'https://www.poder360.com.br/congresso/hugo-motta-rota-colisao-stf/', 'news_article', 1, 'Brasília', 'Entrevista', 'hugo-sem-rota-colisao-b129-71') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 72
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_dav, 'Davi Alcolumbre defende Senado como equilibrador entre Executivo e Judiciário.', 'Senado é o fiel da balança entre os Poderes.', 'Discurso em sessão solene do Senado.', 'verified', false, '2025-03-05', 'https://www12.senado.leg.br/noticias/davi-senado-equilibrio-poderes', 'news_article', 1, 'Senado Federal', 'Sessão solene', 'alcolumbre-equilibrio-senado-b129-72') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 73
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_pac, 'Rodrigo Pacheco defende indicação técnica ao STF.', 'A indicação ao STF deve ser técnica, não política.', 'Entrevista como senador sobre indicação de Messias.', 'verified', false, '2025-03-08', 'https://www12.senado.leg.br/noticias/pacheco-indicacao-tecnica', 'news_article', 1, 'Senado Federal', 'Entrevista', 'pacheco-indicacao-tecnica-b129-73') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 74
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jom, 'Jorge Messias passa por sabatina no Senado e defende ativismo moderado.', 'Não sou ativista. Respeitarei o texto da Constituição.', 'Sabatina na CCJ do Senado sobre indicação ao STF.', 'verified', true, '2025-03-15', 'https://www12.senado.leg.br/noticias/messias-sabatina-ccj', 'news_article', 2, 'Senado Federal', 'Sabatina CCJ', 'messias-sabatina-ccj-b129-74') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 75
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fla, 'Flávio Bolsonaro vota contra Messias e critica indicação política.', 'É uma indicação ideológica. Votarei não.', 'Declaração em plenário do Senado sobre votação de Messias.', 'verified', true, '2025-03-20', 'https://www12.senado.leg.br/noticias/flavio-bolsonaro-contra-messias', 'news_article', 2, 'Senado Federal', 'Sessão plenária', 'flavio-contra-messias-b129-75') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 76
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_bar, 'Barroso deixa o STF e defende legado em discurso emocionado.', 'Deixo o STF com a consciência tranquila. Fizemos o que era necessário.', 'Cerimônia de aposentadoria de Barroso no STF.', 'verified', true, '2025-04-15', 'https://g1.globo.com/politica/noticia/2025/04/15/barroso-aposentadoria-stf.ghtml', 'news_article', 2, 'STF', 'Cerimônia', 'barroso-aposentadoria-b129-76') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 77
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moraes determina busca e apreensão em operação contra milícias digitais.', 'A operação é resultado de dois anos de investigação contra disseminadores de mentiras.', 'Decisão monocrática autorizando operação da PF contra milícias digitais.', 'verified', true, '2025-03-25', 'https://www.cnnbrasil.com.br/politica/moraes-operacao-milicias-digitais-2025/', 'news_article', 3, 'STF', 'Decisão monocrática', 'moraes-operacao-milicias-b129-77') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;
  -- 78
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nik, 'Nikolas acusa STF de perseguição política em operações da PF.', 'É perseguição política. Operações com alvo claro em conservadores.', 'Postagem em redes sociais após operação da PF.', 'verified', true, '2025-03-26', 'https://www.metropoles.com/brasil/politica-br/nikolas-perseguicao-operacoes', 'social_media_post', 4, 'Brasília', 'Postagem em rede social', 'nikolas-perseguicao-operacoes-b129-78') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 79
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_bia, 'Bia Kicis protocola PL que tipifica abuso de autoridade contra ministros do STF.', 'Ministros não podem se achar intocáveis. PL tipifica abuso de autoridade.', 'Coletiva sobre protocolo de PL contra ministros do STF.', 'verified', true, '2025-03-30', 'https://www.camara.leg.br/noticias/1097221-bia-kicis-pl-abuso-autoridade-stf', 'news_article', 4, 'Câmara dos Deputados', 'Coletiva de imprensa', 'bia-kicis-pl-abuso-b129-79') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 80
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_ran, 'Randolfe alerta para escalada de ataques institucionais contra STF.', 'Há escalada de ataques. Precisamos reagir como sociedade.', 'Entrevista sobre ambiente político e ataques ao STF.', 'verified', false, '2025-04-02', 'https://www.poder360.com.br/governo/randolfe-escalada-ataques-stf/', 'news_article', 1, 'Brasília', 'Entrevista', 'randolfe-escalada-ataques-b129-80') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 81
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lin, 'Lindbergh Farias defende impeachment de ministros golpistas se for o caso.', 'Se houver golpismo em qualquer Poder, inclusive no STF, tem que haver impeachment.', 'Declaração polêmica em entrevista sobre ministros do STF.', 'verified', false, '2025-04-05', 'https://www1.folha.uol.com.br/poder/2025/04/lindbergh-impeachment-ministros.shtml', 'news_article', 2, 'Brasília', 'Entrevista', 'lindbergh-impeachment-ministros-b129-81') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 82
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moraes manda desbloquear contas de Bolsonaro por decisão em habeas corpus.', 'O desbloqueio é consequência do cumprimento das medidas cautelares.', 'Decisão em pedido de defesa sobre bloqueios de contas.', 'verified', false, '2025-04-08', 'https://www.jota.info/stf/do-supremo/moraes-desbloqueia-contas-bolsonaro', 'news_article', 1, 'STF', 'Decisão', 'moraes-desbloqueia-contas-b129-82') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 83
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro diz que continuará enfrentando Moraes apesar de decisões favoráveis.', 'Mesmo com decisões pontuais, continuarei enfrentando a tirania.', 'Coletiva após decisão de Moraes.', 'verified', true, '2025-04-10', 'https://www.cnnbrasil.com.br/politica/bolsonaro-moraes-enfrentamento/', 'news_article', 4, 'Brasília', 'Coletiva de imprensa', 'bolsonaro-moraes-enfrentar-b129-83') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 84
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_hum, 'Humberto Costa defende STF e lembra papel no 8 de janeiro.', 'Sem o STF firme em 8 de janeiro, seria pior.', 'Discurso no plenário do Senado.', 'verified', false, '2025-04-12', 'https://www12.senado.leg.br/noticias/humberto-stf-8-janeiro', 'news_article', 1, 'Senado Federal', 'Sessão plenária', 'humberto-stf-8-janeiro-b129-84') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 85
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jaw, 'Jaques Wagner articula defesa de indicações do governo ao STF.', 'Vamos garantir as indicações do presidente com diálogo no Senado.', 'Entrevista como líder do governo no Senado.', 'verified', false, '2025-04-14', 'https://www12.senado.leg.br/noticias/jaques-indicacoes-stf', 'news_article', 1, 'Senado Federal', 'Entrevista', 'jaques-indicacoes-stf-b129-85') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 86
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fac, 'Fachin reafirma independência da Corte em pronunciamento.', 'A independência do STF não é negociável em nenhuma circunstância.', 'Pronunciamento como presidente do STF em sessão solene.', 'verified', true, '2025-03-10', 'https://www.stf.jus.br/portal/cms/verNoticiaDetalhe.asp?fachin-independencia', 'news_article', 2, 'STF', 'Sessão solene', 'fachin-independencia-corte-b129-86') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 87
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_din, 'Flávio Dino vota em caso do marco temporal e defende direitos indígenas.', 'O marco temporal não pode apagar direitos históricos das populações originárias.', 'Voto em julgamento sobre marco temporal indígena.', 'verified', false, '2025-02-28', 'https://www.conjur.com.br/2025-fev-28/dino-marco-temporal-indigenas/', 'news_article', 1, 'STF', 'Sessão do Plenário', 'dino-marco-temporal-indigenas-b129-87') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 88
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mend, 'André Mendonça vota pela prescrição em ações contra bolsonaristas.', 'Há casos em que a prescrição opera inevitavelmente em favor do réu.', 'Voto em recurso sobre prescrição em ação penal do 8 de janeiro.', 'verified', false, '2025-03-12', 'https://www.jota.info/stf/do-supremo/mendonca-prescricao-bolsonaristas', 'news_article', 1, 'STF', 'Sessão', 'mendonca-prescricao-b129-88') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 89
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_zan, 'Zanin defende maior transparência em pautas do STF após críticas públicas.', 'A transparência fortalece a legitimidade da Corte.', 'Discurso em evento sobre direito digital no IDP.', 'verified', false, '2025-03-18', 'https://www.conjur.com.br/2025-mar-18/zanin-transparencia-stf/', 'news_article', 1, 'IDP', 'Seminário', 'zanin-transparencia-stf-b129-89') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 90
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nun, 'Nunes Marques critica morosidade em casos do 8 de janeiro.', 'Precisamos acelerar julgamentos e evitar detenções prolongadas sem decisão.', 'Voto em questão de ordem sobre celeridade em casos do 8 de janeiro.', 'verified', false, '2025-03-20', 'https://www.poder360.com.br/justica/nunes-marques-8-janeiro-morosidade/', 'news_article', 1, 'STF', 'Sessão', 'nunes-morosidade-b129-90') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 91
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mfe, 'Marco Feliciano defende PEC da blindagem parlamentar contra STF.', 'PEC da blindagem é o mínimo para conter abusos do STF.', 'Discurso na Câmara sobre PEC da blindagem.', 'verified', true, '2025-04-01', 'https://www.camara.leg.br/noticias/1098221-feliciano-pec-blindagem', 'news_article', 4, 'Câmara dos Deputados', 'Sessão plenária', 'feliciano-pec-blindagem-b129-91') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 92
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mvh, 'Marcel van Hattem defende medidas duras contra o STF na Câmara.', 'O Congresso tem que ser firme. O STF exagerou.', 'Discurso na Câmara em defesa de medidas contra o STF.', 'verified', false, '2025-04-03', 'https://www.camara.leg.br/noticias/1098311-marcel-medidas-stf', 'news_article', 3, 'Câmara dos Deputados', 'Sessão plenária', 'marcel-medidas-stf-b129-92') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 93
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_bou, 'Boulos critica PEC da blindagem como salvo-conduto a criminosos.', 'PEC da blindagem é salvo-conduto para criminosos de colarinho branco.', 'Discurso na Câmara contra PEC da blindagem.', 'verified', false, '2025-04-04', 'https://www.camara.leg.br/noticias/1098345-boulos-pec-blindagem-salvo-conduto', 'news_article', 1, 'Câmara dos Deputados', 'Sessão plenária', 'boulos-pec-salvo-conduto-b129-93') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 94
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_eri, 'Erika Hilton critica PEC da blindagem e denuncia retrocesso.', 'A PEC da blindagem é retrocesso institucional gravíssimo.', 'Discurso na Câmara contra a PEC.', 'verified', false, '2025-04-05', 'https://www.camara.leg.br/noticias/1098411-erika-pec-blindagem', 'news_article', 1, 'Câmara dos Deputados', 'Sessão plenária', 'erika-pec-blindagem-b129-94') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 95
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_sam, 'Sâmia Bomfim denuncia PEC da blindagem como proteção a golpistas.', 'Não vamos aceitar proteção a golpistas no Congresso.', 'Discurso na Câmara.', 'verified', false, '2025-04-06', 'https://www.camara.leg.br/noticias/1098465-samia-blindagem-golpistas', 'news_article', 1, 'Câmara dos Deputados', 'Sessão plenária', 'samia-blindagem-golpistas-b129-95') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 96
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_tal, 'Talíria Petrone denuncia escalada autoritária no Congresso.', 'Há escalada autoritária no Congresso que precisa ser barrada.', 'Pronunciamento na Câmara em defesa do STF.', 'verified', false, '2025-04-07', 'https://www.camara.leg.br/noticias/1098511-taliria-escalada-autoritaria', 'news_article', 1, 'Câmara dos Deputados', 'Sessão plenária', 'taliria-escalada-autoritaria-b129-96') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 97
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moraes defende legitimidade democrática de decisões do STF em palestra.', 'O STF cumpre a Constituição. Essa é a fonte de nossa legitimidade.', 'Palestra na USP sobre democracia e Judiciário.', 'verified', true, '2025-04-11', 'https://www.conjur.com.br/2025-abr-11/moraes-usp-legitimidade/', 'news_article', 2, 'USP', 'Palestra', 'moraes-usp-legitimidade-b129-97') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 98
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jom, 'Jorge Messias é aprovado no Senado como novo ministro do STF.', 'Honra imensa. Dedicarei minha atuação à Constituição.', 'Declaração após aprovação pelo plenário do Senado.', 'verified', true, '2025-04-14', 'https://www12.senado.leg.br/noticias/messias-aprovado-stf', 'news_article', 2, 'Senado Federal', 'Plenário', 'messias-aprovado-stf-b129-98') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 99
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula celebra aprovação de Messias e diz que STF permanecerá forte.', 'O STF permanecerá forte e com ministros comprometidos com a Constituição.', 'Pronunciamento no Planalto após aprovação de Messias.', 'verified', true, '2025-04-15', 'https://g1.globo.com/politica/noticia/2025/04/15/lula-messias-stf.ghtml', 'news_article', 1, 'Brasília', 'Pronunciamento', 'lula-messias-aprovacao-b129-99') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 100
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_had, 'Haddad diz que estabilidade do STF é essencial para previsibilidade econômica.', 'Sem estabilidade institucional, não há previsibilidade para investir.', 'Entrevista a jornal econômico sobre STF e mercados.', 'verified', false, '2025-04-10', 'https://valor.globo.com/brasil/noticia/2025/04/10/haddad-stf-estabilidade.ghtml', 'news_article', 1, 'Brasília', 'Entrevista', 'haddad-stf-previsibilidade-b129-100') RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
END $$;
