-- Batch 131: Impacto segundo mandato Trump no Brasil - Parte 2 (Ago 2025 - Abr 2026)
DO $$
DECLARE
  v_lul UUID; v_mau UUID; v_alc UUID; v_had UUID; v_edu UUID;
  v_fla UUID; v_jai UUID; v_car UUID; v_nik UUID; v_bia UUID;
  v_mvh UUID; v_pab UUID; v_tar UUID; v_cai UUID; v_zem UUID;
  v_mor UUID; v_cir UUID; v_gle UUID; v_ran UUID; v_teb UUID;
  v_msi UUID; v_fav UUID; v_muc UUID; v_pad UUID; v_ruc UUID;
  v_mes UUID; v_lew UUID; v_amo UUID; v_din UUID; v_gil UUID;
  v_hum UUID; v_hmo UUID; v_dav UUID; v_rom UUID; v_mpo UUID;
  v_sor UUID; v_mic UUID; v_rog UUID; v_jom UUID; v_bou UUID; v_lin UUID;
  v_pac UUID; v_bar UUID; v_fux UUID; v_fac UUID; v_car2 UUID; v_hug UUID;
  c_ant UUID; c_des UUID; c_xen UUID; c_irr UUID; c_abu UUID;
  c_aut UUID; c_ame UUID; c_odi UUID; c_con UUID; c_int UUID;
  c_obs UUID;
BEGIN
  SELECT id INTO v_lul FROM politicians WHERE slug = 'lula';
  SELECT id INTO v_mau FROM politicians WHERE slug = 'mauro-vieira';
  SELECT id INTO v_alc FROM politicians WHERE slug = 'geraldo-alckmin';
  SELECT id INTO v_had FROM politicians WHERE slug = 'fernando-haddad';
  SELECT id INTO v_edu FROM politicians WHERE slug = 'eduardo-bolsonaro';
  SELECT id INTO v_fla FROM politicians WHERE slug = 'flavio-bolsonaro';
  SELECT id INTO v_jai FROM politicians WHERE slug = 'jair-bolsonaro';
  SELECT id INTO v_car FROM politicians WHERE slug = 'carlos-bolsonaro';
  SELECT id INTO v_nik FROM politicians WHERE slug = 'nikolas-ferreira';
  SELECT id INTO v_bia FROM politicians WHERE slug = 'bia-kicis';
  SELECT id INTO v_mvh FROM politicians WHERE slug = 'marcel-van-hattem';
  SELECT id INTO v_pab FROM politicians WHERE slug = 'pablo-marcal';
  SELECT id INTO v_tar FROM politicians WHERE slug = 'tarcisio-de-freitas';
  SELECT id INTO v_cai FROM politicians WHERE slug = 'ronaldo-caiado';
  SELECT id INTO v_zem FROM politicians WHERE slug = 'zema';
  SELECT id INTO v_mor FROM politicians WHERE slug = 'sergio-moro';
  SELECT id INTO v_cir FROM politicians WHERE slug = 'ciro-gomes';
  SELECT id INTO v_gle FROM politicians WHERE slug = 'gleisi-hoffmann';
  SELECT id INTO v_ran FROM politicians WHERE slug = 'randolfe-rodrigues';
  SELECT id INTO v_teb FROM politicians WHERE slug = 'simone-tebet';
  SELECT id INTO v_msi FROM politicians WHERE slug = 'marina-silva';
  SELECT id INTO v_fav FROM politicians WHERE slug = 'carlos-favaro';
  SELECT id INTO v_muc FROM politicians WHERE slug = 'jose-mucio';
  SELECT id INTO v_pad FROM politicians WHERE slug = 'alexandre-padilha';
  SELECT id INTO v_ruc FROM politicians WHERE slug = 'rui-costa';
  SELECT id INTO v_lew FROM politicians WHERE slug = 'ricardo-lewandowski';
  SELECT id INTO v_amo FROM politicians WHERE slug = 'alexandre-de-moraes';
  SELECT id INTO v_din FROM politicians WHERE slug = 'flavio-dino';
  SELECT id INTO v_gil FROM politicians WHERE slug = 'gilmar-mendes';
  SELECT id INTO v_hum FROM politicians WHERE slug = 'humberto-costa';
  SELECT id INTO v_dav FROM politicians WHERE slug = 'davi-alcolumbre';
  SELECT id INTO v_mic FROM politicians WHERE slug = 'michelle-bolsonaro';
  SELECT id INTO v_jom FROM politicians WHERE slug = 'jorge-messias';
  SELECT id INTO v_bou FROM politicians WHERE slug = 'guilherme-boulos';
  SELECT id INTO v_lin FROM politicians WHERE slug = 'lindbergh-farias';
  SELECT id INTO v_pac FROM politicians WHERE slug = 'rodrigo-pacheco';
  SELECT id INTO v_bar FROM politicians WHERE slug = 'luis-roberto-barroso';
  SELECT id INTO v_fux FROM politicians WHERE slug = 'luiz-fux';
  SELECT id INTO v_fac FROM politicians WHERE slug = 'edson-fachin';
  SELECT id INTO v_car2 FROM politicians WHERE slug = 'carmen-lucia';
  SELECT id INTO v_hug FROM politicians WHERE slug = 'hugo-motta';
  SELECT id INTO v_rog FROM politicians WHERE slug = 'rogerio-marinho';

  SELECT id INTO c_ant FROM categories WHERE slug = 'antidemocratico';
  SELECT id INTO c_des FROM categories WHERE slug = 'desinformacao';
  SELECT id INTO c_xen FROM categories WHERE slug = 'xenofobia';
  SELECT id INTO c_irr FROM categories WHERE slug = 'irresponsabilidade';
  SELECT id INTO c_abu FROM categories WHERE slug = 'abuso-de-poder';
  SELECT id INTO c_aut FROM categories WHERE slug = 'autoritarismo';
  SELECT id INTO c_ame FROM categories WHERE slug = 'ameaca-instituicoes';
  SELECT id INTO c_odi FROM categories WHERE slug = 'discurso-de-odio';
  SELECT id INTO c_con FROM categories WHERE slug = 'conflito-interesses';
  SELECT id INTO c_int FROM categories WHERE slug = 'intimidacao';
  SELECT id INTO c_obs FROM categories WHERE slug = 'obstrucao-justica';

  -- 1
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro se reúne com Rick Scott no Capitólio para sanções Magnitsky contra Moraes.', 'Pedi ao senador Scott que lidere a pressão por sanções Magnitsky contra Alexandre de Moraes.', 'Reunião no Capitólio americano reportada pela imprensa internacional.', 'verified', true, '2025-08-05', 'https://www.politico.com/news/2025/08/05/eduardo-bolsonaro-rick-scott-magnitsky-moraes', 'news_article', 5, 'Washington, EUA', 'Reunião no Capitólio', 'eduardo-scott-magnitsky-b131-1') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 2
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fla, 'Flávio Bolsonaro celebra projeto de lei de Rubio que prevê sanções a juízes estrangeiros.', 'A lei Rubio é ferramenta importante contra juízes que perseguem conservadores.', 'Entrevista a rede conservadora em Washington.', 'verified', true, '2025-08-10', 'https://www.cnnbrasil.com.br/politica/flavio-lei-rubio-sancoes/', 'news_article', 5, 'Washington, EUA', 'Entrevista', 'flavio-lei-rubio-sancoes-b131-2') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 3
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula denuncia interferência americana em assuntos internos brasileiros.', 'Não aceitaremos que outro país dite a atuação do nosso Judiciário.', 'Pronunciamento em reunião do G20 sobre soberania.', 'verified', true, '2025-08-12', 'https://www.reuters.com/world/americas/lula-denuncia-interferencia-eua-brasil/', 'news_article', 2, 'Joanesburgo', 'G20', 'lula-interferencia-eua-b131-3') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 4
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mau, 'Mauro Vieira convoca embaixador dos EUA após ameaças contra o STF.', 'Convoquei o embaixador para explicar declarações inaceitáveis de autoridades americanas.', 'Nota do Itamaraty sobre convocação do embaixador dos EUA.', 'verified', true, '2025-08-14', 'https://www1.folha.uol.com.br/mundo/2025/08/mauro-vieira-convoca-embaixador-eua.shtml', 'news_article', 2, 'Brasília', 'Itamaraty', 'mauro-convoca-embaixador-b131-4') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 5
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_amo, 'Moraes reage a pressões de Trump e diz que STF não se intimida.', 'Nenhuma pressão estrangeira mudará as decisões do Supremo.', 'Discurso em sessão do STF sobre soberania judicial.', 'verified', true, '2025-08-18', 'https://g1.globo.com/politica/noticia/2025/08/18/moraes-pressao-trump-stf.ghtml', 'news_article', 3, 'STF', 'Sessão', 'moraes-pressao-trump-b131-5') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 6
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro elogia Trump e pede que Brasil siga o modelo MAGA.', 'Trump mostrou o caminho. O Brasil precisa seguir com um MAGA brasileiro.', 'Live comentando medidas de Trump na economia e imigração.', 'verified', true, '2025-08-20', 'https://www.metropoles.com/brasil/politica-br/bolsonaro-maga-brasileiro', 'social_media_post', 4, 'Brasília', 'Live em rede social', 'bolsonaro-maga-brasileiro-b131-6') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_aut, true FROM ins;
  -- 7
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_tar, 'Tarcísio diz que aproximação com governo Trump trará investimentos.', 'Vejo oportunidade com Trump para atrair investimentos em energia.', 'Entrevista em evento empresarial em Nova York.', 'verified', false, '2025-08-25', 'https://valor.globo.com/brasil/noticia/2025/08/25/tarcisio-trump-investimentos.ghtml', 'news_article', 2, 'Nova York', 'Evento empresarial', 'tarcisio-trump-investimentos-b131-7') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 8
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_zem, 'Zema anuncia viagem aos EUA para reuniões com republicanos.', 'Vou aos EUA encontrar governadores e senadores republicanos afinados com nossas pautas.', 'Anúncio de viagem oficial do governador de MG.', 'verified', false, '2025-08-28', 'https://www.cnnbrasil.com.br/politica/zema-eua-republicanos/', 'news_article', 3, 'Belo Horizonte', 'Coletiva de imprensa', 'zema-eua-republicanos-b131-8') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_con, true FROM ins;
  -- 9
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro busca asilo preventivo nos EUA alegando perseguição.', 'Estou em consultas para proteger minha liberdade diante da perseguição do STF.', 'Entrevista à imprensa americana sobre status migratório.', 'verified', true, '2025-09-03', 'https://www.washingtonpost.com/world/2025/09/03/eduardo-bolsonaro-asilo-eua/', 'news_article', 5, 'Washington, EUA', 'Entrevista', 'eduardo-asilo-eua-b131-9') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_obs, true FROM ins;
  -- 10
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_din, 'Flávio Dino critica lobby de brasileiros por sanções dos EUA ao Brasil.', 'É traição agir no exterior contra o próprio país.', 'Entrevista como ministro do STF sobre pressões externas.', 'verified', false, '2025-09-05', 'https://www.poder360.com.br/justica/dino-lobby-traicao/', 'news_article', 2, 'Brasília', 'Entrevista', 'dino-lobby-traicao-b131-10') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 11
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_amo, 'Moraes cita lei americana de sanções e diz que retaliação é absurda.', 'Pedir sanções contra juízes brasileiros é afronta à soberania nacional.', 'Voto em sessão administrativa sobre medidas contra brasileiros no exterior.', 'verified', true, '2025-09-08', 'https://g1.globo.com/politica/noticia/2025/09/08/moraes-sancoes-absurdo.ghtml', 'news_article', 3, 'STF', 'Sessão', 'moraes-sancoes-absurdo-b131-11') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 12
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_had, 'Haddad rejeita ameaças de Trump a crédito multilateral ao Brasil.', 'Não aceitaremos chantagem com organismos multilaterais.', 'Entrevista em Washington durante reunião do FMI.', 'verified', false, '2025-09-10', 'https://valor.globo.com/brasil/noticia/2025/09/10/haddad-trump-fmi.ghtml', 'news_article', 2, 'Washington', 'Reunião FMI', 'haddad-trump-fmi-b131-12') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 13
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nik, 'Nikolas Ferreira defende aproximação total com Trump e ruptura com BRICS.', 'Precisamos sair do BRICS e nos alinhar totalmente com os EUA.', 'Discurso em plenário da Câmara.', 'verified', true, '2025-09-12', 'https://www.camara.leg.br/noticias/1101221-nikolas-brics-trump', 'news_article', 3, 'Câmara dos Deputados', 'Sessão plenária', 'nikolas-brics-trump-b131-13') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 14
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula reafirma aliança com BRICS em resposta a Trump.', 'O BRICS é a aposta do sul global. Não sairemos.', 'Discurso em cúpula do BRICS.', 'verified', true, '2025-09-15', 'https://www.reuters.com/world/americas/lula-brics-trump-cupula/', 'news_article', 2, 'Rio de Janeiro', 'Cúpula BRICS', 'lula-brics-cupula-b131-14') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 15
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_bia, 'Bia Kicis participa de evento trumpista em Dallas e discursa.', 'O Brasil precisa do trumpismo para se libertar do comunismo.', 'Discurso em evento conservador em Dallas.', 'verified', true, '2025-09-20', 'https://www.metropoles.com/brasil/politica-br/bia-dallas-trumpismo', 'news_article', 4, 'Dallas, EUA', 'Evento conservador', 'bia-dallas-trumpismo-b131-15') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 16
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_muc, 'José Múcio defende soberania contra pressões do governo Trump.', 'As Forças Armadas defendem a soberania. Não se curvarão a pressões externas.', 'Entrevista como ministro da Defesa.', 'verified', false, '2025-09-22', 'https://g1.globo.com/politica/noticia/2025/09/22/mucio-forcas-armadas-trump.ghtml', 'news_article', 1, 'Brasília', 'Entrevista', 'mucio-soberania-trump-b131-16') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 17
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_pad, 'Alexandre Padilha denuncia interferência americana na política brasileira.', 'Há interferência direta de Washington na política brasileira. Isso é gravíssimo.', 'Entrevista como ministro articulação política.', 'verified', false, '2025-09-25', 'https://www.poder360.com.br/governo/padilha-interferencia-eua/', 'news_article', 2, 'Brasília', 'Entrevista', 'padilha-interferencia-eua-b131-17') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 18
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_cir, 'Ciro Gomes critica bolsonaristas que pedem sanções americanas.', 'Pedir sanções contra o próprio país é ato de traição inominável.', 'Entrevista televisiva em programa dominical.', 'verified', true, '2025-09-28', 'https://www.cnnbrasil.com.br/politica/ciro-gomes-traicao-sancoes/', 'news_article', 2, 'Rio de Janeiro', 'Programa de TV', 'ciro-traicao-sancoes-b131-18') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 19
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_gle, 'Gleisi Hoffmann anuncia projeto que tipifica lobby antinacional como crime.', 'Pedir sanções contra o próprio país deve ser crime tipificado.', 'Coletiva como líder do governo na Câmara.', 'verified', true, '2025-10-02', 'https://www.camara.leg.br/noticias/1102111-gleisi-lobby-antinacional', 'news_article', 2, 'Câmara dos Deputados', 'Coletiva', 'gleisi-lobby-antinacional-b131-19') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 20
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_ran, 'Randolfe Rodrigues denuncia atuação de parlamentares brasileiros em Washington.', 'Há parlamentares que trabalham contra o Brasil em Washington. Devem ser investigados.', 'Entrevista no Senado.', 'verified', false, '2025-10-05', 'https://www12.senado.leg.br/noticias/randolfe-parlamentares-washington', 'news_article', 2, 'Senado Federal', 'Entrevista', 'randolfe-parlamentares-washington-b131-20') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 21
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro se reúne com Elon Musk para tratar de redes no Brasil.', 'Elon Musk entende o que o STF faz com a liberdade de expressão no Brasil.', 'Reunião com Musk em Austin segundo reportagens.', 'verified', true, '2025-10-10', 'https://www.reuters.com/technology/eduardo-bolsonaro-musk-austin/', 'news_article', 5, 'Austin, EUA', 'Reunião com Musk', 'eduardo-musk-austin-b131-21') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 22
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_amo, 'Moraes declara que Elon Musk interfere na soberania brasileira.', 'Plataformas não podem ser braços de interferência política contra o Brasil.', 'Discurso em evento sobre regulação digital.', 'verified', true, '2025-10-12', 'https://www1.folha.uol.com.br/poder/2025/10/moraes-musk-soberania.shtml', 'news_article', 3, 'São Paulo', 'Evento', 'moraes-musk-soberania-b131-22') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 23
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nik, 'Nikolas Ferreira defende Musk e ataca STF por censura.', 'Musk é herói da liberdade. O STF quer calar até empresários estrangeiros.', 'Postagem em redes sociais após decisão contra Musk.', 'verified', true, '2025-10-14', 'https://www.metropoles.com/brasil/politica-br/nikolas-defende-musk', 'social_media_post', 3, 'Brasília', 'Postagem em rede social', 'nikolas-defende-musk-b131-23') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 24
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_car, 'Carlos Bolsonaro publica foto com Don Jr. em Mar-a-Lago.', 'Família Bolsonaro e família Trump unidas pela liberdade.', 'Postagem em rede social durante visita a Mar-a-Lago.', 'verified', false, '2025-10-18', 'https://www.cnnbrasil.com.br/politica/carlos-bolsonaro-mar-a-lago-don-jr/', 'social_media_post', 3, 'Palm Beach, EUA', 'Visita a Mar-a-Lago', 'carlos-mar-a-lago-donjr-b131-24') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_con, true FROM ins;
  -- 25
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula diz que não fará concessões a Trump sobre política externa.', 'Nenhum país vai mandar na nossa política externa.', 'Discurso em reunião de cúpula do Mercosul.', 'verified', true, '2025-10-22', 'https://www.reuters.com/world/americas/lula-trump-politica-externa/', 'news_article', 3, 'Montevidéu', 'Cúpula Mercosul', 'lula-concessoes-trump-b131-25') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 26
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mau, 'Mauro Vieira assina acordo com Argentina para política externa coordenada.', 'Mercosul precisa falar em coro contra pressões externas.', 'Assinatura de acordo em cúpula do Mercosul.', 'verified', false, '2025-10-22', 'https://www1.folha.uol.com.br/mundo/2025/10/mauro-vieira-mercosul.shtml', 'news_article', 1, 'Montevidéu', 'Cúpula Mercosul', 'mauro-mercosul-coordenado-b131-26') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 27
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_teb, 'Simone Tebet defende equilíbrio nas relações com os EUA.', 'Diálogo firme e respeitoso é o melhor caminho com os EUA.', 'Entrevista como ministra do Planejamento.', 'verified', false, '2025-10-25', 'https://valor.globo.com/brasil/noticia/2025/10/25/tebet-eua-equilibrio.ghtml', 'news_article', 1, 'Brasília', 'Entrevista', 'tebet-eua-equilibrio-b131-27') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 28
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_alc, 'Alckmin negocia redução de tarifas com representante comercial de Trump.', 'Vamos buscar redução de tarifas via diálogo direto.', 'Entrevista após reunião em Washington como vice-presidente.', 'verified', true, '2025-10-28', 'https://g1.globo.com/politica/noticia/2025/10/28/alckmin-tarifas-washington.ghtml', 'news_article', 1, 'Washington', 'Reunião comercial', 'alckmin-tarifas-washington-b131-28') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 29
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_msi, 'Marina Silva lidera COP30 em Belém com ausência dos EUA.', 'Os EUA perdem papel de liderança climática. Outros países ocupam o espaço.', 'Discurso na abertura da COP30 em Belém.', 'verified', true, '2025-11-10', 'https://www.reuters.com/environment/cop30-marina-silva-belem/', 'news_article', 2, 'Belém', 'COP30', 'marina-cop30-belem-b131-29') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 30
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fav, 'Carlos Fávaro pede diálogo com EUA no agronegócio diante de tarifas.', 'Agronegócio precisa de estabilidade. Vamos dialogar com firmeza.', 'Entrevista em feira agrícola.', 'verified', false, '2025-11-15', 'https://valor.globo.com/agronegocios/noticia/2025/11/15/favaro-eua-tarifas.ghtml', 'news_article', 1, 'Ribeirão Preto', 'Feira agrícola', 'favaro-eua-dialogo-b131-30') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 31
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro diz que prisão domiciliar é consequência da falta de apoio americano.', 'Se Trump tivesse pressionado mais, eu não estaria nessa situação.', 'Declaração em live com aliados.', 'verified', true, '2025-11-20', 'https://www.cnnbrasil.com.br/politica/bolsonaro-prisao-domiciliar-trump/', 'social_media_post', 4, 'Brasília', 'Live em rede social', 'bolsonaro-prisao-domiciliar-trump-b131-31') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 32
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro pede que Trump suspenda vistos de ministros do STF.', 'Trump pode cancelar os vistos. Esse é o caminho.', 'Entrevista em canal conservador americano.', 'verified', true, '2025-11-25', 'https://www.foxnews.com/world/eduardo-bolsonaro-trump-vistos-stf', 'news_article', 5, 'Washington', 'Entrevista à imprensa americana', 'eduardo-trump-vistos-stf-b131-32') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 33
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fla, 'Flávio Bolsonaro reforça pedido por sanções em audiência no Senado americano.', 'Senadores americanos precisam agir. A lei Magnitsky se aplica a Moraes.', 'Audiência em subcomitê do Senado americano.', 'verified', true, '2025-11-28', 'https://www.politico.com/news/2025/11/28/flavio-bolsonaro-senado-eua', 'news_article', 5, 'Washington', 'Senado americano', 'flavio-audiencia-senado-eua-b131-33') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 34
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_pac, 'Pacheco critica compatriotas que pedem sanções externas.', 'Quem pede sanção contra o Brasil não pode alegar amor à pátria.', 'Entrevista no Senado brasileiro.', 'verified', false, '2025-12-02', 'https://www12.senado.leg.br/noticias/pacheco-sancoes-patria', 'news_article', 1, 'Senado Federal', 'Entrevista', 'pacheco-sancoes-patria-b131-34') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 35
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jom, 'Jorge Messias como ministro do STF condena pressão externa indevida.', 'A Corte não cederá a pressões. Nem internas, nem externas.', 'Primeiro discurso como ministro sobre independência judicial.', 'verified', false, '2025-12-05', 'https://www.conjur.com.br/2025-dez-05/messias-pressao-externa-stf/', 'news_article', 2, 'STF', 'Sessão', 'messias-pressao-externa-b131-35') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 36
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moro defende aproximação comercial com Trump, mas critica pedidos de sanção.', 'Comércio sim, sanções não. Isso atinge o Brasil todo.', 'Entrevista em programa dominical.', 'verified', false, '2025-12-08', 'https://www.cnnbrasil.com.br/politica/moro-trump-sancoes-comercio/', 'news_article', 2, 'São Paulo', 'Programa de TV', 'moro-trump-comercio-b131-36') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 37
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_gle, 'Gleisi Hoffmann defende retaliação a lobby bolsonarista nos EUA.', 'O governo deve retaliar quem trabalha contra o Brasil no exterior.', 'Entrevista como líder do governo na Câmara.', 'verified', false, '2025-12-10', 'https://www.camara.leg.br/noticias/1103211-gleisi-retaliacao-lobby', 'news_article', 2, 'Câmara dos Deputados', 'Entrevista', 'gleisi-retaliacao-lobby-b131-37') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 38
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mvh, 'Marcel van Hattem defende relação pragmática com Trump e fim de sanções.', 'Precisamos de pragmatismo. Sanções prejudicam a todos.', 'Discurso na Câmara sobre política externa.', 'verified', false, '2025-12-12', 'https://www.camara.leg.br/noticias/1103245-marcel-trump-pragmatismo', 'news_article', 2, 'Câmara dos Deputados', 'Sessão', 'marcel-trump-pragmatismo-b131-38') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 39
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_pab, 'Pablo Marçal diz que Trump salvou o Ocidente e quer modelo no Brasil.', 'Trump salvou o Ocidente. Brasil precisa de uma versão radical do trumpismo.', 'Live transmitida para milhões de seguidores.', 'verified', false, '2025-12-15', 'https://www.uol.com.br/eleicoes/2025/12/pablo-marcal-trump-ocidente.htm', 'social_media_post', 4, 'São Paulo', 'Live em rede social', 'marcal-trump-ocidente-b131-39') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_aut, true FROM ins;
  -- 40
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_cai, 'Ronaldo Caiado diz que governadores devem dialogar com Trump independentemente do Planalto.', 'Governadores podem e devem dialogar com os EUA diretamente.', 'Entrevista em evento empresarial em Goiânia.', 'verified', false, '2025-12-18', 'https://www.poder360.com.br/governo/caiado-dialogo-trump-governadores/', 'news_article', 3, 'Goiânia', 'Evento empresarial', 'caiado-dialogo-trump-b131-40') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_con, true FROM ins;
  -- 41
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula apresenta balanço de ano e diz que Brasil resistiu à pressão de Trump.', 'Apesar da pressão, mantivemos nossa soberania e nossa agenda.', 'Pronunciamento de fim de ano em cadeia nacional.', 'verified', true, '2025-12-28', 'https://g1.globo.com/politica/noticia/2025/12/28/lula-balanco-trump.ghtml', 'news_article', 2, 'Brasília', 'Pronunciamento em cadeia nacional', 'lula-balanco-trump-b131-41') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 42
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_rog, 'Rogério Marinho defende emenda que bloqueia represálias a quem busca sanções americanas.', 'Liberdade de expressão inclui falar com autoridades americanas.', 'Discurso no Senado.', 'verified', false, '2026-01-08', 'https://www12.senado.leg.br/noticias/rogerio-emenda-represalia-eua', 'news_article', 3, 'Senado Federal', 'Sessão', 'rogerio-emenda-represalia-b131-42') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 43
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_amo, 'Moraes amplia investigação sobre atuação de parlamentares nos EUA.', 'A investigação se estende a quem articulou sanções contra o Brasil.', 'Decisão em inquérito sobre atuação antinacional.', 'verified', true, '2026-01-15', 'https://g1.globo.com/politica/noticia/2026/01/15/moraes-investigacao-parlamentares-eua.ghtml', 'news_article', 3, 'STF', 'Decisão', 'moraes-investigacao-eua-b131-43') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;
  -- 44
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro denuncia decisão de Moraes e pede extradição negada.', 'Moraes agora persegue parlamentares no exterior. Os EUA vão negar qualquer extradição.', 'Postagem em rede social após decisão de Moraes.', 'verified', true, '2026-01-16', 'https://www.metropoles.com/brasil/politica-br/eduardo-extradicao-negada', 'social_media_post', 5, 'Washington, EUA', 'Postagem em rede social', 'eduardo-extradicao-negada-b131-44') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_obs, true FROM ins;
  -- 45
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula diz que Brasil não aceita interferência em ano eleitoral.', 'Não aceitaremos interferência de Trump nas eleições brasileiras.', 'Pronunciamento em reunião com ministros.', 'verified', true, '2026-01-20', 'https://www1.folha.uol.com.br/poder/2026/01/lula-interferencia-eleicoes.shtml', 'news_article', 2, 'Brasília', 'Reunião ministerial', 'lula-interferencia-eleicoes-b131-45') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 46
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_tar, 'Tarcísio busca aliança com governadores republicanos americanos.', 'Estamos construindo parcerias com governadores americanos.', 'Entrevista em evento sobre federalismo.', 'verified', false, '2026-01-25', 'https://www1.folha.uol.com.br/poder/2026/01/tarcisio-governadores-republicanos.shtml', 'news_article', 2, 'São Paulo', 'Evento sobre federalismo', 'tarcisio-governadores-republicanos-b131-46') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_con, true FROM ins;
  -- 47
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mic, 'Michelle Bolsonaro discursa em evento evangélico com apoiadores de Trump.', 'Trump e Bolsonaro foram escolhidos por Deus para salvar nossos países.', 'Discurso em evento evangélico no Texas.', 'verified', true, '2026-02-02', 'https://www.metropoles.com/brasil/politica-br/michelle-texas-evangelico', 'news_article', 3, 'Texas, EUA', 'Evento evangélico', 'michelle-texas-evangelico-b131-47') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 48
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro retoma atividades e anuncia aliança estratégica com Trump.', 'Trump é o grande aliado do Brasil que ama a liberdade.', 'Coletiva à imprensa no Centro de Tradições Gaúchas.', 'verified', true, '2026-02-10', 'https://www.cnnbrasil.com.br/politica/bolsonaro-alianca-trump-2026/', 'news_article', 4, 'Porto Alegre', 'Coletiva', 'bolsonaro-alianca-trump-2026-b131-48') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 49
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_amo, 'Moraes declara que 2026 será ano de combate à interferência externa.', 'A defesa da democracia passa por barrar interferência externa nas eleições.', 'Discurso em seminário sobre democracia.', 'verified', true, '2026-02-15', 'https://g1.globo.com/politica/noticia/2026/02/15/moraes-interferencia-2026.ghtml', 'news_article', 3, 'Brasília', 'Seminário', 'moraes-interferencia-2026-b131-49') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;
  -- 50
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nik, 'Nikolas Ferreira acusa Moraes de censurar conteúdo sobre Trump.', 'Moraes quer nos censurar também sobre Trump.', 'Postagem em redes sociais com conteúdo sobre Trump.', 'verified', true, '2026-02-18', 'https://www.metropoles.com/brasil/politica-br/nikolas-moraes-censura-trump', 'social_media_post', 3, 'Brasília', 'Postagem em rede social', 'nikolas-moraes-censura-trump-b131-50') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 51
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_ran, 'Randolfe Rodrigues propõe lei para criminalizar lobby antinacional.', 'Lobby contra o Brasil no exterior precisa ser crime tipificado.', 'Apresentação de projeto de lei no Senado.', 'verified', false, '2026-02-20', 'https://www12.senado.leg.br/noticias/randolfe-lei-lobby-antinacional', 'news_article', 2, 'Senado Federal', 'Protocolo de PL', 'randolfe-lei-lobby-b131-51') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 52
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fla, 'Flávio Bolsonaro critica projeto de Randolfe como censura.', 'Isso é censura a parlamentares. Vou contestar no STF.', 'Entrevista no Senado.', 'verified', false, '2026-02-22', 'https://www12.senado.leg.br/noticias/flavio-projeto-randolfe-censura', 'news_article', 3, 'Senado Federal', 'Entrevista', 'flavio-randolfe-censura-b131-52') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 53
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro se reúne com enviado de Trump em São Paulo.', 'Trump enviou representante para dialogar com nossa base.', 'Confirmação em rede social sobre reunião com enviado.', 'verified', true, '2026-02-25', 'https://www.cnnbrasil.com.br/politica/bolsonaro-enviado-trump-sp/', 'social_media_post', 4, 'São Paulo', 'Reunião com enviado', 'bolsonaro-enviado-trump-sp-b131-53') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 54
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula convoca reunião de emergência com ministros após reunião de Bolsonaro com enviado de Trump.', 'Não aceitaremos que emissários estrangeiros articulem com políticos brasileiros contra o Brasil.', 'Coletiva após reunião ministerial de emergência.', 'verified', true, '2026-02-26', 'https://g1.globo.com/politica/noticia/2026/02/26/lula-emissario-trump-emergencia.ghtml', 'news_article', 2, 'Brasília', 'Coletiva', 'lula-emissario-trump-b131-54') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 55
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mau, 'Mauro Vieira entrega nota diplomática aos EUA em resposta a emissário.', 'Entregamos nota diplomática formal sobre ações do enviado americano.', 'Nota do Itamaraty.', 'verified', true, '2026-02-27', 'https://www1.folha.uol.com.br/mundo/2026/02/mauro-vieira-nota-diplomatica-eua.shtml', 'news_article', 2, 'Brasília', 'Itamaraty', 'mauro-nota-diplomatica-eua-b131-55') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 56
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro anuncia que Trump prepara sanções contra ministros brasileiros.', 'Estamos próximos. Trump prepara as sanções contra ministros do STF.', 'Entrevista em rede conservadora americana.', 'verified', true, '2026-03-02', 'https://www.foxnews.com/world/eduardo-bolsonaro-sancoes-ministros-stf', 'news_article', 5, 'Washington, EUA', 'Entrevista', 'eduardo-sancoes-ministros-b131-56') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 57
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_amo, 'Moraes determina investigação por divulgação de sanções.', 'A divulgação de suposta iminência de sanções é instrumento de pressão.', 'Decisão em inquérito sobre pressão externa.', 'verified', true, '2026-03-03', 'https://g1.globo.com/politica/noticia/2026/03/03/moraes-investigacao-divulgacao-sancoes.ghtml', 'news_article', 3, 'STF', 'Decisão', 'moraes-investigacao-sancoes-b131-57') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;
  -- 58
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro comemora anúncio de Eduardo sobre sanções.', 'Agora a verdade virá. Os algozes serão sancionados.', 'Live após anúncio de Eduardo sobre sanções.', 'verified', true, '2026-03-04', 'https://www.metropoles.com/brasil/politica-br/bolsonaro-comemora-sancoes', 'social_media_post', 5, 'Porto Alegre', 'Live em rede social', 'bolsonaro-comemora-sancoes-b131-58') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 59
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula convoca cadeia nacional para denunciar plano de sanções.', 'O Brasil não é colônia de ninguém. Vamos resistir.', 'Pronunciamento em cadeia nacional.', 'verified', true, '2026-03-05', 'https://g1.globo.com/politica/noticia/2026/03/05/lula-cadeia-nacional-sancoes.ghtml', 'news_article', 3, 'Brasília', 'Cadeia nacional', 'lula-cadeia-sancoes-b131-59') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 60
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Sergio Moro critica plano de sanções como prejudicial ao Brasil.', 'Sanções são ruins para o Brasil. Sou contra.', 'Entrevista a rádio em Curitiba.', 'verified', false, '2026-03-06', 'https://www.cnnbrasil.com.br/politica/moro-contra-sancoes-stf/', 'news_article', 2, 'Curitiba', 'Entrevista à rádio', 'moro-contra-sancoes-b131-60') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 61
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_gil, 'Gilmar Mendes diz que STF não se intimidará com sanções americanas.', 'Nenhum ministro do STF será intimidado.', 'Entrevista em programa jurídico.', 'verified', true, '2026-03-07', 'https://www.conjur.com.br/2026-mar-07/gilmar-mendes-sancoes-intimidacao/', 'news_article', 2, 'Brasília', 'Entrevista', 'gilmar-sancoes-intimidacao-b131-61') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 62
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_din, 'Flávio Dino critica articulação bolsonarista por sanções.', 'É atentado contra a Nação. Serão responsabilizados.', 'Declaração em sessão administrativa do STF.', 'verified', true, '2026-03-08', 'https://www.poder360.com.br/justica/dino-atentado-nacao/', 'news_article', 3, 'STF', 'Sessão', 'dino-atentado-nacao-b131-62') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 63
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_car, 'Cármen Lúcia defende unidade do STF contra pressões externas.', 'O STF unido resistirá a qualquer pressão externa.', 'Pronunciamento em sessão solene.', 'verified', true, '2026-03-10', 'https://www.stf.jus.br/portal/cms/verNoticiaDetalhe.asp?carmen-unidade-stf', 'news_article', 2, 'STF', 'Sessão solene', 'carmen-unidade-stf-b131-63') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 64
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_bar, 'Barroso, já fora do STF, critica sanções e defende soberania judicial.', 'Mesmo fora, defendo que o STF não pode ser pressionado por governos estrangeiros.', 'Entrevista como professor na FGV.', 'verified', false, '2026-03-12', 'https://www.conjur.com.br/2026-mar-12/barroso-sancoes-soberania/', 'news_article', 1, 'Rio de Janeiro', 'Entrevista', 'barroso-sancoes-soberania-b131-64') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 65
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fux, 'Fux se manifesta pela preservação da autonomia do STF.', 'A autonomia da Corte não é negociável.', 'Discurso em seminário jurídico.', 'verified', false, '2026-03-14', 'https://www.jota.info/stf/do-supremo/fux-autonomia-stf-2026', 'news_article', 1, 'São Paulo', 'Seminário', 'fux-autonomia-2026-b131-65') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 66
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fac, 'Fachin como presidente do STF convoca reunião com chefes de Poderes.', 'Convocamos reunião institucional diante da grave ameaça.', 'Comunicado oficial do STF.', 'verified', true, '2026-03-15', 'https://g1.globo.com/politica/noticia/2026/03/15/fachin-reuniao-poderes-sancoes.ghtml', 'news_article', 2, 'STF', 'Comunicado', 'fachin-reuniao-poderes-b131-66') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 67
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_dav, 'Davi Alcolumbre participa de reunião institucional no STF.', 'Senado está ao lado do STF na defesa da soberania.', 'Declaração após reunião institucional.', 'verified', false, '2026-03-15', 'https://www12.senado.leg.br/noticias/alcolumbre-reuniao-stf', 'news_article', 1, 'STF', 'Reunião institucional', 'alcolumbre-reuniao-stf-b131-67') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 68
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_hug, 'Hugo Motta afirma que Câmara dialoga com STF em momento de crise.', 'A Câmara está presente no diálogo institucional.', 'Declaração após reunião no STF.', 'verified', false, '2026-03-15', 'https://www.camara.leg.br/noticias/1105111-hugo-motta-reuniao-stf', 'news_article', 1, 'STF', 'Reunião institucional', 'hugo-reuniao-stf-b131-68') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 69
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nik, 'Nikolas Ferreira chama reunião de conspiração contra o povo.', 'Reunião é conspiração entre Poderes para calar o povo.', 'Postagem após reunião institucional.', 'verified', true, '2026-03-16', 'https://www.metropoles.com/brasil/politica-br/nikolas-conspiracao-poderes', 'social_media_post', 4, 'Brasília', 'Postagem em rede social', 'nikolas-conspiracao-poderes-b131-69') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 70
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro anuncia em Washington que sanções serão assinadas em abril.', 'As sanções virão. Estamos finalizando em Washington.', 'Entrevista à imprensa americana.', 'verified', true, '2026-03-20', 'https://www.politico.com/news/2026/03/20/eduardo-bolsonaro-sancoes-abril', 'news_article', 5, 'Washington, EUA', 'Entrevista', 'eduardo-sancoes-abril-b131-70') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 71
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula faz pronunciamento defendendo resistência institucional.', 'O Brasil resistirá com todas as suas instituições unidas.', 'Pronunciamento em cadeia de rádio e TV.', 'verified', true, '2026-03-22', 'https://www1.folha.uol.com.br/poder/2026/03/lula-resistencia-institucional.shtml', 'news_article', 2, 'Brasília', 'Pronunciamento', 'lula-resistencia-institucional-b131-71') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 72
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_had, 'Haddad apresenta plano de contingência econômica contra sanções.', 'Estamos prontos para qualquer cenário econômico.', 'Entrevista coletiva no Ministério da Fazenda.', 'verified', true, '2026-03-23', 'https://valor.globo.com/brasil/noticia/2026/03/23/haddad-contingencia-sancoes.ghtml', 'news_article', 2, 'Brasília', 'Coletiva', 'haddad-contingencia-sancoes-b131-72') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 73
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mau, 'Mauro Vieira anuncia articulação com BRICS contra sanções unilaterais.', 'O BRICS se alinha em defesa contra sanções unilaterais.', 'Nota do Itamaraty.', 'verified', true, '2026-03-25', 'https://www.reuters.com/world/americas/mauro-vieira-brics-sancoes/', 'news_article', 2, 'Brasília', 'Itamaraty', 'mauro-brics-sancoes-b131-73') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 74
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro convoca ato na Paulista para apoiar sanções americanas.', 'Vamos para a rua apoiar as sanções contra os algozes.', 'Convocação em live semanal.', 'verified', true, '2026-03-28', 'https://www.cnnbrasil.com.br/politica/bolsonaro-ato-paulista-sancoes/', 'social_media_post', 5, 'Porto Alegre', 'Live em rede social', 'bolsonaro-ato-paulista-sancoes-b131-74') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 75
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_amo, 'Moraes proíbe difusão de notícias falsas sobre sanções.', 'Determino o bloqueio de contas que difundirem desinformação sobre sanções.', 'Decisão monocrática sobre inquérito das milícias digitais.', 'verified', true, '2026-03-29', 'https://g1.globo.com/politica/noticia/2026/03/29/moraes-bloqueio-contas-sancoes.ghtml', 'news_article', 3, 'STF', 'Decisão monocrática', 'moraes-bloqueio-sancoes-b131-75') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;
  -- 76
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nik, 'Nikolas Ferreira descumpre decisão de Moraes e faz live sobre sanções.', 'Moraes pode tentar calar, mas não conseguirá.', 'Live transmitida em desafio à decisão.', 'verified', true, '2026-03-30', 'https://www.metropoles.com/brasil/politica-br/nikolas-desafia-moraes-live', 'social_media_post', 5, 'Brasília', 'Live em rede social', 'nikolas-desafia-moraes-sancoes-b131-76') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_obs, true FROM ins;
  -- 77
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro lidera ato na Paulista com bandeiras americanas.', 'Obrigado presidente Trump. A liberdade está vindo.', 'Discurso no ato na Avenida Paulista.', 'verified', true, '2026-04-01', 'https://www1.folha.uol.com.br/poder/2026/04/bolsonaro-ato-paulista-trump.shtml', 'news_article', 5, 'Av. Paulista', 'Ato bolsonarista', 'bolsonaro-ato-paulista-trump-b131-77') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 78
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro participa do ato por videoconferência de Washington.', 'De Washington, digo ao povo brasileiro: a liberdade chega em breve.', 'Mensagem transmitida no ato da Paulista.', 'verified', true, '2026-04-01', 'https://www.cnnbrasil.com.br/politica/eduardo-videoconferencia-paulista/', 'news_article', 5, 'Washington, EUA', 'Videoconferência para ato', 'eduardo-videoconferencia-paulista-b131-78') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 79
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula chama ato de traição e convoca defensores da democracia.', 'Quem fala com bandeira americana contra juízes brasileiros é traidor.', 'Pronunciamento após ato bolsonarista.', 'verified', true, '2026-04-02', 'https://g1.globo.com/politica/noticia/2026/04/02/lula-traicao-ato-paulista.ghtml', 'news_article', 3, 'Brasília', 'Pronunciamento', 'lula-traicao-ato-paulista-b131-79') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 80
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_bou, 'Boulos convoca ato pró-soberania em resposta a bolsonaristas.', 'Vamos para a rua defender o Brasil soberano.', 'Coletiva convocando ato em Brasília.', 'verified', false, '2026-04-03', 'https://www.cnnbrasil.com.br/politica/boulos-ato-soberania/', 'news_article', 2, 'Brasília', 'Coletiva', 'boulos-ato-soberania-b131-80') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 81
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_gle, 'Gleisi Hoffmann articula resposta política ao lobby bolsonarista.', 'Vamos responder politicamente a quem conspira contra o país.', 'Reunião com líderes do governo no Planalto.', 'verified', false, '2026-04-04', 'https://www.poder360.com.br/governo/gleisi-resposta-lobby/', 'news_article', 2, 'Brasília', 'Reunião de líderes', 'gleisi-resposta-lobby-b131-81') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 82
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_teb, 'Simone Tebet lidera missão a Washington para evitar sanções.', 'Vamos dialogar diretamente com o governo americano.', 'Entrevista antes de viagem.', 'verified', false, '2026-04-05', 'https://valor.globo.com/brasil/noticia/2026/04/05/tebet-missao-washington.ghtml', 'news_article', 1, 'Brasília', 'Coletiva', 'tebet-missao-washington-b131-82') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 83
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_alc, 'Alckmin compõe comitiva diplomática a Washington.', 'Vamos negociar com firmeza e sem concessões à soberania.', 'Entrevista em aeroporto antes de viagem.', 'verified', false, '2026-04-06', 'https://g1.globo.com/politica/noticia/2026/04/06/alckmin-comitiva-washington.ghtml', 'news_article', 1, 'Brasília', 'Embarque para missão', 'alckmin-comitiva-washington-b131-83') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 84
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mau, 'Mauro Vieira reúne-se com Marco Rubio em Washington.', 'Reunião construtiva para buscar caminhos sem sanções.', 'Nota conjunta após reunião com secretário Rubio.', 'verified', true, '2026-04-08', 'https://www.reuters.com/world/americas/mauro-vieira-rubio-washington/', 'news_article', 2, 'Washington', 'Reunião diplomática', 'mauro-rubio-washington-b131-84') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 85
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fla, 'Flávio Bolsonaro acompanha Rubio em paralelo à missão brasileira.', 'Estou com Rubio. Lula não nos representa aqui.', 'Postagem em redes sociais ao lado de Rubio.', 'verified', true, '2026-04-08', 'https://www.cnnbrasil.com.br/politica/flavio-rubio-washington-paralelo/', 'social_media_post', 5, 'Washington', 'Reunião paralela', 'flavio-rubio-paralelo-b131-85') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 86
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_amo, 'Moraes determina investigação sobre reunião paralela de Flávio com Rubio.', 'Reunião paralela configura possível traição contra o Brasil.', 'Decisão em inquérito sobre atuação antinacional.', 'verified', true, '2026-04-09', 'https://g1.globo.com/politica/noticia/2026/04/09/moraes-flavio-rubio-investigacao.ghtml', 'news_article', 4, 'STF', 'Decisão', 'moraes-flavio-rubio-b131-86') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;
  -- 87
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fla, 'Flávio Bolsonaro denuncia investigação como perseguição política.', 'Moraes pirou. Estou exercendo minha função de senador.', 'Coletiva de imprensa no Senado.', 'verified', true, '2026-04-10', 'https://www12.senado.leg.br/noticias/flavio-denuncia-investigacao-moraes', 'news_article', 4, 'Senado Federal', 'Coletiva', 'flavio-denuncia-investigacao-b131-87') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;
  -- 88
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_pac, 'Rodrigo Pacheco critica investigação contra senador por reunião no exterior.', 'A imunidade parlamentar deve ser respeitada mesmo no exterior.', 'Declaração em plenário do Senado.', 'verified', false, '2026-04-11', 'https://www12.senado.leg.br/noticias/pacheco-imunidade-flavio', 'news_article', 2, 'Senado Federal', 'Plenário', 'pacheco-imunidade-flavio-b131-88') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 89
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_ran, 'Randolfe Rodrigues defende investigação e pede cassação de Flávio.', 'Reunião paralela em momento de crise merece cassação.', 'Declaração no plenário do Senado.', 'verified', false, '2026-04-12', 'https://www12.senado.leg.br/noticias/randolfe-cassacao-flavio', 'news_article', 2, 'Senado Federal', 'Plenário', 'randolfe-cassacao-flavio-b131-89') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 90
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lin, 'Lindbergh Farias apresenta representação contra Flávio no Senado.', 'Apresento representação por quebra de decoro parlamentar.', 'Protocolo de representação.', 'verified', false, '2026-04-13', 'https://www.camara.leg.br/noticias/1106111-lindbergh-representacao-flavio', 'news_article', 2, 'Congresso Nacional', 'Protocolo', 'lindbergh-representacao-flavio-b131-90') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 91
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro declara que Trump vai sancionar ministros em questão de dias.', 'Em dias, Trump assinará. Moraes e outros serão sancionados.', 'Live transmitida para apoiadores.', 'verified', true, '2026-04-14', 'https://www.metropoles.com/brasil/politica-br/bolsonaro-trump-sancoes-dias', 'social_media_post', 5, 'Porto Alegre', 'Live em rede social', 'bolsonaro-trump-sancoes-dias-b131-91') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 92
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_amo, 'Moraes recebe proteção reforçada diante de ameaças.', 'Medidas de proteção são tomadas mas não mudam o curso da Corte.', 'Nota do STF sobre reforço de segurança.', 'verified', true, '2026-04-14', 'https://g1.globo.com/politica/noticia/2026/04/14/moraes-protecao-reforcada.ghtml', 'news_article', 3, 'STF', 'Nota de segurança', 'moraes-protecao-reforcada-b131-92') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_int, true FROM ins;
  -- 93
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula anuncia retaliação tarifária preventiva contra EUA.', 'Estamos prontos para responder. Não seremos passivos.', 'Pronunciamento após reunião ministerial.', 'verified', true, '2026-04-15', 'https://g1.globo.com/politica/noticia/2026/04/15/lula-retaliacao-tarifaria.ghtml', 'news_article', 3, 'Brasília', 'Coletiva', 'lula-retaliacao-tarifaria-b131-93') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 94
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_had, 'Haddad detalha plano de retaliação tarifária contra produtos americanos.', 'Temos lista pronta de retaliações em diálogo com setor produtivo.', 'Coletiva de imprensa no Ministério da Fazenda.', 'verified', true, '2026-04-15', 'https://valor.globo.com/brasil/noticia/2026/04/15/haddad-retaliacao-detalhes.ghtml', 'news_article', 2, 'Brasília', 'Coletiva', 'haddad-retaliacao-detalhes-b131-94') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 95
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mau, 'Mauro Vieira aciona OMC contra possíveis sanções dos EUA.', 'O Brasil acionará a OMC contra qualquer sanção unilateral.', 'Nota do Itamaraty sobre ação na OMC.', 'verified', true, '2026-04-16', 'https://www.reuters.com/world/americas/mauro-vieira-omc-sancoes/', 'news_article', 2, 'Brasília', 'Itamaraty', 'mauro-omc-sancoes-b131-95') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 96
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro celebra decreto iminente de Trump sancionando ministros.', 'Em horas Trump assinará. Justiça será feita.', 'Postagem em rede social na véspera da decisão.', 'verified', true, '2026-04-16', 'https://www.cnnbrasil.com.br/politica/eduardo-trump-sancoes-horas/', 'social_media_post', 5, 'Washington', 'Postagem em rede social', 'eduardo-trump-horas-b131-96') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;
  -- 97
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_amo, 'Moraes faz pronunciamento e reafirma que STF não se curvará.', 'Não nos curvaremos. A democracia brasileira é maior que qualquer ameaça.', 'Pronunciamento em sessão plenária do STF.', 'verified', true, '2026-04-17', 'https://g1.globo.com/politica/noticia/2026/04/17/moraes-stf-nao-curvar.ghtml', 'news_article', 3, 'STF', 'Sessão plenária', 'moraes-stf-nao-curvar-b131-97') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;
  -- 98
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula faz cadeia nacional em defesa da soberania e das instituições.', 'Brasil é soberano. Nossas instituições são respeitadas. Não há pressão externa que nos derrube.', 'Cadeia nacional de rádio e TV.', 'verified', true, '2026-04-17', 'https://www1.folha.uol.com.br/poder/2026/04/lula-cadeia-soberania-institucional.shtml', 'news_article', 3, 'Brasília', 'Cadeia nacional', 'lula-cadeia-soberania-b131-98') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 99
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_msi, 'Marina Silva critica retirada dos EUA do Acordo de Paris e cobra responsabilidade climática.', 'A saída dos EUA é golpe no multilateralismo climático. O Brasil vai liderar com outros países.', 'Entrevista sobre agenda climática após um ano de Trump.', 'verified', false, '2026-01-20', 'https://www1.folha.uol.com.br/ambiente/2026/01/marina-silva-trump-clima-aniversario.shtml', 'news_article', 1, 'Brasília', 'Entrevista', 'marina-trump-clima-aniversario-b131-99') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
  -- 100
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_hum, 'Humberto Costa critica articulação bolsonarista como traição histórica.', 'Articular sanções contra o Brasil é a maior traição da história recente.', 'Discurso no plenário do Senado.', 'verified', false, '2026-04-10', 'https://www12.senado.leg.br/noticias/humberto-traicao-historica', 'news_article', 1, 'Senado Federal', 'Sessão plenária', 'humberto-traicao-historica-b131-100') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;
END $$;
