-- Batch 96: Dilma impeachment + Temer era + Lava Jato (2015-2018) - part 1
DO $$
DECLARE
  v_dilma UUID; v_lula UUID; v_temer UUID; v_cunha UUID; v_aecio UUID;
  v_alckmin UUID; v_jair UUID; v_edu UUID; v_fla UUID; v_gle UUID;
  v_moro UUID; v_ciro UUID; v_had UUID; v_serra UUID; v_marta UUID;
  v_maluf UUID; v_sarney UUID; v_renan UUID; v_silas UUID; v_jefferson UUID;
  v_collor UUID; v_guedes UUID; v_lira UUID; v_pacheco UUID; v_feliciano UUID;
  v_damares UUID; v_magno UUID; v_freixo UUID; v_chico UUID; v_jandira UUID;
  c_cor UUID; c_des UUID; c_hom UUID; c_mis UUID; c_rac UUID;
  c_odi UUID; c_abu UUID; c_mac UUID; c_ant UUID; c_irr UUID;
  c_con UUID; c_nep UUID; c_vio UUID; c_int UUID; c_obs UUID; c_ame UUID;
BEGIN
  SELECT id INTO v_dilma FROM politicians WHERE slug = 'dilma-rousseff';
  SELECT id INTO v_lula FROM politicians WHERE slug = 'lula';
  SELECT id INTO v_temer FROM politicians WHERE slug = 'michel-temer';
  SELECT id INTO v_cunha FROM politicians WHERE slug = 'cunha';
  SELECT id INTO v_aecio FROM politicians WHERE slug = 'aecio-neves';
  SELECT id INTO v_alckmin FROM politicians WHERE slug = 'geraldo-alckmin';
  SELECT id INTO v_jair FROM politicians WHERE slug = 'jair-bolsonaro';
  SELECT id INTO v_edu FROM politicians WHERE slug = 'eduardo-bolsonaro';
  SELECT id INTO v_fla FROM politicians WHERE slug = 'flavio-bolsonaro';
  SELECT id INTO v_gle FROM politicians WHERE slug = 'gleisi-hoffmann';
  SELECT id INTO v_moro FROM politicians WHERE slug = 'sergio-moro';
  SELECT id INTO v_ciro FROM politicians WHERE slug = 'ciro-gomes';
  SELECT id INTO v_had FROM politicians WHERE slug = 'fernando-haddad';
  SELECT id INTO v_serra FROM politicians WHERE slug = 'jose-serra';
  SELECT id INTO v_marta FROM politicians WHERE slug = 'marta-suplicy';
  SELECT id INTO v_maluf FROM politicians WHERE slug = 'paulo-maluf';
  SELECT id INTO v_sarney FROM politicians WHERE slug = 'jose-sarney';
  SELECT id INTO v_renan FROM politicians WHERE slug = 'renan-calheiros';
  SELECT id INTO v_silas FROM politicians WHERE slug = 'silas-camara';
  SELECT id INTO v_jefferson FROM politicians WHERE slug = 'roberto-jefferson';
  SELECT id INTO v_collor FROM politicians WHERE slug = 'collor';
  SELECT id INTO v_guedes FROM politicians WHERE slug = 'paulo-guedes';
  SELECT id INTO v_lira FROM politicians WHERE slug = 'arthur-lira';
  SELECT id INTO v_pacheco FROM politicians WHERE slug = 'rodrigo-pacheco';
  SELECT id INTO v_feliciano FROM politicians WHERE slug = 'marco-feliciano';
  SELECT id INTO v_damares FROM politicians WHERE slug = 'damares-alves';
  SELECT id INTO v_magno FROM politicians WHERE slug = 'magno-malta';
  SELECT id INTO v_freixo FROM politicians WHERE slug = 'marcelo-freixo';
  SELECT id INTO v_chico FROM politicians WHERE slug = 'chico-alencar';
  SELECT id INTO v_jandira FROM politicians WHERE slug = 'jandira-feghali';

  SELECT id INTO c_cor FROM categories WHERE slug = 'corrupcao';
  SELECT id INTO c_des FROM categories WHERE slug = 'desinformacao';
  SELECT id INTO c_hom FROM categories WHERE slug = 'homofobia';
  SELECT id INTO c_mis FROM categories WHERE slug = 'misoginia';
  SELECT id INTO c_rac FROM categories WHERE slug = 'racismo';
  SELECT id INTO c_odi FROM categories WHERE slug = 'discurso-de-odio';
  SELECT id INTO c_abu FROM categories WHERE slug = 'abuso-de-poder';
  SELECT id INTO c_mac FROM categories WHERE slug = 'machismo';
  SELECT id INTO c_ant FROM categories WHERE slug = 'antidemocratico';
  SELECT id INTO c_irr FROM categories WHERE slug = 'irresponsabilidade';
  SELECT id INTO c_con FROM categories WHERE slug = 'conflito-interesses';
  SELECT id INTO c_nep FROM categories WHERE slug = 'nepotismo';
  SELECT id INTO c_vio FROM categories WHERE slug = 'violencia';
  SELECT id INTO c_int FROM categories WHERE slug = 'intimidacao';
  SELECT id INTO c_obs FROM categories WHERE slug = 'obstrucao-justica';
  SELECT id INTO c_ame FROM categories WHERE slug = 'ameaca-instituicoes';

  -- 1 Bolsonaro dedica voto a Ustra (17/04/2016)
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jair, 'Bolsonaro dedica voto pelo impeachment de Dilma ao coronel Brilhante Ustra, torturador da ditadura.', 'Pela memória do coronel Carlos Alberto Brilhante Ustra, o pavor de Dilma Rousseff, pelo exército de Caxias, pelas Forças Armadas, por um Brasil acima de tudo e por Deus acima de todos, o meu voto é sim!', 'Durante votação nominal do impeachment na Câmara dos Deputados, Bolsonaro homenageou publicamente o torturador que chefiou o DOI-CODI de São Paulo, agente que torturou a própria Dilma nos anos 1970.', 'verified', true, '2016-04-17', 'https://www1.folha.uol.com.br/poder/2016/04/1763027-bolsonaro-dedica-voto-a-coronel-que-torturou-dilma-na-ditadura.shtml', 'news_article', 5, 'Câmara dos Deputados', 'Votação do impeachment', 'bolsonaro-voto-ustra-impeachment-b96-1') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins UNION ALL SELECT id, c_odi, false FROM ins UNION ALL SELECT id, c_vio, false FROM ins;

  -- 2 Dilma defesa impeachment
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_dilma, 'Dilma afirma em defesa no Senado que o impeachment é um golpe contra a democracia e contra as urnas.', 'O que está em jogo é o respeito às urnas, à vontade soberana do povo brasileiro e à Constituição. Não luto pelo meu mandato por vaidade ou por apego ao poder. Luto pela democracia, pela verdade e pela justiça.', 'Discurso de Dilma em sua defesa durante o julgamento final do impeachment no Senado Federal.', 'verified', true, '2016-08-29', 'https://g1.globo.com/politica/processo-de-impeachment-de-dilma/noticia/2016/08/leia-integra-do-discurso-de-dilma-no-senado.html', 'news_article', 1, 'Senado Federal', 'Julgamento do impeachment', 'dilma-defesa-senado-golpe-b96-2') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;

  -- 3 Cunha ameaça abrir impeachment
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_cunha, 'Cunha rompe com governo e sinaliza que vai acolher pedido de impeachment dias depois de PT votar contra ele no Conselho de Ética.', 'Não dá mais para confiar na palavra dada pelo governo. Estou rompido, sim, com este governo.', 'Declaração após bancada do PT votar pela continuidade do processo contra Cunha no Conselho de Ética por contas secretas na Suíça.', 'verified', true, '2015-07-17', 'https://www1.folha.uol.com.br/poder/2015/07/1657998-presidente-da-camara-eduardo-cunha-rompe-com-governo-dilma.shtml', 'news_article', 4, 'Câmara dos Deputados', 'Rompimento com o governo', 'cunha-rompe-governo-b96-3') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins UNION ALL SELECT id, c_cor, false FROM ins;

  -- 4 Cunha aceita impeachment
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_cunha, 'Cunha acolhe pedido de impeachment contra Dilma horas após PT anunciar voto contra ele no Conselho de Ética.', 'Comunico que, com base no parecer da Consultoria Legislativa, defiro o processamento da denúncia por crime de responsabilidade contra a Presidente da República.', 'Presidente da Câmara abre formalmente o processo de impeachment em retaliação a votação contra ele no mesmo dia.', 'verified', true, '2015-12-02', 'https://g1.globo.com/politica/noticia/2015/12/cunha-acolhe-pedido-de-impeachment-de-dilma.html', 'news_article', 4, 'Câmara dos Deputados', 'Abertura do impeachment', 'cunha-acolhe-impeachment-b96-4') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins UNION ALL SELECT id, c_cor, false FROM ins;

  -- 5 Temer carta Dilma
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_temer, 'Temer envia carta pública a Dilma reclamando ser tratado como vice decorativo, sinalizando rompimento.', 'Nunca tive nem terei a vaidade do protagonismo. Mas V. Exa. sabe que fui desprestigiado e que o PMDB foi desconsiderado.', 'Carta de sete páginas vazada à imprensa revelou ruptura entre Temer e Dilma, prenúncio do apoio do PMDB ao impeachment.', 'verified', true, '2015-12-07', 'https://www1.folha.uol.com.br/poder/2015/12/1714944-leia-integra-da-carta-de-michel-temer-a-dilma.shtml', 'news_article', 2, 'Brasília', 'Carta ao Palácio do Planalto', 'temer-carta-dilma-b96-5') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;

  -- 6 Temer audio vazado
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_temer, 'Áudio de Temer vazado ensaia discurso de posse antes mesmo da votação final do impeachment no Senado.', 'Muita gente terá que se unir para tirar o país dessa crise em que se encontra. Tenho a convicção absoluta de que todos terão um pouco de cada um.', 'Áudio gravado dias antes da votação final do impeachment mostra Temer já se preparando para assumir a Presidência.', 'verified', true, '2016-04-11', 'https://www1.folha.uol.com.br/poder/2016/04/1760431-em-audio-temer-ja-fala-como-presidente.shtml', 'news_article', 3, 'Residência oficial', 'Áudio vazado a correligionários', 'temer-audio-vazado-b96-6') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins UNION ALL SELECT id, c_con, false FROM ins;

  -- 7 Aecio pressão
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_aecio, 'Aécio defende o impeachment de Dilma e pede que PSDB encampe oficialmente o processo.', 'O Brasil não aguenta mais esse governo. É hora de encerrar esse ciclo de incompetência e corrupção.', 'Discurso de Aécio Neves em convenção do PSDB durante a crise que antecedeu a abertura do processo de impeachment.', 'verified', false, '2015-11-22', 'https://g1.globo.com/politica/noticia/2015/11/aecio-defende-impeachment-de-dilma-em-convencao-do-psdb.html', 'news_article', 2, 'Convenção PSDB', 'Pressão pelo impeachment', 'aecio-defende-impeachment-b96-7') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;

  -- 8 Aecio JBS
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_aecio, 'Em gravação feita por Joesley Batista, Aécio pede R$ 2 milhões alegando ser para pagar advogados.', 'Tem que ser alguém do seu absoluto controle, da sua confiança, senão a gente morre. Morre, cara.', 'Gravação clandestina entregue à PGR na delação da JBS mostra Aécio combinando recebimento de propina.', 'verified', true, '2017-05-18', 'https://g1.globo.com/politica/operacao-lava-jato/noticia/audio-joesley-aecio-integra.ghtml', 'news_article', 5, 'Residência de Aécio', 'Delação da JBS', 'aecio-audio-joesley-b96-8') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins UNION ALL SELECT id, c_abu, false FROM ins;

  -- 9 Temer JBS audio
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_temer, 'Gravação secreta feita por Joesley mostra Temer dando anuência a pagamento para comprar silêncio de Cunha.', 'Tem que manter isso, viu?', 'Áudio gravado no Palácio do Jaburu registra Temer reagindo ao relato de Joesley sobre pagar propina a Cunha preso.', 'verified', true, '2017-05-17', 'https://www1.folha.uol.com.br/poder/2017/05/1884283-gravacao-de-joesley-pegou-temer-em-flagrante-diz-procurador.shtml', 'news_article', 5, 'Palácio do Jaburu', 'Delação JBS', 'temer-audio-jbs-b96-9') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins UNION ALL SELECT id, c_obs, false FROM ins;

  -- 10 Temer pronuncamento JBS
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_temer, 'Temer vai à TV e diz que não renunciará após vazamento de áudio com Joesley Batista.', 'Não renunciarei. Repito, não renunciarei. Exijo ampla e rápida investigação para que tudo seja esclarecido ao povo brasileiro.', 'Pronunciamento em cadeia nacional após revelação dos áudios da JBS que o ligavam a crime de obstrução de justiça.', 'verified', true, '2017-05-18', 'https://g1.globo.com/politica/noticia/leia-na-integra-o-pronunciamento-do-presidente-michel-temer.ghtml', 'news_article', 3, 'Palácio do Planalto', 'Pronunciamento em cadeia nacional', 'temer-nao-renunciarei-b96-10') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 11 Moro condenação Lula
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_moro, 'Moro condena Lula a 9 anos e meio de prisão no caso do triplex do Guarujá em primeira instância.', 'O ex-presidente Luiz Inácio Lula da Silva, responsável pelo crime de corrupção passiva e lavagem de dinheiro, é condenado a 9 anos e 6 meses de reclusão.', 'Sentença de primeira instância proferida por Sergio Moro, então juiz da 13ª Vara Federal de Curitiba, depois revelado parcial pela Vaza Jato.', 'verified', true, '2017-07-12', 'https://g1.globo.com/pr/parana/noticia/moro-condena-lula-a-9-anos-e-meio-de-prisao-no-caso-triplex.ghtml', 'news_article', 4, '13ª Vara Federal de Curitiba', 'Sentença Lava Jato', 'moro-condena-lula-triplex-b96-11') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;

  -- 12 Lula discurso ABC
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lula, 'Lula discursa no Sindicato dos Metalúrgicos antes de se entregar à Polícia Federal em Curitiba.', 'Eles não estão prendendo um homem, eles estão prendendo uma ideia. Não adianta tentar acabar com as minhas ideias, elas já estão pairando no ar e vocês não conseguem prendê-las.', 'Discurso de Lula no ABC paulista antes de se entregar para cumprir prisão após condenação mantida pelo TRF4.', 'verified', true, '2018-04-07', 'https://g1.globo.com/sp/sao-paulo/noticia/leia-a-integra-do-discurso-de-lula-no-sindicato-dos-metalurgicos-do-abc.ghtml', 'news_article', 1, 'Sindicato dos Metalúrgicos - ABC', 'Discurso antes da prisão', 'lula-discurso-abc-prisao-b96-12') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;

  -- 13 Bolsonaro AI-5
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jair, 'Em entrevista, Bolsonaro afirma que faria um novo AI-5 se virasse ditador do Brasil.', 'Vamos fazer o Brasil para a maioria. As minorias têm que se curvar às maiorias. A lei deve existir para defender as maiorias. As minorias se adéquam ou simplesmente desaparecem.', 'Declaração em palestra no Clube Hebraica do Rio de Janeiro em abril de 2017, associada à defesa do AI-5 feita em outras ocasiões.', 'verified', true, '2017-04-03', 'https://veja.abril.com.br/politica/bolsonaro-na-hebraica-as-frases-preconceituosas-do-deputado/', 'news_article', 5, 'Clube Hebraica - Rio de Janeiro', 'Palestra', 'bolsonaro-hebraica-minorias-b96-13') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins UNION ALL SELECT id, c_odi, false FROM ins UNION ALL SELECT id, c_rac, false FROM ins;

  -- 14 Bolsonaro quilombolas
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jair, 'Bolsonaro chama quilombolas de improdutivos e mede peso deles em arrobas, termo usado para escravizados.', 'Eu fui num quilombola em Eldorado Paulista. Olha, o afrodescendente mais leve lá pesava 7 arrobas. Não fazem nada. Eu acho que nem pra procriador ele serve mais.', 'Palestra no Clube Hebraica do Rio, na qual Bolsonaro também defendeu o AI-5, gerou ações penais por racismo.', 'verified', true, '2017-04-03', 'https://www1.folha.uol.com.br/poder/2017/04/1874415-para-bolsonaro-afrodescendente-nao-serve-nem-para-procriar.shtml', 'news_article', 5, 'Clube Hebraica - Rio de Janeiro', 'Palestra', 'bolsonaro-quilombolas-arrobas-b96-14') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_rac, true FROM ins UNION ALL SELECT id, c_odi, false FROM ins;

  -- 15 Cunha preso
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_cunha, 'Preso em Curitiba, Cunha ameaça: disse que levará junto quem o abandonou.', 'Quem me abandonar vai junto comigo.', 'Declaração atribuída a Cunha após a prisão pela Lava Jato, reportada por aliados à imprensa.', 'verified', true, '2016-10-19', 'https://www1.folha.uol.com.br/poder/2016/10/1823074-preso-cunha-diz-que-quem-me-abandonar-vai-junto-comigo.shtml', 'news_article', 3, 'Curitiba', 'Prisão pela Lava Jato', 'cunha-quem-abandonar-b96-15') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_int, true FROM ins UNION ALL SELECT id, c_cor, false FROM ins;

  -- 16 Cunha cassação
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_cunha, 'Cunha nega contas secretas na Suíça durante depoimento na CPI da Petrobras sob juramento.', 'Não tenho, nunca tive contas no exterior. Ponto final.', 'Declaração posteriormente desmentida por documentos da Lava Jato, usada como base para a cassação de seu mandato.', 'verified', true, '2015-03-12', 'https://g1.globo.com/politica/operacao-lava-jato/noticia/2015/03/cunha-nega-conta-na-suica-em-depoimento-cpi.html', 'news_article', 4, 'CPI da Petrobras', 'Depoimento sob juramento', 'cunha-nega-contas-suica-b96-16') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins UNION ALL SELECT id, c_des, false FROM ins;

  -- 17 Dilma pedaladas
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_dilma, 'Dilma rebate acusação de pedaladas fiscais dizendo que todos os governos usaram o mesmo instrumento.', 'As chamadas pedaladas são uma prática de gestão contábil adotada por governos anteriores. Não há crime de responsabilidade.', 'Pronunciamento em rede nacional após TCU recomendar rejeição de suas contas de 2014.', 'verified', false, '2015-10-08', 'https://g1.globo.com/politica/noticia/2015/10/em-rede-nacional-dilma-diz-que-pedaladas-foram-praticadas-por-outros.html', 'news_article', 1, 'Palácio do Planalto', 'Pronunciamento em rede nacional', 'dilma-pedaladas-defesa-b96-17') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 18 Dilma "não sou corrupta"
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_dilma, 'Em seu último discurso antes do afastamento, Dilma afirma que não cometeu crime e denuncia golpe parlamentar.', 'Não cometi crime de responsabilidade. Não há prática inconstitucional que justifique meu afastamento. O que está havendo hoje é um golpe.', 'Discurso no Palácio do Planalto horas antes do Senado aprovar o afastamento temporário de Dilma em maio de 2016.', 'verified', true, '2016-05-12', 'https://g1.globo.com/politica/processo-de-impeachment-de-dilma/noticia/2016/05/leia-integra-do-discurso-de-dilma-apos-afastamento.html', 'news_article', 1, 'Palácio do Planalto', 'Afastamento temporário', 'dilma-golpe-afastamento-b96-18') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;

  -- 19 Gleisi defesa Lula
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_gle, 'Gleisi Hoffmann denuncia Moro como juiz parcial após condenação de Lula confirmada pelo TRF4.', 'O julgamento do Lula foi político. Moro conduziu a Lava Jato com clara intenção de destruir politicamente o ex-presidente.', 'Declaração em coletiva de imprensa após o TRF4 confirmar condenação e aumentar pena de Lula.', 'verified', false, '2018-01-24', 'https://www1.folha.uol.com.br/poder/2018/01/1952797-gleisi-diz-que-julgamento-de-lula-foi-politico.shtml', 'news_article', 2, 'Diretório Nacional do PT', 'Coletiva de imprensa', 'gleisi-julgamento-politico-b96-19') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;

  -- 20 Marielle reação Bolsonaro
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jair, 'Bolsonaro minimiza execução de Marielle e sugere que foi episódio pontual do Rio de Janeiro.', 'Foi uma tragédia, mas um caso isolado. O Rio vive isso todos os dias.', 'Declaração dias após o assassinato da vereadora Marielle Franco e do motorista Anderson Gomes no Estácio.', 'verified', false, '2018-03-20', 'https://www.cartacapital.com.br/politica/bolsonaro-minimiza-assassinato-de-marielle/', 'news_article', 4, 'Rio de Janeiro', 'Entrevista após assassinato de Marielle', 'bolsonaro-minimiza-marielle-b96-20') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_odi, true FROM ins UNION ALL SELECT id, c_vio, false FROM ins;

  -- 21 Freixo Marielle
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_freixo, 'Freixo cobra apuração imediata do assassinato de Marielle e responsabiliza milícias do Rio.', 'Marielle foi executada porque lutava contra as milícias. Essa é uma execução política. Quem mandou matar?', 'Discurso na Câmara Municipal do Rio de Janeiro após o assassinato da vereadora Marielle Franco.', 'verified', true, '2018-03-15', 'https://g1.globo.com/rj/rio-de-janeiro/noticia/marcelo-freixo-cobra-quem-mandou-matar-marielle.ghtml', 'news_article', 1, 'Câmara Municipal do Rio', 'Homenagem a Marielle', 'freixo-quem-mandou-matar-marielle-b96-21') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_vio, true FROM ins;

  -- 22 Temer Ponte para o Futuro
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_temer, 'Temer lança programa Ponte para o Futuro com pauta liberal meses antes do impeachment de Dilma.', 'Nossa ponte é da estagnação para o crescimento. Precisamos de reformas profundas e ousadas.', 'Lançamento do documento do PMDB em outubro de 2015 considerado prenúncio do projeto pós-Dilma.', 'verified', false, '2015-10-29', 'https://g1.globo.com/politica/noticia/2015/10/pmdb-lanca-documento-com-propostas-economicas-para-governo.html', 'news_article', 2, 'PMDB', 'Lançamento Ponte para o Futuro', 'temer-ponte-futuro-b96-22') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;

  -- 23 Renan crise
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_renan, 'Renan Calheiros reage a afastamento pelo STF e diz que não vai entregar gabinete.', 'O Senado não vai se curvar a uma decisão individual. Não há precedente para afastamento do presidente do Senado.', 'Declaração após Marco Aurélio afastá-lo liminarmente da presidência do Senado em dezembro de 2016.', 'verified', true, '2016-12-06', 'https://g1.globo.com/politica/noticia/renan-afastado-diz-que-nao-vai-entregar-gabinete.ghtml', 'news_article', 4, 'Senado Federal', 'Afastamento pelo STF', 'renan-nao-entregar-gabinete-b96-23') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins UNION ALL SELECT id, c_abu, false FROM ins;

  -- 24 Renan pacote
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_renan, 'Renan articula pacote que esvazia medidas anticorrupção propostas pelo MPF em retaliação à Lava Jato.', 'O Congresso não pode aceitar que o Judiciário e o Ministério Público pautem a política brasileira.', 'Manobra na Câmara em 29 de novembro de 2016 desfigurou projeto das 10 medidas contra a corrupção.', 'verified', false, '2016-11-30', 'https://www1.folha.uol.com.br/poder/2016/11/1836046-camara-aprova-texto-que-desfigura-10-medidas-contra-corrupcao.shtml', 'news_article', 4, 'Congresso Nacional', 'Votação das 10 medidas', 'renan-desfigura-10-medidas-b96-24') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_obs, true FROM ins UNION ALL SELECT id, c_abu, false FROM ins;

  -- 25 Serra chanceler Temer
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_serra, 'Ministro Serra diz no Itamaraty que politica externa do governo Dilma foi ideológica e fracassada.', 'A política externa do PT foi guiada por preferências ideológicas que custaram caro ao Brasil. Vamos recolocar os interesses nacionais em primeiro lugar.', 'Discurso de posse como ministro de Relações Exteriores do governo Temer em maio de 2016.', 'verified', false, '2016-05-18', 'https://g1.globo.com/politica/noticia/2016/05/serra-ataca-politica-externa-do-pt-em-discurso-de-posse.html', 'news_article', 2, 'Itamaraty', 'Posse como ministro', 'serra-posse-itamaraty-b96-25') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;

  -- 26 Alckmin Bolsonaro
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_alckmin, 'Alckmin ironiza candidatura de Bolsonaro em 2018 chamando-o de patinho feio.', 'O Bolsonaro é o patinho feio. Não tem partido grande, não tem tempo de TV, não tem fundo partidário.', 'Declaração do tucano antes do primeiro turno de 2018, quando Bolsonaro liderava as pesquisas.', 'verified', false, '2018-08-02', 'https://g1.globo.com/politica/eleicoes/2018/noticia/2018/08/02/alckmin-diz-que-bolsonaro-e-o-patinho-feio-da-eleicao.ghtml', 'news_article', 1, 'Convenção PSDB', 'Campanha 2018', 'alckmin-patinho-feio-b96-26') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 27 Haddad substituto Lula
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_had, 'Haddad é anunciado candidato à Presidência após TSE barrar Lula com base na Ficha Limpa.', 'Assumo esta missão com humildade e consciência do tamanho da responsabilidade. Serei a voz de quem foi calado.', 'Convenção do PT em setembro de 2018 oficializou Haddad no lugar de Lula, impedido de disputar.', 'verified', true, '2018-09-11', 'https://g1.globo.com/politica/eleicoes/2018/noticia/2018/09/11/pt-oficializa-haddad-como-candidato-a-presidente.ghtml', 'news_article', 1, 'Diretório Nacional do PT', 'Convenção', 'haddad-candidato-oficial-b96-27') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 28 Ciro ataque PT
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_ciro, 'Ciro acusa PT de sabotar sua candidatura por recusar aliança no primeiro turno de 2018.', 'O PT preferiu apostar na derrota para manter hegemonia na esquerda. É irresponsável com o Brasil.', 'Declaração em entrevista durante reta final da campanha presidencial de 2018.', 'verified', false, '2018-10-05', 'https://www1.folha.uol.com.br/poder/2018/10/ciro-acusa-pt-de-sabotagem-na-campanha.shtml', 'news_article', 2, 'Campanha PDT', 'Entrevista', 'ciro-acusa-pt-sabotagem-b96-28') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 29 Ciro Bolsonaro fascista
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_ciro, 'Ciro Gomes chama Bolsonaro de fascista e alerta para risco à democracia em 2018.', 'Bolsonaro é um fascista. Quem vota nele sabe o que está fazendo. É uma ameaça à democracia brasileira.', 'Comício do PDT em Brasília na reta final da campanha de 2018.', 'verified', false, '2018-09-19', 'https://g1.globo.com/politica/eleicoes/2018/noticia/2018/09/19/ciro-chama-bolsonaro-de-fascista-em-comicio.ghtml', 'news_article', 1, 'Brasília', 'Comício PDT', 'ciro-bolsonaro-fascista-b96-29') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;

  -- 30 Eduardo Bolsonaro soldado
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro diz que bastaria um soldado e um cabo para fechar o STF.', 'Se quiser fechar o STF, você não manda um jurista. Manda o soldado. Não vai nem precisar de jipe. É um soldado e um cabo.', 'Entrevista ao Mídia Ninja em julho de 2018, no calor da campanha eleitoral.', 'verified', true, '2018-10-21', 'https://www1.folha.uol.com.br/poder/2018/10/eduardo-bolsonaro-soldado-cabo-stf.shtml', 'news_article', 5, 'Entrevista', 'Declaração sobre STF', 'eduardo-soldado-cabo-stf-b96-30') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins UNION ALL SELECT id, c_ame, false FROM ins;

  -- 31 Flavio milicia queiroz
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fla, 'Flávio Bolsonaro defende o ex-assessor Fabrício Queiroz após revelação do Coaf sobre rachadinha.', 'Meu ex-assessor Queiroz é um trabalhador de bem e está sendo vítima de perseguição política.', 'Reação a reportagens sobre movimentações atípicas de R$ 1,2 milhão na conta de Queiroz durante mandato no Rio.', 'verified', false, '2018-12-07', 'https://g1.globo.com/rj/rio-de-janeiro/noticia/flavio-bolsonaro-defende-queiroz-e-fala-em-perseguicao.ghtml', 'news_article', 4, 'Rio de Janeiro', 'Entrevista', 'flavio-defende-queiroz-b96-31') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins UNION ALL SELECT id, c_con, false FROM ins;

  -- 32 Jose Serra delação
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_serra, 'Serra rebate delatores da Odebrecht que o citam como beneficiário de caixa 2.', 'Nego veementemente qualquer recebimento irregular. As acusações são caluniosas e serão rebatidas na Justiça.', 'Nota oficial após lista do TSE incluir Serra entre citados na delação da Odebrecht em 2017.', 'verified', false, '2017-04-12', 'https://g1.globo.com/politica/operacao-lava-jato/noticia/serra-nega-acusacoes-da-odebrecht.ghtml', 'news_article', 2, 'Gabinete no Senado', 'Nota oficial', 'serra-nega-odebrecht-b96-32') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins;

  -- 33 Marta Suplicy rompe PT
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_marta, 'Marta Suplicy anuncia saída do PT em carta dura e declara apoio ao impeachment de Dilma.', 'Estou desiludida com o PT. O partido perdeu o rumo e se tornou refém da velha política que um dia combateu.', 'Carta pública de desfiliação do PT após 34 anos, em abril de 2015.', 'verified', true, '2015-04-21', 'https://g1.globo.com/politica/noticia/2015/04/marta-suplicy-deixa-o-pt-apos-34-anos-leia-integra-da-carta.html', 'news_article', 2, 'Senado Federal', 'Desfiliação partidária', 'marta-sai-pt-b96-33') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 34 Maluf preso
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_maluf, 'Preso em dezembro de 2017 após condenação pelo STF, Maluf diz ser alvo de perseguição.', 'Sou perseguido há mais de 30 anos. Nunca desviei um centavo. Tudo é invenção de adversários políticos.', 'Declaração após prisão determinada pelo STF por lavagem de dinheiro no caso da prefeitura de São Paulo.', 'verified', false, '2017-12-20', 'https://g1.globo.com/sp/sao-paulo/noticia/maluf-diz-ser-perseguido-apos-prisao-determinada-pelo-stf.ghtml', 'news_article', 3, 'São Paulo', 'Prisão pelo STF', 'maluf-preso-perseguicao-b96-34') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins;

  -- 35 Sarney Lava Jato
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_sarney, 'Sarney ataca Lava Jato dizendo que operação desestabiliza o Brasil.', 'O Brasil está parado por causa dessa operação. É preciso colocar limite nessa farra de delações.', 'Entrevista à Folha em que o ex-presidente criticou a abrangência da operação Lava Jato.', 'verified', false, '2017-07-09', 'https://www1.folha.uol.com.br/poder/2017/07/1900123-sarney-critica-lava-jato-em-entrevista.shtml', 'news_article', 3, 'Residência - Brasília', 'Entrevista', 'sarney-critica-lava-jato-b96-35') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_obs, true FROM ins;

  -- 36 Jefferson mensalão
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jefferson, 'Roberto Jefferson, em entrevista, reafirma versão do mensalão e mira Lula na Lava Jato.', 'O Lula sabia de tudo. Eu denunciei em 2005 e agora a Lava Jato confirma tudo o que eu disse.', 'Entrevista ao Estadão em junho de 2017, aproveitando momento da Lava Jato.', 'verified', false, '2017-06-15', 'https://www.estadao.com.br/politica/roberto-jefferson-reafirma-mensalao-em-entrevista/', 'news_article', 2, 'Brasília', 'Entrevista Estadão', 'jefferson-reafirma-mensalao-b96-36') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins;

  -- 37 Collor Lava Jato
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_collor, 'Denunciado pela PGR na Lava Jato, Collor diz ser vítima de aparelhamento do MPF.', 'O Ministério Público está aparelhado. Sou vítima da mesma máquina que um dia tentou me destruir.', 'Declaração em plenário do Senado após denúncia por corrupção na Lava Jato.', 'verified', false, '2015-09-15', 'https://g1.globo.com/politica/operacao-lava-jato/noticia/2015/09/collor-se-defende-no-plenario-do-senado.html', 'news_article', 3, 'Senado Federal', 'Pronunciamento no plenário', 'collor-pgr-aparelhada-b96-37') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins UNION ALL SELECT id, c_ame, false FROM ins;

  -- 38 Guedes fundos offshore
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_guedes, 'Paulo Guedes é apresentado como futuro superministro de Bolsonaro e defende privatizações amplas.', 'Vamos privatizar tudo o que der pra privatizar. O Estado brasileiro quebrou e precisa ser reinventado.', 'Entrevista durante campanha de 2018, após ser anunciado como guru econômico de Bolsonaro.', 'verified', false, '2018-08-06', 'https://www1.folha.uol.com.br/mercado/2018/08/guedes-defende-privatizar-tudo-em-entrevista.shtml', 'news_article', 2, 'São Paulo', 'Entrevista à Folha', 'guedes-privatizar-tudo-b96-38') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_con, true FROM ins;

  -- 39 Lira apoio Temer
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lira, 'Arthur Lira articula voto do centrão para salvar Temer da denúncia por corrupção passiva.', 'Vamos votar com o governo. O Brasil precisa estabilidade, não de mais um golpe contra presidente eleito.', 'Articulação para votação de 2 de agosto de 2017 que rejeitou denúncia contra Temer na Câmara.', 'verified', false, '2017-08-01', 'https://g1.globo.com/politica/noticia/lira-articula-voto-contra-denuncia-de-temer.ghtml', 'news_article', 3, 'Câmara dos Deputados', 'Articulação do centrão', 'lira-salva-temer-b96-39') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_obs, true FROM ins UNION ALL SELECT id, c_cor, false FROM ins;

  -- 40 Pacheco MP
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_pacheco, 'Rodrigo Pacheco defende MDB no governo Temer e relativiza áudio da JBS.', 'O presidente Temer tem direito ao devido processo legal. Não podemos julgar antes de investigar.', 'Declaração na CCJ da Câmara em maio de 2017, após revelação dos áudios da JBS.', 'verified', false, '2017-05-23', 'https://www12.senado.leg.br/noticias/materias/2017/05/23/pacheco-defende-temer-na-ccj', 'news_article', 2, 'Câmara dos Deputados', 'Sessão da CCJ', 'pacheco-defende-temer-b96-40') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 41 Feliciano bancada
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_feliciano, 'Marco Feliciano articula bancada evangélica pelo impeachment e diz que Dilma abriu o país ao satanismo.', 'Essa presidente abriu as porteiras do inferno no Brasil. Por isso estamos com Cristo contra a Dilma.', 'Culto em igreja em São Paulo em fevereiro de 2016 registrado em vídeo e noticiado pela imprensa.', 'verified', true, '2016-02-20', 'https://www.cartacapital.com.br/politica/feliciano-ataca-dilma-em-culto-satanismo/', 'news_article', 4, 'Igreja evangélica - SP', 'Culto', 'feliciano-dilma-satanismo-b96-41') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins UNION ALL SELECT id, c_odi, false FROM ins UNION ALL SELECT id, c_mis, false FROM ins;

  -- 42 Silas Camara votação
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_silas, 'Silas Câmara vota pelo impeachment e dedica voto à família tradicional evangélica.', 'Pelo Brasil cristão, pelas nossas famílias, pelas nossas igrejas, voto sim pelo impeachment.', 'Voto nominal na sessão do impeachment em 17 de abril de 2016.', 'verified', false, '2016-04-17', 'https://www1.folha.uol.com.br/poder/2016/04/1763106-veja-como-votaram-os-deputados-no-impeachment.shtml', 'news_article', 2, 'Câmara dos Deputados', 'Votação impeachment', 'silas-voto-impeachment-b96-42') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;

  -- 43 Magno Malta voto
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_magno, 'Magno Malta celebra impeachment e ataca ideologia de gênero em discurso no Senado.', 'O Brasil está sendo salvo da ideologia de gênero que queria destruir nossas crianças.', 'Discurso no plenário do Senado em maio de 2016 após aprovação do afastamento de Dilma.', 'verified', false, '2016-05-12', 'https://www12.senado.leg.br/noticias/materias/2016/05/12/magno-malta-ataca-ideologia-de-genero', 'news_article', 3, 'Senado Federal', 'Discurso no plenário', 'magno-ideologia-genero-b96-43') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_hom, true FROM ins UNION ALL SELECT id, c_des, false FROM ins;

  -- 44 Damares candidatura
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_damares, 'Damares Alves diz em pregação em 2018 que a igreja deve tomar o Brasil e desfazer leis que contrariam a Bíblia.', 'A igreja tem que ocupar os espaços de poder e reverter leis que foram feitas contra o povo de Deus.', 'Pregação em culto evangélico em Brasília durante ano eleitoral.', 'verified', false, '2018-08-11', 'https://www.cartacapital.com.br/politica/damares-prega-pela-tomada-do-poder-pela-igreja/', 'news_article', 4, 'Brasília', 'Culto evangélico', 'damares-igreja-tomar-brasil-b96-44') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins UNION ALL SELECT id, c_hom, false FROM ins;

  -- 45 Chico Alencar defesa Dilma
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_chico, 'Chico Alencar denuncia no plenário o impeachment como golpe parlamentar com viés misógino.', 'O que vemos aqui é o golpe sendo consumado. Muitos colegas votam contra uma mulher por machismo, não por convicção.', 'Discurso na sessão do impeachment na Câmara em 17 de abril de 2016.', 'verified', false, '2016-04-17', 'https://g1.globo.com/politica/processo-de-impeachment-de-dilma/noticia/2016/04/chico-alencar-denuncia-golpe-no-plenario.html', 'news_article', 1, 'Câmara dos Deputados', 'Votação impeachment', 'chico-golpe-plenario-b96-45') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;

  -- 46 Jandira defesa Dilma
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jandira, 'Jandira Feghali lidera oposição ao impeachment apontando machismo no processo.', 'O impeachment é golpe e é machista. Nenhum crime foi provado. O que há é um homem querendo tirar uma mulher da cadeira.', 'Pronunciamento no plenário da Câmara em 15 de abril de 2016.', 'verified', false, '2016-04-15', 'https://www1.folha.uol.com.br/poder/2016/04/1762658-jandira-classifica-impeachment-como-golpe-machista.shtml', 'news_article', 1, 'Câmara dos Deputados', 'Defesa de Dilma', 'jandira-golpe-machista-b96-46') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins UNION ALL SELECT id, c_mis, false FROM ins;

  -- 47 Lula STF habeas
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lula, 'Lula grava mensagem em Curitiba pedindo que o PT não se submeta à perseguição política.', 'Eu sou tanto povo que não posso me calar. Eu sou tanto povo que me multiplico. Estarei com vocês.', 'Mensagem gravada na Superintendência da PF em Curitiba onde Lula cumpria prisão em abril de 2018.', 'verified', true, '2018-04-11', 'https://g1.globo.com/pr/parana/noticia/pt-divulga-mensagem-de-lula-preso.ghtml', 'news_article', 1, 'Superintendência da PF Curitiba', 'Mensagem da prisão', 'lula-mensagem-preso-b96-47') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 48 Dilma acusação
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_dilma, 'Dilma compara sua derrubada à tentativa de suicídio que a obrigaria a engolir afronta.', 'Me subestimaram. Mulher é forte, especialmente mulher que foi presa e torturada. Eles não sabem o que estão fazendo.', 'Entrevista à imprensa internacional em junho de 2016, durante o processo no Senado.', 'verified', false, '2016-06-09', 'https://www.bbc.com/portuguese/brasil-36483942', 'news_article', 1, 'Palácio da Alvorada', 'Entrevista à imprensa internacional', 'dilma-mulher-forte-b96-48') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_mis, true FROM ins;

  -- 49 Cunha cassado
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_cunha, 'Após ser cassado pela Câmara, Cunha ironiza dizendo que seus algozes vão pagar caro.', 'Vou aguardar. O tempo é o senhor da razão. Quem riu hoje talvez não ria amanhã.', 'Declaração após a Câmara cassar seu mandato por quebra de decoro em setembro de 2016.', 'verified', true, '2016-09-12', 'https://g1.globo.com/politica/noticia/2016/09/camara-cassa-mandato-de-eduardo-cunha.html', 'news_article', 3, 'Câmara dos Deputados', 'Cassação do mandato', 'cunha-cassado-algozes-b96-49') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_int, true FROM ins;

  -- 50 Temer indulto
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_temer, 'Temer assina indulto de Natal amplo, beneficiando condenados da Lava Jato.', 'Este decreto é tradicional e busca humanizar a aplicação da pena. Não se trata de beneficiar ninguém em especial.', 'Decreto de 22 de dezembro de 2017 que beneficiava condenados por corrupção, depois suspenso em parte pelo STF.', 'verified', true, '2017-12-22', 'https://www1.folha.uol.com.br/poder/2017/12/1945872-temer-assina-indulto-de-natal-que-pode-beneficiar-presos-da-lava-jato.shtml', 'news_article', 4, 'Palácio do Planalto', 'Decreto de indulto', 'temer-indulto-natal-b96-50') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_obs, true FROM ins UNION ALL SELECT id, c_abu, false FROM ins;

  -- 51 Moro Triplex
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_moro, 'Moro autoriza condução coercitiva de Lula em março de 2016 em fase espetaculosa da Lava Jato.', 'A condução coercitiva se justifica pela necessidade de esclarecimentos e para evitar que o investigado se furte à investigação.', 'Decisão que gerou imagens icônicas de Lula sendo levado para depor em Congonhas, depois apontada como excessiva.', 'verified', true, '2016-03-04', 'https://g1.globo.com/pr/parana/noticia/2016/03/pf-faz-operacao-contra-lula-por-suspeita-de-lavagem-de-dinheiro.html', 'news_article', 4, '13ª Vara Federal de Curitiba', 'Condução coercitiva', 'moro-conducao-lula-b96-51') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;

  -- 52 Moro vazamento grampo
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_moro, 'Moro divulga grampo da conversa de Lula e Dilma em manobra que desestabiliza o governo.', 'A democracia em uma sociedade livre exige que os governantes prestem contas, e os meios idôneos para tanto incluem a publicidade dos atos.', 'Decisão de 16 de março de 2016 tornou pública escuta ilegal de Dilma e Lula, considerada grave abuso pelo STF.', 'verified', true, '2016-03-16', 'https://www1.folha.uol.com.br/poder/2016/03/1751551-moro-divulga-conversas-de-lula-com-dilma-e-outras-autoridades.shtml', 'news_article', 5, '13ª Vara Federal de Curitiba', 'Divulgação de grampo', 'moro-grampo-lula-dilma-b96-52') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins UNION ALL SELECT id, c_ant, false FROM ins;

  -- 53 Bolsonaro cadeado Juiz
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jair, 'Bolsonaro diz em palanque que só aceita resultado da eleição se ele ganhar.', 'Eu só aceito o resultado se for eleito. Se houver fraude, vamos para a guerra.', 'Discurso em ato de campanha em Brasília em setembro de 2018.', 'verified', true, '2018-09-28', 'https://www1.folha.uol.com.br/poder/2018/09/bolsonaro-so-aceita-resultado-se-ganhar.shtml', 'news_article', 5, 'Brasília', 'Ato de campanha', 'bolsonaro-so-aceito-se-ganhar-b96-53') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins UNION ALL SELECT id, c_des, false FROM ins;

  -- 54 Bolsonaro fuzilar PT
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jair, 'Bolsonaro simula fuzilamento de petistas em Acre durante campanha.', 'Vamos fuzilar a petralhada do Acre. Esses marginais vermelhos serão banidos de nossa pátria.', 'Ato de campanha em Rio Branco em setembro de 2018 com gesto de fuzil.', 'verified', true, '2018-09-03', 'https://g1.globo.com/politica/eleicoes/2018/noticia/2018/09/03/bolsonaro-simula-fuzilamento-de-petistas-no-acre.ghtml', 'news_article', 5, 'Rio Branco', 'Ato de campanha', 'bolsonaro-fuzilar-petralhada-b96-54') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_vio, true FROM ins UNION ALL SELECT id, c_odi, false FROM ins UNION ALL SELECT id, c_ame, false FROM ins;

  -- 55 Bolsonaro Maria do Rosário
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jair, 'STF condena Bolsonaro por ofender Maria do Rosário ao dizer que não a estupraria porque ela não merece.', 'Não te estupro porque você não merece. Jamais iria estuprar você, porque você não merece.', 'Ofensas em plenário reiteradas em entrevista ao Zero Hora em dezembro de 2014 geraram condenação penal transitada em 2017.', 'verified', true, '2015-08-17', 'https://g1.globo.com/politica/noticia/2017/08/stf-aceita-denuncia-contra-bolsonaro-por-ofensa-maria-do-rosario.html', 'news_article', 5, 'Câmara dos Deputados', 'Processo por misoginia', 'bolsonaro-estupro-rosario-b96-55') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_mis, true FROM ins UNION ALL SELECT id, c_vio, false FROM ins;

  -- 56 Gleisi STF
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_gle, 'Gleisi é denunciada pela PGR por corrupção na Lava Jato e nega veementemente.', 'Nunca recebi nada da Petrobras ou de qualquer empreiteira. Essa denúncia é politicamente motivada.', 'Reação à denúncia apresentada pelo então PGR Janot em março de 2017.', 'verified', false, '2017-03-09', 'https://g1.globo.com/politica/operacao-lava-jato/noticia/gleisi-e-denunciada-por-janot-e-nega-acusacoes.ghtml', 'news_article', 2, 'Senado Federal', 'Reação à denúncia', 'gleisi-nega-denuncia-b96-56') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins;

  -- 57 Haddad Bolsonaro nazi
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_had, 'Haddad chama Bolsonaro de candidato do ódio e compara retórica a discursos fascistas.', 'O Brasil não pode abraçar o discurso do ódio e da intolerância que Bolsonaro prega todos os dias.', 'Debate na Band em 27 de setembro de 2018, último com todos os candidatos.', 'verified', true, '2018-09-27', 'https://g1.globo.com/politica/eleicoes/2018/noticia/2018/09/27/debate-band-haddad-ataca-bolsonaro.ghtml', 'news_article', 1, 'TV Bandeirantes', 'Debate presidencial', 'haddad-bolsonaro-odio-b96-57') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;

  -- 58 Ciro mulher Bolsonaro
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_ciro, 'Ciro Gomes ironiza disparos na campanha de Bolsonaro e chama candidato de covarde.', 'Bolsonaro é covarde. Não foi em debate algum. Só sabe falar pela internet para os seus fanáticos.', 'Coletiva após debate da Globo em 4 de outubro de 2018 que Bolsonaro não compareceu.', 'verified', false, '2018-10-04', 'https://g1.globo.com/politica/eleicoes/2018/noticia/2018/10/04/ciro-chama-bolsonaro-de-covarde.ghtml', 'news_article', 1, 'Rede Globo - São Paulo', 'Debate Globo', 'ciro-bolsonaro-covarde-b96-58') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 59 Alckmin fundão
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_alckmin, 'Alckmin capitaliza tempo de TV do centrão em 2018 e defende seu uso institucional.', 'Ter tempo de TV não é privilégio, é representação. O meu tempo é do povo que me elegeu governador quatro vezes.', 'Coletiva após firmar aliança com partidos do centrão em agosto de 2018.', 'verified', false, '2018-08-05', 'https://g1.globo.com/politica/eleicoes/2018/noticia/2018/08/05/alckmin-defende-aliancas-com-centrao.ghtml', 'news_article', 2, 'São Paulo', 'Aliança do centrão', 'alckmin-tempo-tv-centrao-b96-59') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_con, true FROM ins;

  -- 60 Dilma lembrança Cunha
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_dilma, 'Dilma afirma que Cunha a derrubou após chantagem por votos no Conselho de Ética.', 'Cunha me derrubou porque não aceitei ceder à sua chantagem. Não neguei nada, apenas não cedi a um criminoso.', 'Entrevista ao El País em dezembro de 2016 após impeachment.', 'verified', false, '2016-12-15', 'https://brasil.elpais.com/brasil/2016/12/15/politica/1481832517_134892.html', 'news_article', 2, 'Porto Alegre', 'Entrevista El País', 'dilma-cunha-chantagem-b96-60') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;

  -- 61 Temer reforma trabalhista
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_temer, 'Temer sanciona reforma trabalhista em cerimônia no Planalto defendendo flexibilização.', 'Esta reforma é uma conquista histórica. Vai gerar emprego e modernizar as relações de trabalho no Brasil.', 'Sanção da Lei 13.467 em 13 de julho de 2017.', 'verified', false, '2017-07-13', 'https://g1.globo.com/politica/noticia/temer-sanciona-reforma-trabalhista.ghtml', 'news_article', 2, 'Palácio do Planalto', 'Sanção da reforma trabalhista', 'temer-sanciona-reforma-trabalhista-b96-61') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 62 Temer greve caminhoneiros
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_temer, 'Temer autoriza uso das Forças Armadas para desobstruir estradas durante greve dos caminhoneiros.', 'Determinei o uso das Forças Armadas para garantir a liberdade de circulação. Não toleraremos bloqueios.', 'Pronunciamento em 25 de maio de 2018 durante a greve que paralisou o país.', 'verified', true, '2018-05-25', 'https://g1.globo.com/politica/noticia/temer-autoriza-forcas-armadas-greve-caminhoneiros.ghtml', 'news_article', 3, 'Palácio do Planalto', 'Greve dos caminhoneiros', 'temer-forcas-armadas-greve-b96-62') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;

  -- 63 Lula CNJ
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lula, 'Lula chama Moro de juiz parcial em entrevista concedida antes da prisão.', 'Moro é um juiz parcial. Ele quer ser meu algoz. A história vai provar que eu estou certo.', 'Entrevista à Carta Capital em fevereiro de 2018.', 'verified', false, '2018-02-07', 'https://www.cartacapital.com.br/politica/lula-chama-moro-de-parcial/', 'news_article', 1, 'São Paulo', 'Entrevista Carta Capital', 'lula-moro-parcial-b96-63') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;

  -- 64 Marta Suplicy PMDB
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_marta, 'Marta Suplicy filia-se ao PMDB e defende governo Temer.', 'O governo Temer precisa de apoio para tirar o Brasil da crise deixada pelo PT.', 'Coletiva de imprensa ao filiar-se ao PMDB em maio de 2016.', 'verified', false, '2016-05-27', 'https://g1.globo.com/politica/noticia/2016/05/marta-suplicy-se-filia-ao-pmdb.html', 'news_article', 2, 'Diretório PMDB', 'Filiação partidária', 'marta-filia-pmdb-b96-64') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 65 Maluf cassado
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_maluf, 'Maluf tem mandato cassado pela Câmara em maio de 2018 após começar a cumprir pena.', 'Vou recorrer. Ainda vou dar muita alegria ao povo paulistano que acredita em mim.', 'Declaração após a cassação pela Câmara dos Deputados em maio de 2018.', 'verified', false, '2018-05-30', 'https://g1.globo.com/politica/noticia/camara-cassa-mandato-paulo-maluf.ghtml', 'news_article', 2, 'Câmara dos Deputados', 'Cassação de mandato', 'maluf-cassado-alegria-b96-65') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins;

  -- 66 Sarney vaza delatado
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_sarney, 'Sarney nega acusações de delatores da Odebrecht que o colocam como beneficiário de caixa 2.', 'Nunca recebi um centavo ilegal em 60 anos de vida pública. Essas delações são uma farsa.', 'Nota oficial em abril de 2017 após lista do TSE envolvê-lo em 11 inquéritos da Lava Jato.', 'verified', false, '2017-04-13', 'https://www1.folha.uol.com.br/poder/2017/04/1875432-sarney-nega-acusacoes-da-odebrecht.shtml', 'news_article', 2, 'Residência - Brasília', 'Nota oficial', 'sarney-nega-odebrecht-b96-66') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins;

  -- 67 Renan aecio
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_renan, 'Renan defende volta de Aécio ao Senado mesmo após STF afastá-lo.', 'Aécio foi eleito pelo povo. O Senado tem prerrogativas próprias. Não cabe a um ministro do STF definir quem senta aqui.', 'Declaração após decisão da Primeira Turma do STF afastar Aécio em setembro de 2017.', 'verified', false, '2017-10-17', 'https://www12.senado.leg.br/noticias/materias/2017/10/17/renan-defende-aecio', 'news_article', 3, 'Senado Federal', 'Defesa de Aécio', 'renan-defende-aecio-b96-67') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;

  -- 68 Jefferson preso
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jefferson, 'Roberto Jefferson comenta da prisão de Lula e diz que o PT terá o mesmo destino do mensalão.', 'O Lula é o maior ladrão da história do país. Eu falei isso em 2005 e estão confirmando agora.', 'Entrevista concedida em abril de 2018 após o início da prisão de Lula.', 'verified', false, '2018-04-10', 'https://www.conjur.com.br/2018-abr-10/roberto-jefferson-lula-maior-ladrao', 'news_article', 2, 'Rio de Janeiro', 'Entrevista', 'jefferson-lula-maior-ladrao-b96-68') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;

  -- 69 Collor PF
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_collor, 'Collor acusa Polícia Federal de vazar busca a sua casa para a imprensa em 2015.', 'A Polícia Federal virou instrumento político. Vazar informação antes mesmo da operação é uma afronta à legalidade.', 'Pronunciamento no Senado em 14 de julho de 2015 após operação da PF em sua residência.', 'verified', false, '2015-07-14', 'https://www12.senado.leg.br/noticias/materias/2015/07/14/collor-acusa-pf-de-vazamento', 'news_article', 3, 'Senado Federal', 'Reação à operação da PF', 'collor-pf-vazamento-b96-69') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;

  -- 70 Guedes Chicago Boy
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_guedes, 'Guedes elogia Pinochet como modelo econômico em debates de 2018.', 'O Chile de Pinochet fez uma reforma da previdência maravilhosa. Nós vamos fazer algo parecido.', 'Declaração em seminário com investidores em São Paulo em outubro de 2018.', 'verified', true, '2018-10-29', 'https://www1.folha.uol.com.br/mercado/2018/10/guedes-elogia-modelo-pinochet.shtml', 'news_article', 4, 'São Paulo', 'Seminário econômico', 'guedes-elogia-pinochet-b96-70') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;

  -- 71 Lira votação reforma
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lira, 'Arthur Lira articula voto do centrão pela reforma da previdência de Temer em 2017.', 'A reforma é necessária. Não podemos deixar o Brasil afundar por causa do populismo.', 'Articulação em fevereiro de 2017 a favor da PEC da reforma da previdência apresentada pelo governo Temer.', 'verified', false, '2017-02-20', 'https://g1.globo.com/politica/noticia/lira-articula-reforma-previdencia-temer.ghtml', 'news_article', 1, 'Câmara dos Deputados', 'Articulação centrão', 'lira-previdencia-temer-b96-71') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 72 Pacheco impeachment
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_pacheco, 'Pacheco vota pelo impeachment de Dilma na Câmara em abril de 2016.', 'Voto pelo Brasil, pelas minhas crianças e pelo fim da era do PT. Meu voto é sim.', 'Voto nominal na sessão do impeachment em 17 de abril de 2016.', 'verified', false, '2016-04-17', 'https://www1.folha.uol.com.br/poder/2016/04/1763106-veja-como-votaram-os-deputados-no-impeachment.shtml', 'news_article', 2, 'Câmara dos Deputados', 'Votação impeachment', 'pacheco-voto-impeachment-b96-72') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;

  -- 73 Feliciano gays
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_feliciano, 'Feliciano ataca comunidade LGBT ao dizer que gays não nascem assim.', 'Ninguém nasce gay. É uma escolha ou consequência de abuso. Precisamos tratar essas pessoas com amor cristão.', 'Pregação em culto em São Paulo em agosto de 2017 gerou ação do MPF.', 'verified', true, '2017-08-06', 'https://www.cartacapital.com.br/politica/feliciano-diz-que-gays-nao-nascem-assim/', 'news_article', 4, 'Igreja evangélica - SP', 'Culto', 'feliciano-gays-nao-nascem-b96-73') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_hom, true FROM ins UNION ALL SELECT id, c_des, false FROM ins;

  -- 74 Silas Câmara bancada
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_silas, 'Silas Câmara articula bancada evangélica contra Estatuto da Família alternativo em 2015.', 'Família é pai, mãe e filhos. Ponto. Não podemos aceitar redefinição desse conceito por imposição de minorias.', 'Declaração ao defender PL 6.583/2013 na Comissão Especial em agosto de 2015.', 'verified', false, '2015-08-11', 'https://g1.globo.com/politica/noticia/2015/08/silas-camara-defende-estatuto-familia.html', 'news_article', 3, 'Câmara dos Deputados', 'Comissão Estatuto da Família', 'silas-estatuto-familia-b96-74') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_hom, true FROM ins;

  -- 75 Magno Malta Bolsonaro
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_magno, 'Magno Malta é cotado para vice de Bolsonaro em 2018 e defende pauta de costumes.', 'A família brasileira está sob ataque. Precisamos de gente comprometida com Deus no poder.', 'Evento evangélico em abril de 2018 em Vitória.', 'verified', false, '2018-04-15', 'https://www.gazetaonline.com.br/noticias/politica/magno-malta-defende-pauta-costumes-bolsonaro.html', 'news_article', 3, 'Vitória - ES', 'Evento evangélico', 'magno-malta-vice-bolsonaro-b96-75') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_hom, true FROM ins;

  -- 76 Damares bebê batom
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_damares, 'Damares defende o tapa na boca em criança em pregação viralizada.', 'Quando a minha filha pequena quis imitar menininho, eu dei um tapa na boca dela. Lugar de menina é brincar de boneca.', 'Pregação em culto evangélico gravada e viralizada em 2017.', 'verified', true, '2017-07-02', 'https://www1.folha.uol.com.br/cotidiano/2018/12/frases-polemicas-de-damares-alves-ministra-da-mulher.shtml', 'news_article', 4, 'Culto evangélico', 'Pregação viralizada', 'damares-tapa-boca-menina-b96-76') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_mac, true FROM ins UNION ALL SELECT id, c_vio, false FROM ins;

  -- 77 Freixo prefeitura 2016
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_freixo, 'Freixo disputa o segundo turno da prefeitura do Rio contra Crivella e denuncia crescimento do extremismo religioso.', 'O Rio não pode ser governado pela teocracia. A cidade é laica e das ruas.', 'Debate da Globo no segundo turno em outubro de 2016.', 'verified', false, '2016-10-27', 'https://g1.globo.com/rj/rio-de-janeiro/eleicoes/2016/noticia/2016/10/freixo-defende-estado-laico-em-debate.html', 'news_article', 1, 'Rede Globo Rio', 'Debate eleitoral', 'freixo-estado-laico-rio-b96-77') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 78 Chico Alencar denúncia
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_chico, 'Chico Alencar denuncia no plenário que Lava Jato seletiva protege tucanos da PSDB mineiro.', 'A operação prende petistas e liberta tucanos. Onde está a investigação sobre Aécio? Onde estão os inquéritos sobre Alckmin?', 'Discurso no plenário da Câmara em junho de 2017.', 'verified', false, '2017-06-22', 'https://g1.globo.com/politica/noticia/chico-alencar-denuncia-lava-jato-seletiva.ghtml', 'news_article', 1, 'Câmara dos Deputados', 'Pronunciamento no plenário', 'chico-alencar-lava-jato-seletiva-b96-78') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 79 Jandira defende Marielle
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jandira, 'Jandira Feghali exige resposta do governo Temer sobre a execução de Marielle Franco.', 'Marielle foi calada porque denunciava a milícia e a violência policial. O Estado tem responsabilidade.', 'Discurso na Câmara dos Deputados em 15 de março de 2018.', 'verified', false, '2018-03-15', 'https://www.camara.leg.br/noticias/jandira-feghali-cobra-apuracao-marielle', 'news_article', 1, 'Câmara dos Deputados', 'Discurso por Marielle', 'jandira-marielle-exige-resposta-b96-79') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_vio, true FROM ins;

  -- 80 Dilma veto
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_dilma, 'Dilma veta projeto que daria aumento a servidores e gera crise com base aliada no Congresso.', 'Tenho responsabilidade com o fiscal. Não posso assinar projeto que quebre o Tesouro.', 'Veto à MP que reajustava salários do Judiciário em agosto de 2015.', 'verified', false, '2015-08-25', 'https://g1.globo.com/politica/noticia/2015/08/dilma-veta-reajuste-do-judiciario.html', 'news_article', 1, 'Palácio do Planalto', 'Sessão de veto', 'dilma-veta-reajuste-judiciario-b96-80') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 81 Eduardo Bolsonaro homofobia
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro compara união homoafetiva a zoofilia em 2016.', 'Se permitirmos casamento gay, amanhã vão querer casar com animais. Onde vamos parar?', 'Postagem em rede social em março de 2016.', 'verified', false, '2016-03-18', 'https://www.cartacapital.com.br/politica/eduardo-bolsonaro-compara-uniao-homoafetiva-a-zoofilia', 'news_article', 4, 'Facebook', 'Postagem em rede social', 'eduardo-uniao-zoofilia-b96-81') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_hom, true FROM ins UNION ALL SELECT id, c_odi, false FROM ins;

  -- 82 Flavio Marielle
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fla, 'Flávio Bolsonaro homenageou ex-policial Adriano Nóbrega, ligado à investigação do caso Marielle.', 'Adriano Nóbrega é herói. Foi injustiçado pela corporação.', 'Homenagem concedida na Alerj em 2005 reaparece no contexto das investigações sobre Marielle em 2018.', 'verified', true, '2018-12-20', 'https://www1.folha.uol.com.br/poder/2018/12/flavio-bolsonaro-homenageou-policial-ligado-a-milicia.shtml', 'news_article', 5, 'Alerj', 'Revelação de homenagem', 'flavio-adriano-nobrega-b96-82') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_vio, true FROM ins UNION ALL SELECT id, c_con, false FROM ins;

  -- 83 Lula Curitiba
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lula, 'Lula diz em caravana pelo Nordeste que é perseguido por ser o ex-operário com maior aprovação da história.', 'Se eu fosse um ex-operário fracassado, ninguém me perseguiria. Me perseguem porque fui o presidente mais bem avaliado.', 'Discurso em Juazeiro-BA em 21 de agosto de 2017 na caravana do PT.', 'verified', false, '2017-08-21', 'https://g1.globo.com/ba/bahia/noticia/lula-discursa-em-juazeiro-durante-caravana-nordeste.ghtml', 'news_article', 1, 'Juazeiro - BA', 'Caravana pelo Nordeste', 'lula-caravana-juazeiro-b96-83') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 84 Bolsonaro facada
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jair, 'Após a facada em Juiz de Fora, Bolsonaro alimenta teoria conspiratória contra PT.', 'Isso não foi um lobo solitário. Tem muita gente por trás. O PT tem responsabilidade moral.', 'Entrevista do hospital Albert Einstein em 16 de setembro de 2018.', 'verified', true, '2018-09-16', 'https://g1.globo.com/politica/eleicoes/2018/noticia/2018/09/16/bolsonaro-atribui-facada-ao-pt-em-entrevista.ghtml', 'news_article', 4, 'Hospital Albert Einstein', 'Entrevista pós-facada', 'bolsonaro-facada-pt-b96-84') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins UNION ALL SELECT id, c_odi, false FROM ins;

  -- 85 Bolsonaro Nordeste
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jair, 'Bolsonaro faz piada sobre multiplicação dos pobres no Nordeste em convenção.', 'Eu fiz quatro. Dei uma fraquejada e veio uma mulher. A quinta eu tive uma filhinha. Isso foi uma fraquejada minha.', 'Discurso em palestra no Clube Hebraica em abril de 2017 envolveu ofensa a mulheres e ao Nordeste.', 'verified', true, '2017-04-03', 'https://www1.folha.uol.com.br/poder/2017/04/1874534-bolsonaro-diz-que-filha-foi-fraquejada.shtml', 'news_article', 4, 'Clube Hebraica', 'Palestra', 'bolsonaro-fraquejada-filha-b96-85') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_mis, true FROM ins UNION ALL SELECT id, c_mac, false FROM ins;

  -- 86 Haddad final campanha
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_had, 'Haddad denuncia disparos em massa de WhatsApp por empresários a favor de Bolsonaro.', 'Empresários estão financiando milhões de mensagens falsas contra mim. É caixa 2 eleitoral e é crime.', 'Coletiva em 18 de outubro de 2018 em resposta à reportagem da Folha.', 'verified', true, '2018-10-18', 'https://www1.folha.uol.com.br/poder/2018/10/empresarios-bancam-campanha-contra-pt-pelo-whatsapp.shtml', 'news_article', 2, 'São Paulo', 'Coletiva de imprensa', 'haddad-disparos-whatsapp-b96-86') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins UNION ALL SELECT id, c_cor, false FROM ins;

  -- 87 Temer propina
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_temer, 'Temer responde à segunda denúncia da PGR por obstrução de justiça e organização criminosa.', 'As denúncias são recheadas de ilações e fantasias. Continuarei trabalhando pelo Brasil.', 'Pronunciamento em 15 de setembro de 2017 após Janot apresentar a segunda denúncia.', 'verified', false, '2017-09-15', 'https://g1.globo.com/politica/noticia/temer-responde-a-segunda-denuncia-da-pgr.ghtml', 'news_article', 3, 'Palácio do Planalto', 'Resposta à denúncia', 'temer-segunda-denuncia-b96-87') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins;

  -- 88 Moro aceita convite
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_moro, 'Moro aceita convite para ministro da Justiça do eleito Bolsonaro em decisão que aprofunda suspeita sobre imparcialidade.', 'Aceito o convite para servir ao Brasil como ministro da Justiça. Buscaremos combate à corrupção, ao crime organizado e à violência.', 'Anúncio em 1 de novembro de 2018 após vitória de Bolsonaro, reforçando crítica ao julgamento de Lula.', 'verified', true, '2018-11-01', 'https://g1.globo.com/politica/noticia/2018/11/01/moro-aceita-convite-para-ministro-da-justica-de-bolsonaro.ghtml', 'news_article', 5, 'Curitiba', 'Aceite como ministro', 'moro-aceita-bolsonaro-b96-88') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_con, true FROM ins UNION ALL SELECT id, c_abu, false FROM ins;

  -- 89 Dilma rede
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_dilma, 'Dilma chama panelaço de resposta preconceituosa em rede nacional.', 'Os panelaços demonstram intolerância e não vontade democrática. Eu não vou ceder a esse tipo de pressão.', 'Pronunciamento em março de 2015 após panelaços nas janelas durante discurso oficial.', 'verified', false, '2015-03-08', 'https://g1.globo.com/politica/noticia/2015/03/dilma-rebate-panelaco.html', 'news_article', 1, 'Palácio do Planalto', 'Pronunciamento em rede', 'dilma-panelaco-intolerancia-b96-89') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 90 Cunha Waldir
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_cunha, 'Cunha blinda Waldir Maranhão para manobra que tentou anular o impeachment.', 'O rito precisa ser respeitado. O presidente interino da Câmara tem prerrogativas.', 'Cunha articula, do afastamento, manobra em 9 de maio de 2016 para tentar anular votação do impeachment.', 'verified', false, '2016-05-09', 'https://g1.globo.com/politica/processo-de-impeachment-de-dilma/noticia/2016/05/waldir-maranhao-tenta-anular-impeachment.html', 'news_article', 4, 'Câmara dos Deputados', 'Tentativa de anular impeachment', 'cunha-waldir-anular-b96-90') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins UNION ALL SELECT id, c_obs, false FROM ins;

  -- 91 Aecio afastamento
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_aecio, 'Aécio é afastado pelo STF após áudio com Joesley e reage chamando decisão de arbítrio.', 'A decisão do STF é uma arbitrariedade. Vou recorrer e provar que sou inocente.', 'Reação após a Primeira Turma do STF afastá-lo do Senado em 26 de setembro de 2017.', 'verified', false, '2017-09-26', 'https://www12.senado.leg.br/noticias/materias/2017/09/26/stf-afasta-aecio-neves-do-senado', 'news_article', 3, 'Senado Federal', 'Afastamento pelo STF', 'aecio-afastado-arbitrio-b96-91') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins;

  -- 92 Alckmin derrota 2018
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_alckmin, 'Alckmin reconhece derrota em 2018 com 4,76 porcento dos votos e comenta o avanço do bolsonarismo.', 'O resultado é uma lição. Teremos que refletir sobre o futuro do PSDB e da centro-direita.', 'Coletiva de imprensa após o primeiro turno em 7 de outubro de 2018.', 'verified', false, '2018-10-07', 'https://g1.globo.com/politica/eleicoes/2018/noticia/2018/10/07/alckmin-reconhece-derrota.ghtml', 'news_article', 1, 'São Paulo', 'Reconhecimento de derrota', 'alckmin-derrota-2018-b96-92') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 93 Gleisi JBS
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_gle, 'Gleisi diz que os áudios da JBS provam cartelização entre governo Temer e Aécio.', 'Temer e Aécio são farinha do mesmo saco. Os áudios escancaram a corrupção sistêmica.', 'Pronunciamento no Senado em 18 de maio de 2017 após revelação dos áudios.', 'verified', false, '2017-05-18', 'https://www12.senado.leg.br/noticias/materias/2017/05/18/gleisi-jbs-aecio-temer', 'news_article', 2, 'Senado Federal', 'Pronunciamento sobre JBS', 'gleisi-jbs-temer-aecio-b96-93') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins;

  -- 94 Ciro Lula prisão
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_ciro, 'Ciro comenta a prisão de Lula e classifica como abuso jurídico da Lava Jato.', 'Lula está preso sem provas materiais. Isso é abuso. A Lava Jato virou um instrumento político.', 'Entrevista ao Roda Viva em abril de 2018 durante campanha pré-eleitoral.', 'verified', false, '2018-04-09', 'https://tvcultura.com.br/rodaviva-ciro-gomes-lula/', 'news_article', 1, 'TV Cultura', 'Roda Viva', 'ciro-prisao-lula-abuso-b96-94') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_abu, true FROM ins;

  -- 95 Lira centrão Temer
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lira, 'Arthur Lira diz que o centrão garantirá governabilidade de Temer a despeito das denúncias.', 'O centrão não vai abandonar o governo. O presidente Temer merece concluir o mandato.', 'Entrevista concedida em 15 de outubro de 2017 durante a segunda denúncia.', 'verified', false, '2017-10-15', 'https://g1.globo.com/politica/noticia/lira-centrao-garantir-temer.ghtml', 'news_article', 3, 'Brasília', 'Entrevista', 'lira-centrao-garante-temer-b96-95') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_obs, true FROM ins;

  -- 96 Pacheco Lava Jato
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_pacheco, 'Pacheco defende Temer de segunda denúncia e diz que Brasil precisa de estabilidade.', 'O Brasil não aguenta mais um trauma institucional. Temos que votar contra a denúncia.', 'Discurso em outubro de 2017 na Câmara durante votação da segunda denúncia.', 'verified', false, '2017-10-25', 'https://www1.folha.uol.com.br/poder/2017/10/1928455-camara-rejeita-segunda-denuncia-contra-temer.shtml', 'news_article', 3, 'Câmara dos Deputados', 'Votação segunda denúncia', 'pacheco-estabilidade-temer-b96-96') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_obs, true FROM ins;

  -- 97 Feliciano campanha
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_feliciano, 'Feliciano declara apoio a Bolsonaro e ataca candidatura de Haddad em 2018.', 'Haddad é o mesmo PT corrupto travestido. Bolsonaro é a única alternativa para salvar o Brasil do comunismo.', 'Evento evangélico em São Paulo em 8 de outubro de 2018.', 'verified', false, '2018-10-08', 'https://www.cartacapital.com.br/politica/feliciano-apoia-bolsonaro-ataca-haddad/', 'news_article', 3, 'São Paulo', 'Evento evangélico', 'feliciano-apoio-bolsonaro-b96-97') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;

  -- 98 Silas câmara propina
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_silas, 'Silas Câmara é investigado por desvio da Assembleia e nega culpa em 2017.', 'Tudo é perseguição política. Nunca cometi irregularidade alguma em meu mandato.', 'Declaração após operação da PF que investigava fraude em verba indenizatória da Assembleia do AM.', 'verified', false, '2017-11-09', 'https://g1.globo.com/am/amazonas/noticia/silas-camara-investigado-indenizacao.ghtml', 'news_article', 3, 'Manaus', 'Operação da PF', 'silas-investigacao-am-b96-98') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_cor, true FROM ins;

  -- 99 Magno Malta voto aberto
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_magno, 'Magno Malta critica ativistas LGBT e diz não reconhecer a bandeira do arco-íris.', 'Essa bandeira do arco-íris não é do brasileiro. Brasileiro tem bandeira verde, amarela e azul.', 'Pronunciamento no Senado durante debate sobre gênero em 2016.', 'verified', false, '2016-06-30', 'https://www12.senado.leg.br/noticias/materias/2016/06/30/magno-malta-criticas-lgbt', 'news_article', 3, 'Senado Federal', 'Pronunciamento no plenário', 'magno-bandeira-arco-iris-b96-99') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_hom, true FROM ins UNION ALL SELECT id, c_odi, false FROM ins;

  -- 100 Damares ministério
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_damares, 'Damares Alves é anunciada ministra de Bolsonaro e prega que menino veste azul e menina veste rosa.', 'É uma nova era no Brasil. Menino veste azul e menina veste rosa.', 'Cerimônia de anúncio do ministério em 6 de dezembro de 2018 no CCBB de Brasília.', 'verified', true, '2018-12-06', 'https://g1.globo.com/politica/noticia/2018/12/06/bolsonaro-anuncia-damares-alves-para-ministerio-da-mulher.ghtml', 'news_article', 4, 'CCBB - Brasília', 'Anúncio do ministério', 'damares-menino-azul-menina-rosa-b96-100') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_mac, true FROM ins UNION ALL SELECT id, c_hom, false FROM ins;

END $$;
