-- Batch 84: Foreign policy Lula 3 (2023-2026) - BRICS, Gaza, Ucrânia, Venezuela, COP, Trump tariffs
-- 100 statements
DO $$
DECLARE
  v_lul UUID; v_mvi UUID; v_alc UUID; v_had UUID; v_msi UUID;
  v_cfa UUID; v_jai UUID; v_edu UUID; v_fla UUID; v_car UUID;
  v_dil UUID; v_fhc UUID; v_tem UUID; v_teb UUID; v_mer UUID;
  v_mor UUID; v_cir UUID; v_nik UUID; v_mvh UUID; v_pab UUID;
  v_tar UUID; v_hel UUID; v_rog UUID; v_hmo UUID; v_pgu UUID;
  v_asi UUID; v_jpp UUID; v_mch UUID; v_gle UUID; v_ran UUID;
  v_hum UUID; v_mpo UUID; v_dam UUID; v_mag UUID;
  c_ant UUID; c_des UUID; c_xen UUID; c_rac UUID; c_vio UUID;
  c_odi UUID; c_abu UUID; c_aut UUID; c_irr UUID; c_con UUID;
  c_ame UUID; c_neg UUID;
BEGIN
  SELECT id INTO v_lul FROM politicians WHERE slug = 'lula';
  SELECT id INTO v_mvi FROM politicians WHERE slug = 'mauro-vieira';
  SELECT id INTO v_alc FROM politicians WHERE slug = 'geraldo-alckmin';
  SELECT id INTO v_had FROM politicians WHERE slug = 'fernando-haddad';
  SELECT id INTO v_msi FROM politicians WHERE slug = 'marina-silva';
  SELECT id INTO v_cfa FROM politicians WHERE slug = 'carlos-favaro';
  SELECT id INTO v_jai FROM politicians WHERE slug = 'jair-bolsonaro';
  SELECT id INTO v_edu FROM politicians WHERE slug = 'eduardo-bolsonaro';
  SELECT id INTO v_fla FROM politicians WHERE slug = 'flavio-bolsonaro';
  SELECT id INTO v_car FROM politicians WHERE slug = 'carlos-bolsonaro';
  SELECT id INTO v_dil FROM politicians WHERE slug = 'dilma-rousseff';
  SELECT id INTO v_fhc FROM politicians WHERE slug = 'fernando-henrique';
  SELECT id INTO v_tem FROM politicians WHERE slug = 'michel-temer';
  SELECT id INTO v_teb FROM politicians WHERE slug = 'simone-tebet';
  SELECT id INTO v_mer FROM politicians WHERE slug = 'aloizio-mercadante';
  SELECT id INTO v_mor FROM politicians WHERE slug = 'sergio-moro';
  SELECT id INTO v_cir FROM politicians WHERE slug = 'ciro-gomes';
  SELECT id INTO v_nik FROM politicians WHERE slug = 'nikolas-ferreira';
  SELECT id INTO v_mvh FROM politicians WHERE slug = 'marcel-van-hattem';
  SELECT id INTO v_pab FROM politicians WHERE slug = 'pablo-marcal';
  SELECT id INTO v_tar FROM politicians WHERE slug = 'tarcisio-de-freitas';
  SELECT id INTO v_hel FROM politicians WHERE slug = 'helder-barbalho';
  SELECT id INTO v_rog FROM politicians WHERE slug = 'rogerio-marinho';
  SELECT id INTO v_hmo FROM politicians WHERE slug = 'hamilton-mourao';
  SELECT id INTO v_pgu FROM politicians WHERE slug = 'paulo-guedes';
  SELECT id INTO v_asi FROM politicians WHERE slug = 'alexandre-silveira';
  SELECT id INTO v_jpp FROM politicians WHERE slug = 'jean-paul-prates';
  SELECT id INTO v_mch FROM politicians WHERE slug = 'magda-chambriard';
  SELECT id INTO v_gle FROM politicians WHERE slug = 'gleisi-hoffmann';
  SELECT id INTO v_ran FROM politicians WHERE slug = 'randolfe-rodrigues';
  SELECT id INTO v_hum FROM politicians WHERE slug = 'humberto-costa';
  SELECT id INTO v_mpo FROM politicians WHERE slug = 'marcos-pontes';
  SELECT id INTO v_dam FROM politicians WHERE slug = 'damares-alves';
  SELECT id INTO v_mag FROM politicians WHERE slug = 'magno-malta';

  SELECT id INTO c_ant FROM categories WHERE slug = 'antidemocratico';
  SELECT id INTO c_des FROM categories WHERE slug = 'desinformacao';
  SELECT id INTO c_xen FROM categories WHERE slug = 'xenofobia';
  SELECT id INTO c_rac FROM categories WHERE slug = 'racismo';
  SELECT id INTO c_vio FROM categories WHERE slug = 'violencia';
  SELECT id INTO c_odi FROM categories WHERE slug = 'discurso-de-odio';
  SELECT id INTO c_abu FROM categories WHERE slug = 'abuso-de-poder';
  SELECT id INTO c_aut FROM categories WHERE slug = 'autoritarismo';
  SELECT id INTO c_irr FROM categories WHERE slug = 'irresponsabilidade';
  SELECT id INTO c_con FROM categories WHERE slug = 'conflito-interesses';
  SELECT id INTO c_ame FROM categories WHERE slug = 'ameaca-instituicoes';
  SELECT id INTO c_neg FROM categories WHERE slug = 'negacionismo';

  -- 1
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula compara operação de Israel em Gaza ao Holocausto de Hitler.', 'O que está acontecendo na Faixa de Gaza com o povo palestino não existiu em nenhum outro momento histórico. Aliás, existiu: quando Hitler resolveu matar os judeus.', 'Declaração em entrevista coletiva em Adis Abeba, Etiópia, durante cúpula da União Africana em fevereiro de 2024. A fala provocou crise diplomática com Israel, que declarou Lula persona non grata.', 'verified', true, '2024-02-18', 'https://www1.folha.uol.com.br/mundo/2024/02/lula-compara-israel-holocausto-hitler.shtml', 'news_article', 5, 'Adis Abeba, Etiópia', 'Cúpula da União Africana', 'lula-israel-holocausto-hitler-b84-1') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;

  -- 2
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula classifica guerra em Gaza como genocídio contra o povo palestino.', 'Não é guerra, é genocídio. É um genocídio praticado por um exército altamente preparado contra mulheres e crianças.', 'Entrevista à imprensa durante visita oficial ao Egito, onde Lula cobrou cessar-fogo e acesso humanitário a Gaza.', 'verified', true, '2024-02-15', 'https://agenciabrasil.ebc.com.br/politica/noticia/2024-02/lula-gaza-genocidio-egito', 'news_article', 4, 'Cairo', 'Visita oficial ao Egito', 'lula-gaza-genocidio-egito-b84-2') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;

  -- 3
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula defende expansão do BRICS como contrapeso à hegemonia do G7.', 'O BRICS não quer ser contraponto ao G7, ao G20 ou aos Estados Unidos. Queremos nos organizar como Sul Global. Queremos uma nova ordem econômica mundial.', 'Discurso durante cúpula do BRICS em Joanesburgo, quando o bloco aprovou adesão de seis novos países incluindo Egito, Etiópia, Irã, Emirados Árabes, Arábia Saudita e Argentina.', 'verified', true, '2023-08-24', 'https://g1.globo.com/politica/noticia/2023/08/24/lula-brics-sul-global.ghtml', 'news_article', 2, 'Joanesburgo', 'XV Cúpula do BRICS', 'lula-brics-sul-global-b84-3') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 4
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula diz que Ucrânia e Rússia têm responsabilidades iguais pela guerra.', 'Os dois países estão tomando essa decisão da guerra. Às vezes você fica olhando e parece que um gosta de guerra. Tanto um quanto o outro são responsáveis.', 'Declaração em Abu Dhabi, nos Emirados Árabes, que provocou reação do governo de Zelensky e do Departamento de Estado dos EUA acusando Lula de repetir narrativa russa.', 'verified', true, '2023-04-15', 'https://www.reuters.com/world/lula-says-us-should-stop-encouraging-war-ukraine-2023-04-15/', 'news_article', 4, 'Abu Dhabi', 'Visita aos Emirados Árabes', 'lula-ucrania-russia-responsabilidades-b84-4') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;

  -- 5
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula sugere que EUA e UE incentivam a guerra na Ucrânia ao fornecer armas.', 'Os Estados Unidos precisam parar de incentivar a guerra e começar a falar de paz. A União Europeia precisa começar a falar de paz.', 'Declaração em coletiva na China ao lado do chanceler chinês, enquanto Lula defendia criação de um "clube da paz" mediador com China e Índia.', 'verified', true, '2023-04-14', 'https://www.bbc.com/portuguese/articles/cv2jpnpdxj2o', 'news_article', 4, 'Pequim', 'Visita de Estado à China', 'lula-eua-incentiva-guerra-b84-5') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 6
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula afirma que Zelensky também é responsável pela continuidade da guerra.', 'Zelensky não pode querer tudo. Ele gerou a guerra também. Não é só o Putin.', 'Declaração dada a jornalistas no Portugal, reiterando posição de equidistância que gerou desconforto em aliados ocidentais.', 'verified', false, '2023-04-22', 'https://www.folha.uol.com.br/mundo/2023/04/lula-zelensky-gerou-guerra.shtml', 'news_article', 4, 'Lisboa', 'Visita oficial a Portugal', 'lula-zelensky-gerou-guerra-b84-6') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;

  -- 7
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula chama Putin de amigo e diz que ele não será preso se vier ao G20 no Rio.', 'Se o Putin vier ao Brasil, quem decide se ele vai ser preso ou não é a Justiça. Não sou eu. Mas eu posso dizer uma coisa: se eu for presidente e ele vier ao Brasil, ele não tem por que ser preso.', 'Declaração em entrevista à TV indiana First Post sobre mandado de prisão do TPI contra Putin, antes da cúpula do G20 do Rio em 2024.', 'verified', true, '2023-09-09', 'https://g1.globo.com/mundo/g20/noticia/2023/09/09/lula-putin-g20-prisao.ghtml', 'news_article', 4, 'Nova Delhi', 'Cúpula do G20 na Índia', 'lula-putin-nao-preso-g20-b84-7') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;

  -- 8
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula recebe Xi Jinping em Brasília e reafirma parceria estratégica abrangente.', 'O Brasil e a China têm uma parceria que é estratégica e abrangente. Queremos construir juntos uma ordem mundial mais justa e um planeta mais sustentável.', 'Declaração conjunta após reunião bilateral com Xi Jinping no Palácio da Alvorada, quando foram assinados 37 acordos incluindo adesão do Brasil a iniciativas da Rota da Seda.', 'verified', true, '2024-11-20', 'https://agenciabrasil.ebc.com.br/politica/noticia/2024-11/lula-xi-parceria-brasil-china', 'news_article', 2, 'Brasília', 'Visita de Estado de Xi Jinping', 'lula-xi-parceria-brasilia-b84-8') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 9
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula chama Maduro de "normalidade democrática" venezuelana.', 'A Venezuela tem uma normalidade democrática muito melhor do que muita gente pensa. O Maduro foi eleito, tem um processo eleitoral e precisa ser respeitado.', 'Declaração a jornalistas em Brasília ao receber Maduro, que havia sido impedido de viajar a outros países pelas sanções americanas.', 'verified', true, '2023-05-29', 'https://www1.folha.uol.com.br/mundo/2023/05/lula-maduro-normalidade-democratica.shtml', 'news_article', 4, 'Brasília', 'Visita oficial de Nicolás Maduro', 'lula-maduro-normalidade-b84-9') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;

  -- 10
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula diz que narrativa de autoritarismo na Venezuela é construída por adversários.', 'Essa tese de que a Venezuela não é democracia é uma narrativa construída por quem é contra o Maduro. Eu acho que temos que ser ponderados.', 'Entrevista à Globonews durante viagem internacional, minimizando relatórios da ONU e OEA sobre perseguição política no regime chavista.', 'verified', false, '2023-05-30', 'https://g1.globo.com/mundo/noticia/2023/05/30/lula-venezuela-narrativa.ghtml', 'news_article', 4, 'Brasília', 'Entrevista Globonews', 'lula-venezuela-narrativa-b84-10') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 11
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula pede prova em ata após eleição venezuelana contestada.', 'Maduro sabe que me deve uma explicação. Ele deve ao Brasil, a Colômbia e ao México uma explicação sobre as atas.', 'Entrevista à Rádio Nacional, três semanas após eleição de 28 de julho de 2024 na Venezuela em que Maduro se declarou vencedor sem apresentar as atas eleitorais.', 'verified', true, '2024-08-15', 'https://agenciabrasil.ebc.com.br/politica/noticia/2024-08/lula-cobra-atas-maduro', 'news_article', 2, 'Brasília', 'Entrevista Rádio Nacional', 'lula-cobra-atas-maduro-b84-11') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 12
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula compara situação na Venezuela à de Cuba e diz que é "regime desagradável".', 'A Venezuela tem um regime muito desagradável. Eu sei disso. É autoritário. Mas não é ditadura.', 'Entrevista a jornalistas estrangeiros em que Lula tentou equilibrar crítica a Maduro após pressão internacional crescente.', 'verified', false, '2024-08-22', 'https://www.bbc.com/portuguese/articles/c20d1x9ypd1o', 'news_article', 3, 'Brasília', 'Entrevista coletiva', 'lula-venezuela-regime-desagradavel-b84-12') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 13
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula chama Milei de "maluco" e de "fascista" antes do segundo turno argentino.', 'Tem um maluco concorrendo no segundo turno da eleição argentina. É um fascista. É como se fosse uma cópia carbono do Bolsonaro.', 'Declaração em evento do PT em São Paulo, a semanas da eleição argentina. Gerou crise diplomática antes mesmo da posse de Milei.', 'verified', true, '2023-10-24', 'https://www.folha.uol.com.br/mundo/2023/10/lula-milei-maluco-fascista.shtml', 'news_article', 3, 'São Paulo', 'Evento do PT', 'lula-milei-maluco-fascista-b84-13') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_odi, true FROM ins;

  -- 14
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula não vai à posse de Milei após atritos pessoais com presidente argentino.', 'Eu não fui convidado para a posse do Milei. Se fosse convidado, eu não sei se iria. Ele disse tanta bobagem sobre mim que eu não me sinto à vontade.', 'Entrevista à GloboNews sobre ausência na posse argentina. Milei havia chamado Lula de corrupto e comunista em campanha.', 'verified', true, '2023-12-09', 'https://g1.globo.com/mundo/noticia/2023/12/09/lula-nao-vai-posse-milei.ghtml', 'news_article', 2, 'Brasília', 'Entrevista GloboNews', 'lula-nao-vai-posse-milei-b84-14') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 15
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula condiciona diálogo com Milei a pedido de desculpas pelo presidente argentino.', 'O Milei me chamou de comunista, de corrupto, de ladrão. Ele que tem que pedir desculpas. Eu não tenho nada para pedir.', 'Declaração após G20 do Rio de 2024, onde Milei e Lula não se cumprimentaram formalmente. Relação bilateral permaneceu congelada.', 'verified', true, '2024-11-19', 'https://www.clarin.com/mundo/lula-milei-pedir-disculpas_0_rioRJ5p3X8.html', 'news_article', 2, 'Rio de Janeiro', 'Cúpula do G20', 'lula-milei-pedir-desculpas-b84-15') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 16
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula defende BRICS criar moeda de comércio para reduzir dependência do dólar.', 'Por que todos os países precisam fazer comércio lastreado no dólar? Por que não podemos fazer comércio lastreado na nossa moeda?', 'Discurso em Xangai, no banco do BRICS presidido por Dilma Rousseff, defendendo alternativa ao dólar para transações comerciais entre países do bloco.', 'verified', true, '2023-04-13', 'https://www.reuters.com/world/americas/brazils-lula-calls-new-currency-trade-between-brics-countries-2023-04-13/', 'news_article', 3, 'Xangai', 'Visita ao Novo Banco de Desenvolvimento', 'lula-moeda-brics-xangai-b84-16') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 17
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula visita Cuba e defende fim do embargo americano à ilha.', 'O bloqueio econômico a Cuba é uma violação inaceitável dos direitos do povo cubano. Vou levar essa mensagem ao presidente Biden e à ONU.', 'Discurso em Havana durante visita oficial em que Lula recebeu condecoração máxima do governo cubano.', 'verified', false, '2023-09-16', 'https://agenciabrasil.ebc.com.br/internacional/noticia/2023-09/lula-cuba-embargo', 'news_article', 3, 'Havana', 'Cúpula do G77+China', 'lula-cuba-embargo-b84-17') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 18
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula elogia Ortega da Nicarágua apesar de perseguição a opositores.', 'Cada país tem seu processo. A Nicarágua tem suas especificidades históricas. Não podemos intervir em decisões soberanas.', 'Entrevista a jornalistas quando questionado sobre expulsão de 222 presos políticos da Nicarágua por Daniel Ortega em 2023.', 'verified', false, '2023-02-20', 'https://www1.folha.uol.com.br/mundo/2023/02/lula-ortega-nicaragua.shtml', 'news_article', 4, 'Brasília', 'Entrevista coletiva', 'lula-ortega-nicaragua-b84-18') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 19
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula assina pacote de cooperação econômica com Angola e elogia João Lourenço.', 'Angola é parceiro estratégico do Brasil na África. Queremos estreitar laços econômicos e retomar obras de infraestrutura.', 'Declaração conjunta em Luanda em visita oficial, quando foram assinados acordos para reativar projetos da Odebrecht na África.', 'verified', false, '2023-08-10', 'https://g1.globo.com/mundo/noticia/2023/08/10/lula-angola-joao-lourenco.ghtml', 'news_article', 2, 'Luanda', 'Visita oficial a Angola', 'lula-angola-lourenco-b84-19') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 20
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula se solidariza com África do Sul em processo contra Israel na CIJ.', 'O Brasil apoia a ação da África do Sul na Corte Internacional de Justiça. O genocídio precisa ser reconhecido e precisa parar.', 'Declaração em coletiva em Brasília após decisão preliminar da CIJ em Haia reconhecendo risco plausível de genocídio em Gaza.', 'verified', true, '2024-01-26', 'https://www.aljazeera.com/news/2024/1/26/brazil-backs-south-africa-case-against-israel', 'news_article', 4, 'Brasília', 'Coletiva de imprensa', 'lula-solidariedade-africa-sul-cij-b84-20') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;

  -- 21
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula discursa na COP28 em Dubai defendendo financiamento climático de países ricos.', 'Os países ricos fizeram a sujeira por 200 anos e agora querem que nós paguemos a conta. Isso não é justo. É justiça climática.', 'Discurso na plenária de chefes de Estado da COP28 em Dubai, onde Lula anunciou meta de desmatamento zero na Amazônia até 2030.', 'verified', true, '2023-12-01', 'https://www.reuters.com/world/cop28-lula-climate-finance-rich-countries-2023-12-01/', 'news_article', 1, 'Dubai', 'COP28', 'lula-cop28-dubai-financiamento-b84-21') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 22
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula na COP29 em Baku critica países ricos por não cumprirem metas.', 'Os países desenvolvidos prometeram 100 bilhões de dólares e não cumpriram. Como vamos acreditar agora em novas promessas?', 'Discurso remoto na COP29 em Baku, Azerbaijão, em novembro de 2024. Lula não compareceu presencialmente por acidente doméstico.', 'verified', false, '2024-11-13', 'https://agenciabrasil.ebc.com.br/internacional/noticia/2024-11/lula-cop29-baku', 'news_article', 1, 'Brasília (por vídeo)', 'COP29 Baku', 'lula-cop29-baku-financiamento-b84-22') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 23
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula promete COP30 em Belém como marco histórico para Amazônia.', 'A COP30 em Belém vai ser a COP da Amazônia, a COP dos povos, a COP que vai restabelecer a confiança no multilateralismo climático.', 'Discurso na sessão de encerramento da COP29, quando Lula formalizou passagem da presidência para o Brasil na próxima conferência.', 'verified', true, '2024-11-22', 'https://g1.globo.com/meio-ambiente/cop-30/noticia/2024/11/22/lula-cop30-belem-amazonia.ghtml', 'news_article', 1, 'Baku/Brasília', 'Encerramento da COP29', 'lula-cop30-belem-marco-b84-23') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 24
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula reage a tarifas de Trump sobre Brasil como chantagem política.', 'O Trump não pode achar que o Brasil é colônia dele. Essa tarifa de 50% é uma chantagem política por causa do julgamento do Bolsonaro. Isso não vai ficar sem resposta.', 'Pronunciamento em cadeia nacional de rádio e TV após Trump anunciar tarifas adicionais de 50% sobre exportações brasileiras em julho de 2025.', 'verified', true, '2025-07-31', 'https://www1.folha.uol.com.br/mercado/2025/07/lula-trump-tarifa-chantagem.shtml', 'news_article', 3, 'Brasília', 'Pronunciamento em rede nacional', 'lula-trump-tarifa-chantagem-b84-24') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 25
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula acusa Eduardo Bolsonaro de traição à pátria por lobby em Washington.', 'Um deputado brasileiro foi para os Estados Unidos pedir sanção contra o Brasil, contra autoridades brasileiras. Isso tem nome: é traição à pátria.', 'Entrevista coletiva sobre atuação de Eduardo Bolsonaro em Washington articulando com governo Trump sanções contra ministros do STF.', 'verified', true, '2025-03-18', 'https://g1.globo.com/politica/noticia/2025/03/18/lula-eduardo-traicao-patria.ghtml', 'news_article', 3, 'Brasília', 'Coletiva de imprensa', 'lula-eduardo-traicao-patria-b84-25') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;

  -- 26
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula defende soberania brasileira e anuncia retaliação a tarifas de Trump.', 'Se os Estados Unidos taxarem o Brasil, nós vamos taxar os Estados Unidos. Não vamos ficar de joelho para ninguém. Soberania não se negocia.', 'Pronunciamento em Brasília anunciando lei de reciprocidade tarifária aprovada pelo Congresso em abril de 2025.', 'verified', true, '2025-04-02', 'https://agenciabrasil.ebc.com.br/economia/noticia/2025-04/lula-reciprocidade-trump', 'news_article', 2, 'Brasília', 'Cerimônia de sanção da Lei da Reciprocidade', 'lula-reciprocidade-trump-b84-26') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 27
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula defende que países pobres não sejam "mão-de-obra barata" para guerras.', 'Não podemos mais aceitar que os pobres sejam mão-de-obra para as guerras dos ricos. A juventude ucraniana e a juventude russa estão morrendo por interesses que não são deles.', 'Entrevista à RFI durante visita a Paris, em comentário que foi interpretado como equivalência entre agressor e agredido na guerra ucraniana.', 'verified', false, '2023-06-23', 'https://www.rfi.fr/br/brasil/20230623-lula-paris-ucrania-mao-de-obra', 'news_article', 3, 'Paris', 'Entrevista à RFI Brasil', 'lula-ucrania-mao-de-obra-b84-27') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 28
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula critica Zelensky por não comparecer a reunião marcada em Hiroshima.', 'O Zelensky marcou reunião comigo e não apareceu. Eu estava esperando. Ele deveria respeitar o tempo dos outros chefes de Estado.', 'Declaração a jornalistas após a cúpula do G7 em Hiroshima, Japão, em maio de 2023, após incidente diplomático com Zelensky.', 'verified', true, '2023-05-21', 'https://www.bbc.com/portuguese/articles/cg62x8j4kldo', 'news_article', 3, 'Hiroshima', 'Cúpula do G7', 'lula-zelensky-faltou-hiroshima-b84-28') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 29
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula se recusa a receber Zelensky no Brasil em 2023 após tensões.', 'Se o Zelensky quiser vir, ele vem. Se não quiser vir, não vem. Eu não posso sair correndo atrás dele.', 'Entrevista à Globonews após repetidas tentativas frustradas de encontro bilateral com o presidente ucraniano.', 'verified', false, '2023-08-05', 'https://g1.globo.com/politica/noticia/2023/08/05/lula-zelensky-recusa.ghtml', 'news_article', 2, 'Brasília', 'Entrevista Globonews', 'lula-zelensky-recusa-b84-29') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 30
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula defende ingresso de Brasil como membro permanente do Conselho de Segurança.', 'A ONU precisa ser reformada. O Conselho de Segurança não pode continuar com a mesma estrutura de 1945. O Brasil, a Índia, a África e a América Latina precisam de assento permanente.', 'Discurso na abertura da 78ª Assembleia-Geral da ONU em Nova York em setembro de 2023, tradicional primeira fala da abertura.', 'verified', true, '2023-09-19', 'https://agenciabrasil.ebc.com.br/politica/noticia/2023-09/lula-onu-reforma-conselho', 'news_article', 1, 'Nova York', 'Abertura da Assembleia Geral da ONU', 'lula-onu-reforma-conselho-b84-30') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 31
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula cobra Netanyahu na ONU e denuncia genocídio em Gaza.', 'Nunca em tempos recentes vimos tantos civis assassinados em tão pouco tempo. O que está acontecendo em Gaza não é uma guerra, é um genocídio praticado por um Estado que tem toda a tecnologia.', 'Discurso de abertura da 79ª Assembleia-Geral da ONU em 24 de setembro de 2024, pouco antes da fala de Netanyahu.', 'verified', true, '2024-09-24', 'https://www.folha.uol.com.br/mundo/2024/09/lula-onu-genocidio-gaza.shtml', 'news_article', 4, 'Nova York', 'Assembleia-Geral da ONU 2024', 'lula-onu-genocidio-b84-31') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, true FROM ins;

  -- 32
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula anuncia taxação global para super-ricos durante presidência do G20.', 'É hora de os super-ricos pagarem imposto. Não é possível que bilionários paguem proporcionalmente menos do que trabalhadores. Vamos levar isso para o G20.', 'Discurso em Davos no Fórum Econômico Mundial em janeiro de 2024, anunciando proposta que Haddad apresentaria ao G20.', 'verified', true, '2024-01-17', 'https://www.ft.com/content/lula-davos-tax-super-rich-g20', 'news_article', 1, 'Davos', 'Fórum Econômico Mundial', 'lula-davos-super-ricos-b84-32') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 33
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula recebe Putin por vídeo no BRICS e mantém postura não-alinhada.', 'O presidente Putin foi convidado, mas optou por participar à distância. Respeitamos a decisão e continuamos dialogando sobre paz na Ucrânia.', 'Declaração na abertura da XV Cúpula do BRICS, quando Putin participou remotamente devido ao mandado de prisão do TPI.', 'verified', false, '2023-08-22', 'https://www.reuters.com/world/lula-brics-putin-video-2023-08-22/', 'news_article', 2, 'Joanesburgo', 'XV Cúpula do BRICS', 'lula-putin-video-brics-b84-33') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 34
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula exalta adesão de Irã ao BRICS como vitória geopolítica.', 'A entrada do Irã no BRICS é uma vitória do multilateralismo e do respeito às diferenças. Não cabe aos Estados Unidos definir quem pode ou não participar.', 'Coletiva de imprensa em Joanesburgo após aprovação da ampliação do BRICS para 11 membros em agosto de 2023.', 'verified', false, '2023-08-24', 'https://www1.folha.uol.com.br/mundo/2023/08/lula-ira-brics.shtml', 'news_article', 3, 'Joanesburgo', 'XV Cúpula do BRICS', 'lula-ira-brics-vitoria-b84-34') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 35
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula critica disputa Essequibo e pede solução pacífica entre Venezuela e Guiana.', 'O Brasil não aceita nova guerra no continente sul-americano. A disputa entre Venezuela e Guiana precisa ser resolvida por vias diplomáticas.', 'Declaração em Brasília após Maduro realizar referendo sobre anexação do Essequibo em dezembro de 2023.', 'verified', true, '2023-12-05', 'https://g1.globo.com/mundo/noticia/2023/12/05/lula-essequibo-guiana-venezuela.ghtml', 'news_article', 2, 'Brasília', 'Coletiva de imprensa', 'lula-essequibo-paz-b84-35') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 36
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula declara Netanyahu criminoso de guerra e apoia ação do TPI.', 'Netanyahu precisa ser responsabilizado. Ele é um criminoso de guerra. O Tribunal Penal Internacional tem todo o respaldo do Brasil.', 'Entrevista a jornalistas em Brasília após TPI expedir mandados de prisão contra Netanyahu e Gallant em novembro de 2024.', 'verified', true, '2024-11-21', 'https://www.aljazeera.com/news/2024/11/21/lula-netanyahu-war-criminal-icc', 'news_article', 4, 'Brasília', 'Entrevista coletiva', 'lula-netanyahu-criminoso-guerra-b84-36') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_odi, true FROM ins;

  -- 37
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula recebe Abbas em Brasília e reafirma reconhecimento da Palestina.', 'A Palestina tem o direito de existir como Estado independente. O Brasil reconhece a Palestina desde 2010 e apoia a solução de dois Estados.', 'Cerimônia em Brasília com Mahmoud Abbas, presidente da Autoridade Palestina, para retomar relações bilaterais reforçadas.', 'verified', false, '2024-05-14', 'https://agenciabrasil.ebc.com.br/politica/noticia/2024-05/lula-abbas-palestina', 'news_article', 2, 'Brasília', 'Visita oficial de Mahmoud Abbas', 'lula-abbas-palestina-b84-37') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 38
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula reage a Israel declarando-o persona non grata após discurso do Holocausto.', 'Israel que se cuide. Eu não vou pedir desculpa. Eu não tenho do que me desculpar. Nós vamos manter nossa posição contra o genocídio.', 'Coletiva em Brasília após Israel declarar Lula persona non grata em fevereiro de 2024. Brasil chamou embaixador em Tel Aviv para consultas.', 'verified', true, '2024-02-19', 'https://www.bbc.com/portuguese/articles/czk03v4lz6po', 'news_article', 3, 'Brasília', 'Coletiva de imprensa', 'lula-israel-nao-pede-desculpa-b84-38') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 39
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula defende voto do Brasil pró-cessar-fogo na ONU apesar de pressão americana.', 'Eu não vou mudar minha posição por causa dos Estados Unidos. O Brasil vota a favor do cessar-fogo em Gaza porque crianças estão morrendo todos os dias.', 'Entrevista em Brasília após votação na Assembleia-Geral da ONU em que Brasil votou a favor do cessar-fogo humanitário em Gaza.', 'verified', false, '2023-10-27', 'https://g1.globo.com/mundo/noticia/2023/10/27/lula-onu-cessar-fogo-gaza.ghtml', 'news_article', 2, 'Brasília', 'Coletiva de imprensa', 'lula-onu-cessar-fogo-b84-39') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 40
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula critica Milei por ceder a Trump e romper Mercosul.', 'O Milei quer virar subordinado do Trump e destruir o Mercosul. Nós não vamos deixar. O Mercosul é maior que um governo passageiro.', 'Discurso em cúpula do Mercosul em Foz do Iguaçu em dezembro de 2024, quando Milei ameaçou saída unilateral do bloco.', 'verified', true, '2024-12-06', 'https://www.clarin.com/politica/lula-critica-milei-mercosur_0_xRJy82P3M7.html', 'news_article', 3, 'Foz do Iguaçu', 'Cúpula do Mercosul', 'lula-milei-mercosul-b84-40') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_odi, false FROM ins;

  -- 41
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula anuncia conclusão do acordo Mercosul-União Europeia após 25 anos.', 'Hoje é um dia histórico. Depois de 25 anos de negociação, o Mercosul e a União Europeia fecham um acordo que vai beneficiar 700 milhões de pessoas.', 'Declaração em Montevidéu em 6 de dezembro de 2024 ao lado da presidente da Comissão Europeia Ursula von der Leyen.', 'verified', true, '2024-12-06', 'https://www.ft.com/content/mercosur-eu-trade-deal-lula-von-der-leyen', 'news_article', 1, 'Montevidéu', 'Cúpula do Mercosul', 'lula-mercosul-ue-acordo-b84-41') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 42
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula critica sanções dos EUA contra Alexandre de Moraes.', 'Os Estados Unidos não têm o direito de sancionar um ministro da Suprema Corte brasileira. Isso é ingerência inaceitável. O Brasil é país soberano.', 'Pronunciamento em Brasília após Departamento do Tesouro americano incluir Moraes na Lei Magnitsky em 2025.', 'verified', true, '2025-07-20', 'https://www1.folha.uol.com.br/poder/2025/07/lula-sancao-moraes-magnitsky.shtml', 'news_article', 3, 'Brasília', 'Coletiva de imprensa', 'lula-moraes-magnitsky-b84-42') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 43
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula promete reciprocidade a Trump e cita exemplo da China.', 'A China mostrou que quando você é firme, o Trump recua. O Brasil vai fazer o mesmo. Não vamos ser humilhados.', 'Entrevista ao Globo sobre estratégia brasileira de enfrentamento às tarifas americanas de 50% em agosto de 2025.', 'verified', false, '2025-08-10', 'https://oglobo.globo.com/economia/lula-china-trump-reciprocidade-2025.ghtml', 'news_article', 2, 'Brasília', 'Entrevista O Globo', 'lula-china-trump-exemplo-b84-43') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 44
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula recebe Petro da Colômbia e articula frente progressista na América Latina.', 'A América Latina tem que falar com uma voz só. Nossa geração tem responsabilidade de deixar um continente mais justo, mais soberano.', 'Declaração em cúpula da CELAC em São Vicente e Granadinas em março de 2024 ao lado de Gustavo Petro.', 'verified', false, '2024-03-01', 'https://agenciabrasil.ebc.com.br/politica/noticia/2024-03/lula-petro-celac', 'news_article', 1, 'Kingstown', 'Cúpula da CELAC', 'lula-petro-celac-b84-44') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 45
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula diz que Obama e Biden erraram ao não apoiar Dilma em 2016.', 'Os Estados Unidos tinham informação sobre o que estava acontecendo no Brasil em 2016 e não fizeram nada. Isso foi um erro histórico.', 'Entrevista a documentário da Al Jazeera sobre intervenção estrangeira na América Latina em 2024.', 'verified', false, '2024-06-11', 'https://www.aljazeera.com/features/lula-obama-biden-dilma-2024', 'news_article', 3, 'Brasília', 'Entrevista Al Jazeera', 'lula-obama-biden-dilma-b84-45') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 46
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula anuncia plano de paz conjunto Brasil-China para Ucrânia.', 'O Brasil e a China apresentam um plano de seis pontos para a paz na Ucrânia. É hora de parar de mandar armas e começar a mandar mediadores.', 'Coletiva com chanceler chinês Wang Yi em Pequim em maio de 2024, apresentando plano que foi rejeitado por Kiev.', 'verified', true, '2024-05-23', 'https://www.reuters.com/world/brazil-china-ukraine-peace-plan-2024-05-23/', 'news_article', 3, 'Pequim', 'Plano de Paz Brasil-China', 'lula-plano-paz-china-b84-46') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 47
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula faz autocrítica sobre comparação Israel-Hitler mas não pede desculpas.', 'Talvez eu tivesse que ter usado outra palavra. Mas eu vi o que está acontecendo e ninguém vai me tirar o direito de dizer o que eu penso.', 'Entrevista à TV Record em março de 2024, minimizando o atrito sem retratar-se formalmente pela comparação com o Holocausto.', 'verified', false, '2024-03-04', 'https://www.folha.uol.com.br/poder/2024/03/lula-autocritica-hitler.shtml', 'news_article', 3, 'Brasília', 'Entrevista TV Record', 'lula-autocritica-hitler-b84-47') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 48
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula defende Hamas como movimento de resistência palestina.', 'O Hamas é consequência, não é causa. A causa é a ocupação israelense. Enquanto não houver Estado palestino, vai haver resistência.', 'Entrevista ao programa Conversa com Bial em dezembro de 2023, declaração que gerou protestos de comunidades judaicas.', 'verified', false, '2023-12-12', 'https://g1.globo.com/pop-arte/noticia/2023/12/12/lula-conversa-bial-hamas.ghtml', 'news_article', 4, 'Rio de Janeiro', 'Conversa com Bial', 'lula-hamas-resistencia-b84-48') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 49
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula compara ataque do Hamas a operação militar e relativiza ação terrorista.', 'O que o Hamas fez foi um ato terrorista. Mas o que Israel está fazendo também é terrorismo de Estado. Não existe moralidade diferente para os dois lados.', 'Entrevista à CNN Brasil em outubro de 2023, duas semanas após ataque de 7 de outubro do Hamas contra Israel.', 'verified', false, '2023-10-22', 'https://www.cnnbrasil.com.br/politica/lula-hamas-israel-terrorismo/', 'news_article', 4, 'Brasília', 'Entrevista CNN Brasil', 'lula-hamas-israel-equivalencia-b84-49') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 50
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mvi, 'Mauro Vieira condena bombardeio de Gaza em nome do Brasil na ONU.', 'O Conselho de Segurança falhou. Enquanto discutimos, crianças morrem em Gaza. O Brasil, na presidência rotativa, propõe cessar-fogo humanitário imediato.', 'Discurso do chanceler na presidência brasileira do Conselho de Segurança da ONU em outubro de 2023, após ataque a hospital Al-Ahli.', 'verified', true, '2023-10-18', 'https://agenciabrasil.ebc.com.br/internacional/noticia/2023-10/mauro-vieira-conselho-seguranca-gaza', 'news_article', 2, 'Nova York', 'Conselho de Segurança da ONU', 'mauro-vieira-conselho-seguranca-b84-50') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 51
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mvi, 'Mauro Vieira convoca embaixador israelense após declarações contra Lula.', 'O Brasil não aceitará interferência do governo israelense em assuntos internos. A fala do embaixador é inaceitável e requer explicações formais.', 'Nota do Itamaraty em fevereiro de 2024 convocando embaixador Daniel Zonshine após Israel declarar Lula persona non grata.', 'verified', true, '2024-02-19', 'https://www1.folha.uol.com.br/mundo/2024/02/mauro-vieira-convoca-embaixador-israel.shtml', 'news_article', 2, 'Brasília', 'Nota oficial do Itamaraty', 'mauro-vieira-convoca-embaixador-b84-51') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 52
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mvi, 'Mauro Vieira discursa na AG da ONU cobrando reforma do Conselho de Segurança.', 'O Conselho de Segurança das Nações Unidas é obsoleto. Sua paralisia diante de Gaza e Ucrânia prova que as estruturas de 1945 não servem ao mundo de hoje.', 'Discurso do chanceler representando Lula na 80ª Assembleia-Geral da ONU em setembro de 2025.', 'verified', false, '2025-09-24', 'https://agenciabrasil.ebc.com.br/politica/noticia/2025-09/mauro-vieira-onu-reforma', 'news_article', 1, 'Nova York', 'Assembleia-Geral da ONU 2025', 'mauro-vieira-onu-reforma-b84-52') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 53
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mvi, 'Mauro Vieira defende presença de Putin na cúpula do G20 no Rio.', 'Não cabe ao Brasil executar mandado de prisão em cúpula internacional. Esse não é nosso papel como anfitrião.', 'Declaração em Brasília sobre possível participação de Putin na cúpula do G20 de novembro de 2024.', 'verified', true, '2024-06-20', 'https://g1.globo.com/mundo/noticia/2024/06/20/mauro-vieira-putin-g20.ghtml', 'news_article', 3, 'Brasília', 'Entrevista coletiva', 'mauro-vieira-putin-g20-b84-53') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 54
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mvi, 'Mauro Vieira anuncia veto brasileiro a candidatura de Edmundo González.', 'O Brasil não reconhece eleição nem derrota na Venezuela sem que as atas sejam apresentadas. Nossa posição é de exigência de transparência.', 'Coletiva após reunião em Bogotá com colombianos e mexicanos tentando mediar crise pós-eleitoral venezuelana.', 'verified', false, '2024-08-20', 'https://www.bbc.com/portuguese/articles/cv1x2n4j9eko', 'news_article', 2, 'Bogotá', 'Reunião tripartite Brasil-Colômbia-México', 'mauro-vieira-venezuela-atas-b84-54') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 55
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mvi, 'Mauro Vieira convoca embaixador americano por sanção a Moraes.', 'As sanções unilaterais dos Estados Unidos contra um ministro da Suprema Corte do Brasil configuram ato grave de intervenção. O embaixador foi convocado.', 'Nota do Itamaraty em julho de 2025 após sanções de Magnitsky aplicadas pelo Tesouro americano.', 'verified', true, '2025-07-21', 'https://www1.folha.uol.com.br/mundo/2025/07/mauro-vieira-convoca-embaixador-eua.shtml', 'news_article', 3, 'Brasília', 'Nota oficial do Itamaraty', 'mauro-vieira-eua-moraes-b84-55') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 56
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_alc, 'Alckmin comemora acordo Mercosul-UE como salto econômico para o Brasil.', 'O acordo Mercosul-União Europeia é o maior acordo comercial da história do Brasil. Vai gerar empregos, aumentar exportações e atrair investimentos.', 'Coletiva do Ministério do Desenvolvimento em Montevidéu em dezembro de 2024, ao lado de Lula na assinatura do acordo.', 'verified', true, '2024-12-06', 'https://agenciabrasil.ebc.com.br/economia/noticia/2024-12/alckmin-mercosul-ue', 'news_article', 1, 'Montevidéu', 'Cúpula do Mercosul', 'alckmin-mercosul-ue-b84-56') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 57
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_alc, 'Alckmin lidera missão a Washington para negociar tarifas com Trump.', 'Viemos aqui para dialogar com o governo americano. O Brasil quer parceria, não confronto. Mas não abriremos mão da nossa soberania.', 'Declaração de Alckmin em Washington em agosto de 2025 durante reunião com secretário de Comércio americano Howard Lutnick.', 'verified', true, '2025-08-12', 'https://www.ft.com/content/alckmin-washington-tariffs-trump-2025', 'news_article', 1, 'Washington D.C.', 'Missão comercial brasileira', 'alckmin-washington-tarifas-b84-57') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 58
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_alc, 'Alckmin nega que Brasil renuncie a BRICS em troca de negociação com EUA.', 'Não existe escolha entre BRICS e Estados Unidos. O Brasil é país do Sul Global e parceiro histórico dos americanos. Fazemos negócios com todos.', 'Entrevista à Reuters em setembro de 2025, rebatendo pressão do governo Trump para que Brasil saísse do BRICS.', 'verified', false, '2025-09-15', 'https://www.reuters.com/world/americas/alckmin-brics-us-2025-09-15/', 'news_article', 2, 'São Paulo', 'Entrevista Reuters', 'alckmin-brics-eua-b84-58') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 59
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_had, 'Haddad apresenta ao G20 proposta de taxação global de super-ricos.', 'Vinte e três anos depois de Lula ter proposto o Bolsa Família, o Brasil propõe ao mundo o combate à desigualdade pelo topo. Taxar bilionários é justiça fiscal.', 'Discurso de Haddad em reunião de ministros das Finanças do G20 em São Paulo em fevereiro de 2024.', 'verified', true, '2024-02-29', 'https://www.ft.com/content/haddad-g20-billionaires-tax-sao-paulo', 'news_article', 1, 'São Paulo', 'Reunião do G20 Finanças', 'haddad-g20-super-ricos-b84-59') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 60
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_had, 'Haddad defende no FMI que riqueza mundial precisa ser redistribuída.', 'Precisamos de um FMI diferente. A riqueza mundial está se concentrando a velocidades sem precedentes. É urgente taxar fortunas globais.', 'Discurso na reunião anual do FMI em Washington em outubro de 2024.', 'verified', false, '2024-10-24', 'https://agenciabrasil.ebc.com.br/economia/noticia/2024-10/haddad-fmi-super-ricos', 'news_article', 1, 'Washington D.C.', 'Reunião Anual FMI', 'haddad-fmi-super-ricos-b84-60') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 61
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_had, 'Haddad anuncia medidas de contenção contra tarifas de Trump.', 'Vamos usar R$ 30 bilhões para socorrer setores afetados pelas tarifas americanas. Não deixaremos empresas brasileiras quebrarem por causa de decisão política de Trump.', 'Coletiva no Ministério da Fazenda em agosto de 2025 anunciando Plano Brasil Soberano.', 'verified', true, '2025-08-13', 'https://www1.folha.uol.com.br/mercado/2025/08/haddad-plano-brasil-soberano-trump.shtml', 'news_article', 2, 'Brasília', 'Coletiva Ministério da Fazenda', 'haddad-plano-brasil-soberano-b84-61') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

  -- 62
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_msi, 'Marina Silva critica países ricos por travarem financiamento climático.', 'A conta climática não está fechando. Os países ricos precisam de cem vezes mais ambição do que estão mostrando. Senão o planeta não aguenta.', 'Discurso de Marina Silva na plenária da COP29 em Baku em novembro de 2024.', 'verified', false, '2024-11-19', 'https://g1.globo.com/meio-ambiente/cop-29/noticia/2024/11/19/marina-cop29-financiamento.ghtml', 'news_article', 1, 'Baku', 'COP29', 'marina-cop29-financiamento-b84-62') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 63
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_msi, 'Marina anuncia que COP30 em Belém colocará povos indígenas no centro.', 'A COP30 vai ser diferente. Os povos indígenas vão estar no centro das decisões, não no entorno. A Amazônia precisa falar na COP da Amazônia.', 'Entrevista em Brasília em abril de 2025 anunciando organização da COP30 em Belém do Pará.', 'verified', false, '2025-04-15', 'https://agenciabrasil.ebc.com.br/meio-ambiente/noticia/2025-04/marina-cop30-belem-indigenas', 'news_article', 1, 'Brasília', 'Entrevista coletiva', 'marina-cop30-indigenas-b84-63') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 64
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_msi, 'Marina discursa em Dubai e anuncia retomada da liderança climática do Brasil.', 'O Brasil voltou à mesa. Não vamos mais envergonhar o mundo com desmatamento. Vamos liderar pelo exemplo.', 'Discurso de Marina Silva na plenária de alto nível da COP28 em Dubai em dezembro de 2023.', 'verified', false, '2023-12-02', 'https://www.reuters.com/business/environment/cop28-brazil-marina-silva-climate-leadership-2023-12-02/', 'news_article', 1, 'Dubai', 'COP28', 'marina-cop28-lideranca-b84-64') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 65
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_cfa, 'Carlos Fávaro critica UE por travar acordo Mercosul alegando ambiente.', 'Não é possível que o Brasil ensine a Europa sobre agricultura sustentável e ainda seja barrado. Somos a nação agrícola mais sustentável do mundo.', 'Entrevista do ministro da Agricultura a Valor Econômico em março de 2024 durante tensões do acordo Mercosul-UE.', 'verified', false, '2024-03-10', 'https://valor.globo.com/agronegocios/noticia/2024/03/10/favaro-mercosul-ue-sustentabilidade.ghtml', 'news_article', 2, 'Brasília', 'Entrevista Valor Econômico', 'favaro-mercosul-ue-b84-65') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 66
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro critica posição de Lula sobre Israel e chama de "ódio".', 'Essa comparação do Lula com Hitler é um escárnio. É ódio aos judeus falando mais alto do que qualquer política externa séria.', 'Entrevista a jornalistas em frente ao Alvorada em fevereiro de 2024 sobre crise diplomática Brasil-Israel.', 'verified', true, '2024-02-20', 'https://www1.folha.uol.com.br/poder/2024/02/bolsonaro-lula-hitler-israel.shtml', 'news_article', 3, 'Brasília', 'Entrevista a jornalistas', 'bolsonaro-lula-israel-b84-66') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_odi, false FROM ins;

  -- 67
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jai, 'Bolsonaro defende Netanyahu e critica ação da CIJ na Haia.', 'Israel tem o direito de se defender do terrorismo do Hamas. A Corte Internacional de Justiça está sendo usada por antissemitas para criminalizar uma democracia.', 'Postagem nas redes sociais de Bolsonaro em janeiro de 2024 após decisão da CIJ.', 'verified', false, '2024-01-27', 'https://g1.globo.com/politica/noticia/2024/01/27/bolsonaro-netanyahu-cij-haia.ghtml', 'news_article', 3, 'Brasília', 'Redes sociais', 'bolsonaro-netanyahu-cij-b84-67') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 68
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro articula com Trump sanções contra ministros do STF.', 'O governo americano precisa aplicar a Lei Magnitsky contra ministros do STF que perseguem conservadores no Brasil. Estamos trabalhando nisso.', 'Declaração em evento no CPAC em Washington em fevereiro de 2025, tornando pública pressão por sanções americanas.', 'verified', true, '2025-02-22', 'https://www.washingtonpost.com/world/2025/02/22/eduardo-bolsonaro-cpac-sanctions/', 'news_article', 5, 'Washington D.C.', 'CPAC 2025', 'eduardo-cpac-sancoes-b84-68') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;

  -- 69
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo pede que Trump intervenha para "libertar Brasil" da "ditadura" do STF.', 'Presidente Trump, ajude o Brasil. Meu pai é preso político. O STF virou ditadura. Sanções contra Moraes são urgentes para salvar a democracia brasileira.', 'Gravação de vídeo em inglês publicada em março de 2025 dirigido ao presidente americano.', 'verified', true, '2025-03-05', 'https://www.nytimes.com/2025/03/05/world/americas/eduardo-bolsonaro-trump-brazil.html', 'news_article', 5, 'Washington D.C.', 'Vídeo redes sociais', 'eduardo-trump-libertar-brasil-b84-69') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ant, true FROM ins;

  -- 70
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo Bolsonaro se licencia da Câmara para se estabelecer nos EUA.', 'Vou me licenciar do mandato para continuar a luta pelo Brasil a partir dos Estados Unidos. Aqui eu consigo articular apoio internacional.', 'Pronunciamento em vídeo anunciando licença do mandato de deputado federal em março de 2025.', 'verified', true, '2025-03-18', 'https://g1.globo.com/politica/noticia/2025/03/18/eduardo-licenca-camara-eua.ghtml', 'news_article', 4, 'Washington D.C.', 'Vídeo redes sociais', 'eduardo-licenca-camara-b84-70') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_con, true FROM ins;

  -- 71
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_edu, 'Eduardo celebra tarifas de Trump sobre Brasil como resposta ao STF.', 'A tarifa que Trump impôs é uma resposta firme ao STF. É consequência da perseguição ao meu pai. O Brasil está pagando caro pela ditadura de Moraes.', 'Postagem em X em julho de 2025 celebrando tarifa de 50% imposta por Trump.', 'verified', true, '2025-07-10', 'https://www1.folha.uol.com.br/poder/2025/07/eduardo-tarifa-trump-stf.shtml', 'news_article', 5, 'Washington D.C.', 'Rede social X', 'eduardo-tarifa-trump-comemora-b84-71') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_ame, true FROM ins;

  -- 72
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fla, 'Flávio Bolsonaro acusa Lula de destruir relação do Brasil com Israel.', 'Lula transformou o Brasil em pária internacional. Destruiu em meses uma relação de décadas com Israel. Isso é crime contra a pátria.', 'Discurso no Senado em março de 2024 durante sessão sobre crise diplomática com Israel.', 'verified', false, '2024-03-12', 'https://g1.globo.com/politica/noticia/2024/03/12/flavio-lula-israel-pais.ghtml', 'news_article', 2, 'Senado Federal', 'Sessão plenária', 'flavio-lula-israel-paria-b84-72') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 73
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fla, 'Flávio defende BRICS como ameaça à soberania brasileira.', 'Esse BRICS da moeda comum é um risco. Estamos nos atrelando à China, à Rússia, ao Irã. Os Estados Unidos vão retaliar e o povo é que vai pagar.', 'Entrevista à Jovem Pan em outubro de 2024 criticando cúpula do BRICS em Kazan.', 'verified', false, '2024-10-24', 'https://jovempan.com.br/noticias/politica/flavio-brics-moeda-china.html', 'news_article', 2, 'Brasília', 'Entrevista Jovem Pan', 'flavio-brics-ameaca-b84-73') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 74
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_car, 'Carlos Bolsonaro ataca embaixador brasileiro em Washington.', 'O embaixador Lyrio não representa o Brasil. Representa o PT. Está fazendo lobby contra os interesses do povo brasileiro em Washington.', 'Postagem no X em maio de 2025 atacando o embaixador Maria Luiza Viotti.', 'verified', false, '2025-05-18', 'https://www1.folha.uol.com.br/poder/2025/05/carlos-bolsonaro-embaixador-washington.shtml', 'news_article', 3, 'Rio de Janeiro', 'Rede social X', 'carlos-ataca-embaixador-b84-74') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 75
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_dil, 'Dilma assume presidência do Novo Banco de Desenvolvimento do BRICS.', 'É uma honra presidir o NDB. Vamos financiar infraestrutura, desenvolvimento e sustentabilidade nos países do Sul Global. Esta é uma nova ordem econômica.', 'Cerimônia de posse em Xangai em abril de 2023, após indicação de Lula.', 'verified', false, '2023-04-13', 'https://www.reuters.com/world/dilma-rousseff-ndb-brics-shanghai-2023-04-13/', 'news_article', 1, 'Xangai', 'Posse no NDB', 'dilma-posse-ndb-b84-75') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 76
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_dil, 'Dilma defende moeda comum dos BRICS para "desdolarizar" comércio.', 'O sistema financeiro mundial precisa de alternativas ao dólar. O NDB pode ser instrumento para que países do BRICS comerciem em suas próprias moedas.', 'Entrevista a Global Times em Pequim em outubro de 2024.', 'verified', false, '2024-10-20', 'https://www.globaltimes.cn/page/202410/dilma-brics-currency-ndb.html', 'news_article', 2, 'Pequim', 'Entrevista Global Times', 'dilma-moeda-brics-b84-76') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 77
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_fhc, 'FHC critica comparação de Lula entre Israel e Hitler como grave erro.', 'A comparação do presidente com o Holocausto é historicamente infundada e politicamente desastrosa. O Brasil perdeu credibilidade.', 'Artigo publicado no Estadão em fevereiro de 2024 criticando Lula.', 'verified', false, '2024-02-25', 'https://www.estadao.com.br/opiniao/fhc-lula-israel-hitler-erro-grave/', 'news_article', 2, 'São Paulo', 'Artigo no Estadão', 'fhc-lula-israel-critica-b84-77') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 78
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_tem, 'Temer critica política externa de Lula por ideologização excessiva.', 'A política externa do Brasil não pode ser ideológica. Temos que ser pragmáticos. O Lula está isolando o Brasil ao tomar lados em conflitos distantes.', 'Entrevista à Folha em junho de 2024 criticando diplomacia de Lula.', 'verified', false, '2024-06-08', 'https://www1.folha.uol.com.br/poder/2024/06/temer-lula-politica-externa.shtml', 'news_article', 2, 'São Paulo', 'Entrevista Folha de S.Paulo', 'temer-critica-politica-externa-b84-78') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 79
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_teb, 'Simone Tebet critica Lula por não condenar invasão russa de forma clara.', 'O governo não pode ter dois discursos. Se a Rússia invadiu território soberano, tem que ser dito. Equivalência não é neutralidade.', 'Declaração em entrevista à GloboNews em abril de 2023 sobre posição brasileira na ONU.', 'verified', false, '2023-04-18', 'https://g1.globo.com/politica/noticia/2023/04/18/tebet-lula-russia-ucrania.ghtml', 'news_article', 2, 'Brasília', 'Entrevista GloboNews', 'tebet-critica-ucrania-b84-79') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 80
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mor, 'Moro questiona no Senado a postura de Lula em relação à Venezuela.', 'O Brasil não pode chancelar fraudes eleitorais. O silêncio de Lula sobre as atas da Venezuela é cumplicidade. Isso é vergonhoso para nossa democracia.', 'Discurso no Senado em agosto de 2024 sobre crise eleitoral venezuelana.', 'verified', false, '2024-08-05', 'https://www.estadao.com.br/politica/moro-senado-venezuela-atas-lula-2024/', 'news_article', 2, 'Senado Federal', 'Sessão plenária', 'moro-venezuela-atas-b84-80') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 81
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_cir, 'Ciro Gomes classifica Lula de "idiota útil" de Putin e Maduro.', 'O Lula virou idiota útil de ditador. Defende Putin, defende Maduro, defende Ortega. Isso não é política externa altiva, é subserviência ideológica.', 'Entrevista ao Poder360 em julho de 2024 atacando postura de Lula.', 'verified', false, '2024-07-22', 'https://www.poder360.com.br/ciro-gomes-lula-idiota-util-2024/', 'news_article', 3, 'Fortaleza', 'Entrevista Poder360', 'ciro-lula-idiota-util-b84-81') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_odi, false FROM ins;

  -- 82
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_nik, 'Nikolas Ferreira viraliza vídeo contra Lula em inglês criticando Gaza.', 'Lula shames Brazil on the world stage. He compares Israel to Hitler while ignoring real genocide in Venezuela. Brazil deserves better leadership.', 'Vídeo em inglês publicado em fevereiro de 2024 atacando fala de Lula sobre Israel.', 'verified', true, '2024-02-21', 'https://www1.folha.uol.com.br/poder/2024/02/nikolas-ingles-lula-israel.shtml', 'news_article', 3, 'Belo Horizonte', 'Vídeo rede social', 'nikolas-ingles-lula-israel-b84-82') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_odi, false FROM ins;

  -- 83
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mvh, 'Marcel van Hattem defende apoio irrestrito do Brasil a Israel.', 'O Brasil deveria ser aliado incondicional de Israel. É a única democracia no Oriente Médio. Lula escolheu o lado errado da história.', 'Discurso na Câmara em novembro de 2023, logo após ataque do Hamas.', 'verified', false, '2023-11-08', 'https://www.camara.leg.br/noticias/marcel-van-hattem-israel-hamas-2023', 'news_article', 2, 'Câmara dos Deputados', 'Discurso em plenário', 'marcel-israel-apoio-b84-83') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 84
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_pab, 'Pablo Marçal elogia Milei e pede que Lula siga o "choque argentino".', 'O Milei está salvando a Argentina. Se Lula tivesse coragem de fazer choque liberal, o Brasil ia bombar. Mas ele prefere Maduro e Xi Jinping.', 'Live no Instagram em julho de 2024.', 'verified', false, '2024-07-15', 'https://g1.globo.com/sp/sao-paulo/eleicoes/2024/noticia/2024/07/15/pablo-marcal-milei-lula.ghtml', 'news_article', 2, 'São Paulo', 'Live Instagram', 'marcal-milei-lula-b84-84') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 85
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_tar, 'Tarcísio critica Lula por "transformar Brasil em pária" na ONU.', 'A política externa petista transformou o Brasil em pária internacional. Quem ganha são Rússia, China e Irã. Quem perde é o povo brasileiro.', 'Entrevista em São Paulo em outubro de 2024 em evento empresarial.', 'verified', false, '2024-10-10', 'https://www.estadao.com.br/politica/tarcisio-lula-paria-onu-2024/', 'news_article', 2, 'São Paulo', 'Evento empresarial FIESP', 'tarcisio-lula-paria-b84-85') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 86
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_hel, 'Helder Barbalho articula COP30 em Belém e defende investimentos na Amazônia.', 'Belém vai sediar a COP mais importante da história. O Pará está pronto. Precisamos que os países ricos venham com dinheiro, não com promessas.', 'Entrevista à Agência Brasil em março de 2025 sobre preparativos para COP30.', 'verified', false, '2025-03-20', 'https://agenciabrasil.ebc.com.br/politica/noticia/2025-03/helder-cop30-belem', 'news_article', 1, 'Belém', 'Entrevista Agência Brasil', 'helder-cop30-belem-b84-86') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 87
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_rog, 'Rogério Marinho critica gastos de Lula em viagens internacionais.', 'O presidente viaja mais que empresário de sucesso. Gastou 100 milhões em viagens. Enquanto isso, o povo brasileiro sofre com inflação e juros altos.', 'Discurso no Senado em setembro de 2024 criticando viagens presidenciais.', 'verified', false, '2024-09-10', 'https://www12.senado.leg.br/noticias/rogerio-marinho-viagens-lula-2024', 'news_article', 1, 'Senado Federal', 'Sessão plenária', 'rogerio-viagens-lula-b84-87') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 88
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_hmo, 'Mourão critica aproximação de Lula com Rússia e China.', 'O Brasil precisa de política externa equilibrada. Não podemos virar vassalo da China nem aliado do Putin. Temos tradição atlantista que precisa ser respeitada.', 'Entrevista no Senado em maio de 2024 sobre política externa.', 'verified', false, '2024-05-22', 'https://www12.senado.leg.br/noticias/mourao-politica-externa-china-2024', 'news_article', 2, 'Senado Federal', 'Entrevista corredores', 'mourao-china-russia-b84-88') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 89
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_pgu, 'Paulo Guedes critica Haddad por taxação global no G20.', 'Taxar super-ricos no G20 é populismo barato. Os bilionários vão mudar de residência fiscal e o Brasil vai ficar sem investimento.', 'Entrevista em evento do Credit Suisse em São Paulo em março de 2024.', 'verified', false, '2024-03-14', 'https://valor.globo.com/financas/noticia/2024/03/14/paulo-guedes-haddad-taxacao.ghtml', 'news_article', 1, 'São Paulo', 'Evento Credit Suisse', 'guedes-haddad-taxacao-b84-89') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 90
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_asi, 'Alexandre Silveira anuncia parcerias de energia com BRICS.', 'O Brasil vai cooperar com China e Índia em energias renováveis. Nossa matriz é a mais limpa do mundo. Queremos exportar tecnologia e hidrogênio verde.', 'Declaração em Nova Delhi em fevereiro de 2024 em reunião de ministros de Energia do BRICS.', 'verified', false, '2024-02-05', 'https://agenciabrasil.ebc.com.br/politica/noticia/2024-02/silveira-brics-energia', 'news_article', 1, 'Nova Delhi', 'Reunião de Energia do BRICS', 'silveira-brics-energia-b84-90') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 91
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_jpp, 'Jean Paul Prates defende Petrobras em parcerias internacionais.', 'A Petrobras vai retomar atuação internacional. Venezuela, Bolívia, África. Voltamos ao mapa da energia global.', 'Entrevista à CNN Brasil em janeiro de 2024 sobre expansão internacional da Petrobras.', 'verified', false, '2024-01-19', 'https://www.cnnbrasil.com.br/economia/jean-paul-prates-petrobras-internacional/', 'news_article', 1, 'Rio de Janeiro', 'Entrevista CNN Brasil', 'prates-petrobras-internacional-b84-91') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 92
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_gle, 'Gleisi Hoffmann ataca Eduardo Bolsonaro por lobby contra o Brasil em Washington.', 'Eduardo Bolsonaro é traidor da pátria. Está em Washington trabalhando contra os interesses do Brasil. Precisa ser cassado por crime contra a soberania nacional.', 'Entrevista em Brasília em março de 2025 pedindo cassação do mandato de Eduardo Bolsonaro.', 'verified', false, '2025-03-22', 'https://www1.folha.uol.com.br/poder/2025/03/gleisi-eduardo-traidor.shtml', 'news_article', 3, 'Brasília', 'Entrevista coletiva', 'gleisi-eduardo-traidor-b84-92') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_odi, false FROM ins;

  -- 93
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_ran, 'Randolfe Rodrigues defende soberania brasileira contra tarifas de Trump.', 'O Brasil não vai se ajoelhar para Trump. Temos que responder à altura. Se ele aumenta tarifas, nós aumentamos também. É reciprocidade ou rendição.', 'Entrevista no Senado em agosto de 2025 apoiando lei de reciprocidade.', 'verified', false, '2025-08-05', 'https://www12.senado.leg.br/noticias/randolfe-reciprocidade-trump-2025', 'news_article', 2, 'Senado Federal', 'Entrevista coletiva', 'randolfe-trump-reciprocidade-b84-93') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 94
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_hum, 'Humberto Costa lidera pressão no Senado por defesa de Moraes.', 'As sanções americanas contra ministro do STF são afronta intolerável. O Senado brasileiro repudia e exige resposta firme do governo Lula.', 'Discurso como líder do PT no Senado em julho de 2025.', 'verified', false, '2025-07-22', 'https://www12.senado.leg.br/noticias/humberto-costa-moraes-sancoes-2025', 'news_article', 2, 'Senado Federal', 'Discurso em plenário', 'humberto-moraes-sancoes-b84-94') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 95
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mpo, 'Marcos Pontes critica aproximação com China em área espacial.', 'Depender da China na área espacial é risco estratégico enorme. Estamos entregando tecnologia sensível e ganhando pouco em troca.', 'Discurso no Senado em setembro de 2024 criticando cooperação Brasil-China.', 'verified', false, '2024-09-25', 'https://www12.senado.leg.br/noticias/marcos-pontes-china-espacial-2024', 'news_article', 2, 'Senado Federal', 'Sessão plenária', 'pontes-china-espacial-b84-95') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 96
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_dam, 'Damares defende Israel no plenário e critica Lula como antissemita.', 'O presidente Lula é antissemita. Ele ofendeu o povo judeu, ofendeu as vítimas do Holocausto. O Brasil deve a Israel um pedido de desculpas.', 'Discurso no Senado em fevereiro de 2024 após declaração de Lula em Adis Abeba.', 'verified', false, '2024-02-26', 'https://www12.senado.leg.br/noticias/damares-lula-antissemita-israel-2024', 'news_article', 3, 'Senado Federal', 'Sessão plenária', 'damares-lula-antissemita-b84-96') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_odi, false FROM ins;

  -- 97
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mag, 'Magno Malta ataca governo Lula por aproximação com Irã.', 'Esse governo está entregando o Brasil a Irã, a Hamas, a Hezbollah. Isso é perigoso. Estamos nos tornando alvo de terroristas.', 'Discurso no Senado em novembro de 2023 após aproximação do Brasil com Irã no BRICS.', 'verified', false, '2023-11-15', 'https://www12.senado.leg.br/noticias/magno-malta-ira-hamas-2023', 'news_article', 3, 'Senado Federal', 'Sessão plenária', 'malta-ira-hamas-b84-97') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_des, false FROM ins;

  -- 98
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mer, 'Mercadante anuncia no BNDES financiamentos em parceria com BRICS.', 'O BNDES vai ser ponte entre Brasil e NDB. Vamos co-financiar projetos de infraestrutura. O Sul Global vai se desenvolver com nossos recursos.', 'Declaração no Fórum Econômico do BRICS em Moscou em junho de 2024.', 'verified', false, '2024-06-05', 'https://agenciabrasil.ebc.com.br/economia/noticia/2024-06/mercadante-bndes-brics', 'news_article', 1, 'Moscou', 'Fórum Econômico do BRICS', 'mercadante-bndes-brics-b84-98') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, false FROM ins;

  -- 99
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_mch, 'Magda Chambriard defende exploração na Margem Equatorial perto de COP30.', 'A Petrobras precisa explorar na Margem Equatorial. Não é contradição com a COP30. O Brasil precisa de receita para fazer transição energética.', 'Entrevista à Folha em fevereiro de 2025 em resposta a Marina Silva.', 'verified', false, '2025-02-18', 'https://www1.folha.uol.com.br/mercado/2025/02/chambriard-margem-equatorial-cop30.shtml', 'news_article', 3, 'Rio de Janeiro', 'Entrevista Folha de S.Paulo', 'chambriard-margem-cop30-b84-99') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_con, false FROM ins;

  -- 100
  WITH ins AS (INSERT INTO statements (politician_id, summary, full_quote, context, verification_status, is_featured, statement_date, primary_source_url, primary_source_type, severity_score, venue, event_name, slug) VALUES (v_lul, 'Lula anuncia abertura da COP30 em Belém com discurso de defesa da floresta.', 'A COP30 começa aqui em Belém, no coração da Amazônia. Esta é a hora da verdade. Ou salvamos a floresta, ou a humanidade não tem futuro.', 'Discurso de abertura da COP30 em novembro de 2025, em Belém do Pará, com presença de líderes de mais de 150 países.', 'verified', true, '2025-11-10', 'https://g1.globo.com/meio-ambiente/cop-30/noticia/2025/11/10/lula-abertura-cop30-belem.ghtml', 'news_article', 1, 'Belém', 'Abertura da COP30', 'lula-abertura-cop30-belem-b84-100') ON CONFLICT (slug) DO NOTHING RETURNING id)
  INSERT INTO statement_categories (statement_id, category_id, is_primary) SELECT id, c_irr, true FROM ins;

END $$;
